import type { DatabaseSync } from "node:sqlite";
import type { ExecutionFill, ExecutionRecord, ExecutionRepository, ExecutionTransition } from "../../../apps/execution/src/durable-execution";

export interface DurableExecutionDatabase { readonly connection: DatabaseSync; transaction<T>(fn: () => T): T; }
export class SqliteDurableExecutionRepository implements ExecutionRepository {
  public constructor(private readonly db: DurableExecutionDatabase) {
    db.connection.exec(`CREATE TABLE IF NOT EXISTS execution_records (execution_id TEXT PRIMARY KEY, client_order_id TEXT NOT NULL UNIQUE, state TEXT NOT NULL, version INTEGER NOT NULL, record_json TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS execution_transitions (transition_id TEXT PRIMARY KEY, execution_id TEXT NOT NULL, sequence INTEGER NOT NULL, transition_json TEXT NOT NULL, UNIQUE(execution_id, sequence)); CREATE TABLE IF NOT EXISTS execution_fills (fill_id TEXT PRIMARY KEY, execution_id TEXT NOT NULL, exchange_trade_id TEXT NOT NULL UNIQUE, fill_json TEXT NOT NULL);`);
  }
  get(id: string): ExecutionRecord | null { const r = this.db.connection.prepare("SELECT record_json FROM execution_records WHERE execution_id=?").get(id) as { record_json: string } | undefined; return r ? JSON.parse(r.record_json) as ExecutionRecord : null; }
  getByClientOrderId(id: string): ExecutionRecord | null { const r = this.db.connection.prepare("SELECT record_json FROM execution_records WHERE client_order_id=?").get(id) as { record_json: string } | undefined; return r ? JSON.parse(r.record_json) as ExecutionRecord : null; }
  save(record: ExecutionRecord, transition: ExecutionTransition): ExecutionRecord { return this.db.transaction(() => { const old = this.get(record.executionId); if (old && (record.version !== old.version + 1 || transition.sequence !== this.transitions(record.executionId).length + 1)) throw new Error("EXECUTION_VERSION_CONFLICT"); this.db.connection.prepare("INSERT INTO execution_records(execution_id,client_order_id,state,version,record_json,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(execution_id) DO UPDATE SET state=excluded.state,version=excluded.version,record_json=excluded.record_json,updated_at=excluded.updated_at").run(record.executionId, record.clientOrderId, record.state, record.version, JSON.stringify(record), record.updatedAt); this.db.connection.prepare("INSERT INTO execution_transitions(transition_id,execution_id,sequence,transition_json) VALUES(?,?,?,?)").run(transition.transitionId, transition.executionId, transition.sequence, JSON.stringify(transition)); return record; }); }
  transitions(id: string): readonly ExecutionTransition[] { const rows = this.db.connection.prepare("SELECT transition_json FROM execution_transitions WHERE execution_id=? ORDER BY sequence").all(id) as Array<{ transition_json: string }>; return Object.freeze(rows.map(x => JSON.parse(x.transition_json) as ExecutionTransition)); }
  fills(id: string): readonly ExecutionFill[] { const rows = this.db.connection.prepare("SELECT fill_json FROM execution_fills WHERE execution_id=? ORDER BY rowid").all(id) as Array<{ fill_json: string }>; return Object.freeze(rows.map(x => JSON.parse(x.fill_json) as ExecutionFill)); }
  appendFill(fill: ExecutionFill): void { this.db.connection.prepare("INSERT OR IGNORE INTO execution_fills(fill_id,execution_id,exchange_trade_id,fill_json) VALUES(?,?,?,?)").run(fill.fillId, fill.executionId, fill.exchangeTradeId, JSON.stringify(fill)); }
  listActive(): readonly ExecutionRecord[] { const rows = this.db.connection.prepare("SELECT record_json FROM execution_records WHERE state NOT IN ('RISK_REJECTED','REJECTED','FILLED','CANCELED','EXPIRED','RECONCILED') ORDER BY updated_at").all() as Array<{ record_json: string }>; return Object.freeze(rows.map(x => JSON.parse(x.record_json) as ExecutionRecord)); }
}
