import { DisasterRecoveryDecision, type DisasterRecoveryResult, type RecoveryDomainResult } from "../../../apps/execution/src/disaster-recovery";
import { StartupGateDecision, type StartupConsistencyResult } from "../../../apps/execution/src/startup-consistency-gate";
import type { RecoveryEvidenceRepository } from "../../../apps/execution/src/recovery-evidence";
import type { SqliteDatabase } from "./index";

type SqlRow=Record<string,string|number|bigint|null>;
export class SqliteRecoveryEvidenceRepository implements RecoveryEvidenceRepository{
  public constructor(private readonly db:SqliteDatabase){db.connection.exec(`CREATE TABLE IF NOT EXISTS disaster_recovery_runs(run_id TEXT PRIMARY KEY,decision TEXT NOT NULL,domains_json TEXT NOT NULL,blocking_domains_json TEXT NOT NULL,completed_at_ms TEXT NOT NULL);CREATE TABLE IF NOT EXISTS startup_gate_audits(audit_id TEXT PRIMARY KEY,recovery_run_id TEXT NOT NULL UNIQUE,decision TEXT NOT NULL,blockers_json TEXT NOT NULL,evaluated_at_ms TEXT NOT NULL,production_mutation_allowed INTEGER NOT NULL CHECK(production_mutation_allowed=0),FOREIGN KEY(recovery_run_id) REFERENCES disaster_recovery_runs(run_id));`);}
  appendRecovery(r:DisasterRecoveryResult):void{this.db.connection.prepare("INSERT INTO disaster_recovery_runs VALUES (?,?,?,?,?)").run(r.runId,r.decision,JSON.stringify(r.domains),JSON.stringify(r.blockingDomains),r.completedAtMs.toString());}
  getRecovery(runId:string):DisasterRecoveryResult|undefined{const r=this.db.connection.prepare("SELECT * FROM disaster_recovery_runs WHERE run_id=?").get(runId) as SqlRow|undefined;if(!r)return undefined;return Object.freeze({runId:String(r.run_id),decision:String(r.decision) as DisasterRecoveryDecision,domains:Object.freeze(JSON.parse(String(r.domains_json)) as RecoveryDomainResult[]),blockingDomains:Object.freeze(JSON.parse(String(r.blocking_domains_json)) as string[]),completedAtMs:Number(r.completed_at_ms)});}
  appendStartup(input:{readonly auditId:string;readonly recoveryRunId:string;readonly result:StartupConsistencyResult;readonly evaluatedAtMs:number}):void{if(!this.getRecovery(input.recoveryRunId))throw new Error("referenced recovery evidence does not exist");this.db.connection.prepare("INSERT INTO startup_gate_audits VALUES (?,?,?,?,?,0)").run(input.auditId,input.recoveryRunId,input.result.decision,JSON.stringify(input.result.blockers),input.evaluatedAtMs.toString());}
  getStartup(auditId:string){const r=this.db.connection.prepare("SELECT * FROM startup_gate_audits WHERE audit_id=?").get(auditId) as SqlRow|undefined;if(!r)return undefined;return Object.freeze({auditId:String(r.audit_id),recoveryRunId:String(r.recovery_run_id),result:Object.freeze({decision:String(r.decision) as StartupGateDecision,productionMutationAllowed:false as const,blockers:Object.freeze(JSON.parse(String(r.blockers_json)) as string[])}),evaluatedAtMs:Number(r.evaluated_at_ms)});}
}
