import type { DatabaseSync } from "node:sqlite";
import type { RegisteredStrategy, StrategyGovernanceEvent } from "../../contracts/src/strategyGovernance";
import { appendStrategyGovernanceEvent, replayStrategyGovernanceLedger, type StrategyGovernanceLedgerRecord } from "../../../apps/cloud/src/strategyGovernanceLedger";
export interface StrategyGovernanceDatabase { readonly connection:DatabaseSync; transaction<T>(fn:()=>T):T; }
export class SqliteStrategyGovernanceStore { constructor(private readonly db:StrategyGovernanceDatabase){this.db.connection.exec(`CREATE TABLE IF NOT EXISTS strategy_registry (strategy_id TEXT NOT NULL, version TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(strategy_id,version)); CREATE TABLE IF NOT EXISTS strategy_governance_events (sequence INTEGER PRIMARY KEY, previous_hash TEXT NOT NULL, event_json TEXT NOT NULL, hash TEXT NOT NULL UNIQUE); CREATE TABLE IF NOT EXISTS strategy_governance_state (id INTEGER PRIMARY KEY CHECK(id=1), snapshot_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS champion_assignments (family TEXT PRIMARY KEY, strategy_key TEXT NOT NULL); CREATE TABLE IF NOT EXISTS strategy_governance_commands (command_id TEXT PRIMARY KEY, fingerprint TEXT NOT NULL);`);}
  claimCommand(commandId:string,fingerprint:string):boolean{return this.db.transaction(()=>{if(!commandId.trim()||!fingerprint.trim())throw new Error("governance command is invalid");const existing=this.db.connection.prepare("SELECT fingerprint FROM strategy_governance_commands WHERE command_id=?").get(commandId) as {fingerprint:string}|undefined;if(existing){if(existing.fingerprint!==fingerprint)throw new Error("governance command conflict");return false;}this.db.connection.prepare("INSERT INTO strategy_governance_commands(command_id,fingerprint) VALUES(?,?)").run(commandId,fingerprint);return true;});}
  append(strategy:RegisteredStrategy,event:StrategyGovernanceEvent):void{this.db.transaction(()=>{const records=this.listEvents();const next=appendStrategyGovernanceEvent(records,event);this.db.connection.prepare("INSERT INTO strategy_registry(strategy_id,version,payload) VALUES(?,?,?) ON CONFLICT(strategy_id,version) DO NOTHING").run(strategy.identity.strategyId,strategy.identity.version,JSON.stringify(strategy));const stored=this.db.connection.prepare("SELECT payload FROM strategy_registry WHERE strategy_id=? AND version=?").get(strategy.identity.strategyId,strategy.identity.version) as {payload:string}|undefined;if(!stored||stored.payload!==JSON.stringify(strategy))throw new Error("strategy registry conflict");const r=next.at(-1)!;this.db.connection.prepare("INSERT INTO strategy_governance_events(sequence,previous_hash,event_json,hash) VALUES(?,?,?,?)").run(r.sequence,r.previousHash,JSON.stringify(r.event),r.hash);const replay=replayStrategyGovernanceLedger(next);const snapshot=JSON.stringify({hash:replay.hash,lifecycles:[...replay.lifecycles],champions:[...replay.champions]});this.db.connection.prepare("INSERT INTO strategy_governance_state(id,snapshot_json) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET snapshot_json=excluded.snapshot_json").run(snapshot);for(const [family,strategyKey] of replay.champions)this.db.connection.prepare("INSERT INTO champion_assignments(family,strategy_key) VALUES(?,?) ON CONFLICT(family) DO UPDATE SET strategy_key=excluded.strategy_key").run(family,strategyKey);});}
  listEvents():readonly StrategyGovernanceLedgerRecord[]{return Object.freeze((this.db.connection.prepare("SELECT * FROM strategy_governance_events ORDER BY sequence ASC").all() as Array<Record<string,unknown>>).map(r=>Object.freeze({sequence:Number(r.sequence),previousHash:String(r.previous_hash),event:JSON.parse(String(r.event_json)) as StrategyGovernanceEvent,hash:String(r.hash)})));}
  listStrategies(): readonly RegisteredStrategy[] { return Object.freeze((this.db.connection.prepare("SELECT payload FROM strategy_registry ORDER BY strategy_id ASC, version ASC").all() as Array<{ payload: string }>).map((row) => { const value = JSON.parse(row.payload) as RegisteredStrategy; if (!value.identity || !value.lifecycle) throw new Error("governance registry record malformed"); return Object.freeze({ identity: Object.freeze({ ...value.identity }), lifecycle: value.lifecycle }); })); }
  verify():void{const replay=replayStrategyGovernanceLedger(this.listEvents());const row=this.db.connection.prepare("SELECT snapshot_json FROM strategy_governance_state WHERE id=1").get() as {snapshot_json:string}|undefined;if(!row)throw new Error("governance snapshot missing");const s=JSON.parse(row.snapshot_json) as {hash:string};if(s.hash!==replay.hash)throw new Error("governance snapshot mismatch");}
}
