import React from "react";
import { RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { DataRow, NusaButton, NusaCard, StatusChip } from "./components";
import { InlineNotice, MetricTile, ScreenHeader } from "./uxPrimitives";
import { useTheme } from "./ThemeProvider";
import { createCashInvestmentEnvelope } from "./capitalAllocationGuard";
import type { PersonalPaperOperationsLoadResult } from "./personalPaperOperationsClient";

type Snapshot = Extract<PersonalPaperOperationsLoadResult, { status: "READY" }>["snapshot"];
export type HomeDestination = "Markets" | "Trade" | "Portfolio" | "More";
interface HomeViewProps { readonly snapshot: Snapshot | null; readonly investmentPercent: number; readonly readOnlyError: string | null; readonly notConfigured: string | null; readonly refreshing: boolean; readonly onRefresh: () => void; readonly onGoSettings: () => void; readonly onNavigate: (destination: HomeDestination) => void; }
function krw(value: number): string { return `₩${Math.round(value).toLocaleString("ko-KR")}`; }
function healthTone(health: string | undefined): "success" | "warning" | "danger" { return health === "HEALTHY" || health === "READY" ? "success" : health === "FAIL_CLOSED" || health === "DOWN" ? "danger" : "warning"; }

export function HomeView({ snapshot, investmentPercent, readOnlyError, notConfigured, refreshing, onRefresh, onGoSettings, onNavigate }: HomeViewProps) {
  const { theme } = useTheme();
  const account = snapshot?.portfolio?.account ?? null;
  const allocation = account == null ? null : createCashInvestmentEnvelope(account.cash, investmentPercent);
  const totalPnl = account == null ? null : (account.realizedPnl ?? account.position.realizedPnl) + account.unrealizedPnl;
  const ai = snapshot?.ai ?? null;
  const aiTrustedConfidence = ai?.calibrationStatus === "CALIBRATED" ? `${Math.round(ai.confidence * 100)}%` : "-";
  const runtimeTone = healthTone(snapshot?.operations.runtimeState);
  const aiInsightAvailable = ai?.status === "AVAILABLE" && Boolean(ai.thesis?.trim()) && ai.evidenceReferences.length > 0;
  const nextAction = snapshot == null ? null : snapshot.health !== "HEALTHY" || snapshot.dashboard.killSwitchActive || !snapshot.readyForPaperOperations ? { title: "안전 상태를 먼저 확인하세요", detail: "차단·저하 또는 PAPER 운영 대기 상태에서는 주문보다 운영 상태 확인이 우선입니다.", label: "PAPER 상태 보기", destination: "Trade" as const, tone: "warning" as const } : aiInsightAvailable ? { title: "최신 AI 분석이 있습니다", detail: "검증된 분석과 근거를 읽기 전용으로 확인할 수 있습니다.", label: "AI 분석 보기", destination: "More" as const, tone: "info" as const } : { title: "시장 관찰을 이어가세요", detail: "AI 분석이 없을 때는 수신된 시장 데이터와 연결 상태부터 확인합니다.", label: "시장 보기", destination: "Markets" as const, tone: "primary" as const };

  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl tintColor={theme.colors.primary} refreshing={refreshing} onRefresh={onRefresh} />} testID="home-screen">
    <ScreenHeader eyebrow="PERSONAL PAPER" title="홈" description="자산, 현금 배분, 손익과 다음 행동을 한눈에 보여줍니다." statusLabel={snapshot?.health ?? (notConfigured ? "연결 필요" : "대기")} statusTone={snapshot ? healthTone(snapshot.health) : "warning"} />
    {readOnlyError ? <InlineNotice title="PAPER 서버 연결 오류" detail={readOnlyError} tone="danger" /> : null}
    {notConfigured ? <NusaCard testID="dashboard-session-card"><View style={styles.cardHeader}><View><Text style={[styles.cardEyebrow, { color: theme.colors.primary }]}>PAPER CONNECTION</Text><Text style={[styles.cardTitle, { color: theme.colors.text }]}>서버 연결이 필요합니다</Text></View><StatusChip label="설정 필요" tone="warning" /></View><Text style={[styles.body, { color: theme.colors.textMuted }]}>{notConfigured}</Text><NusaButton label="설정에서 PAPER 연결" onPress={onGoSettings} testID="dashboard-open-settings" /></NusaCard> : null}
    {snapshot ? <>
      <View style={styles.hero} testID="account-hero-card">
        <View style={styles.heroTop}><View><Text style={[styles.heroLabel, { color: theme.colors.textMuted }]}>PAPER EQUITY</Text><Text style={[styles.heroValue, { color: theme.colors.text }]} adjustsFontSizeToFit numberOfLines={1}>{account ? krw(account.equity) : "-"}</Text></View><StatusChip label={snapshot.operations.runtimeState} tone={runtimeTone} /></View>
        <View style={styles.heroMeta}>{totalPnl != null ? <Text style={[styles.heroPnl, { color: totalPnl >= 0 ? theme.colors.success : theme.colors.danger }]}>{totalPnl >= 0 ? "+" : ""}{krw(totalPnl)} 누적 손익</Text> : null}<Text style={[styles.heroAllocation, { color: theme.colors.textMuted }]}>{allocation ? `현금 ${allocation.investmentPercent}% 투자 · ${allocation.reservePercent}% 보호` : "현금 배분 정보 없음"}</Text></View>
      </View>
      {allocation ? <View style={[styles.allocationPanel, { borderColor: theme.colors.border }]} testID="home-allocation-panel">
        <View style={styles.allocationHeader}><View><Text style={[styles.cardEyebrow, { color: theme.colors.primary }]}>CASH ALLOCATION</Text><Text style={[styles.cardTitle, { color: theme.colors.text }]}>현금 배분</Text></View><Text style={[styles.allocationTotal, { color: theme.colors.textMuted }]}>{krw(account?.cash ?? 0)}</Text></View>
        <View style={[styles.allocationTrack, { backgroundColor: theme.colors.surfaceSunken }]}><View style={[styles.investedTrack, { width: `${allocation.investmentPercent}%`, backgroundColor: theme.colors.primary }]} /></View>
        <View style={styles.allocationValues}><View style={styles.allocationValue}><Text style={[styles.allocationLabel, { color: theme.colors.textMuted }]}>투자 가능</Text><Text style={[styles.allocationNumber, { color: theme.colors.text }]}>{krw(allocation.investableCash)}</Text><Text style={[styles.allocationPercent, { color: theme.colors.primary }]}>{allocation.investmentPercent}%</Text></View><View style={styles.allocationValue}><Text style={[styles.allocationLabel, { color: theme.colors.textMuted }]}>보호 현금</Text><Text style={[styles.allocationNumber, { color: theme.colors.text }]}>{krw(allocation.reservedCash)}</Text><Text style={[styles.allocationPercent, { color: theme.colors.textMuted }]}>{allocation.reservePercent}%</Text></View></View>
      </View> : null}
      <View style={styles.metrics}><MetricTile label="PAPER 준비" value={snapshot.readyForPaperOperations ? "준비됨" : "대기/차단"} detail="주문 가능 상태" tone={snapshot.readyForPaperOperations ? "success" : "warning"} /><MetricTile label="AI 신뢰도" value={aiTrustedConfidence} detail={ai?.calibrationStatus ?? "UNKNOWN"} tone={ai?.calibrationStatus === "CALIBRATED" ? "info" : "default"} /></View>
      {nextAction ? <View style={styles.nextAction}><InlineNotice title={nextAction.title} detail={nextAction.detail} tone={nextAction.tone === "primary" ? "info" : nextAction.tone} testID="home-next-action-notice" /><NusaButton accessibilityLabel={nextAction.label} label={nextAction.label} onPress={() => onNavigate(nextAction.destination)} testID="home-next-action-button" /></View> : null}
      <View style={styles.grid} testID="home-responsive-grid"><View style={styles.column}><NusaCard testID="ai-card"><View style={styles.cardHeader}><View><Text style={[styles.cardEyebrow, { color: theme.colors.info }]}>AI READ-ONLY</Text><Text style={[styles.cardTitle, { color: theme.colors.text }]}>AI 인텔리전스</Text></View><StatusChip label={ai?.status ?? "UNAVAILABLE"} tone={ai?.status === "AVAILABLE" ? "success" : ai?.status === "INCOMPLETE" ? "warning" : "neutral"} /></View><Text style={[styles.thesis, { color: ai?.thesis ? theme.colors.text : theme.colors.textMuted }]}>{ai?.thesis ?? "현재 표시할 AI 분석이 없습니다."}</Text><DataRow label="검증 신뢰도" value={aiTrustedConfidence} /><DataRow label="불확실성" value={ai?.uncertainty ?? "-"} /><NusaButton label="AI 자세히 보기" onPress={() => onNavigate("More")} tone="neutral" /></NusaCard></View><View style={styles.column}><NusaCard testID="safety-card"><View style={styles.cardHeader}><View><Text style={[styles.cardEyebrow, { color: theme.colors.textMuted }]}>SAFETY</Text><Text style={[styles.cardTitle, { color: theme.colors.text }]}>운영 상태</Text></View><StatusChip label={snapshot.health} tone={healthTone(snapshot.health)} /></View><DataRow label="PAPER 런타임" value={snapshot.operations.runtimeState} tone={runtimeTone} /><DataRow label="킬 스위치" value={snapshot.dashboard.killSwitchActive ? "활성" : "비활성"} tone={snapshot.dashboard.killSwitchActive ? "danger" : "success"} /><DataRow label="LIVE 권한" value={snapshot.liveAuthority} emphasis /><DataRow label="Production mutation" value={snapshot.productionMutationAllowed ? "허용" : "금지"} tone={snapshot.productionMutationAllowed ? "danger" : "success"} /><NusaButton label="PAPER 작업공간" onPress={() => onNavigate("Trade")} tone="neutral" /></NusaCard></View></View>
    </> : null}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 20, gap: 18, paddingBottom: 40, width: "100%", maxWidth: 1080, alignSelf: "center" }, hero: { paddingVertical: 4, gap: 10 }, heroTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }, heroLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1.3 }, heroValue: { marginTop: 4, fontSize: 46, lineHeight: 52, fontWeight: "800", letterSpacing: -2.1, fontVariant: ["tabular-nums"] }, heroMeta: { flexDirection: "row", flexWrap: "wrap", gap: 12, alignItems: "center" }, heroPnl: { fontSize: 15, lineHeight: 21, fontWeight: "700", fontVariant: ["tabular-nums"] }, heroAllocation: { fontSize: 13, lineHeight: 19, fontWeight: "600" }, allocationPanel: { borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 18, gap: 14 }, allocationHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 }, allocationTotal: { fontSize: 13, fontWeight: "600", fontVariant: ["tabular-nums"] }, allocationTrack: { height: 7, borderRadius: 999, overflow: "hidden" }, investedTrack: { height: "100%", borderRadius: 999 }, allocationValues: { flexDirection: "row", gap: 24, flexWrap: "wrap" }, allocationValue: { minWidth: 130, flexGrow: 1 }, allocationLabel: { fontSize: 11, fontWeight: "700" }, allocationNumber: { marginTop: 4, fontSize: 20, lineHeight: 26, fontWeight: "800", fontVariant: ["tabular-nums"] }, allocationPercent: { marginTop: 2, fontSize: 12, fontWeight: "700" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, nextAction: { gap: 10 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 14, alignItems: "flex-start" }, column: { flexGrow: 1, flexBasis: 440 }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 10 }, cardEyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginBottom: 4 }, cardTitle: { fontSize: 18, fontWeight: "700", letterSpacing: -0.4 }, thesis: { fontSize: 16, fontWeight: "600", lineHeight: 24, marginBottom: 10 }, body: { fontSize: 13, lineHeight: 20, marginTop: 8 } });