import React from "react";
import { RefreshControl, ScrollView, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { DataRow, MotionReveal, NusaButton, TerrainSignal } from "./components";
import { InlineNotice } from "./uxPrimitives";
import { useTheme } from "./ThemeProvider";
import { createCashInvestmentEnvelope } from "./capitalAllocationGuard";
import type { PersonalPaperOperationsLoadResult } from "./personalPaperOperationsClient";

type Snapshot = Extract<PersonalPaperOperationsLoadResult, { status: "READY" }>["snapshot"];
export type HomeDestination = "Markets" | "Trade" | "Portfolio" | "More";
interface HomeViewProps { readonly snapshot: Snapshot | null; readonly investmentPercent: number; readonly readOnlyError: string | null; readonly notConfigured: string | null; readonly refreshing: boolean; readonly onRefresh: () => void; readonly onGoSettings: () => void; readonly onNavigate: (destination: HomeDestination) => void; }
function krw(value: number): string { return `₩${Math.round(value).toLocaleString("ko-KR")}`; }
function healthTone(health: string | undefined): "success" | "warning" | "danger" { return health === "HEALTHY" || health === "READY" ? "success" : health === "FAIL_CLOSED" || health === "DOWN" ? "danger" : "warning"; }

export function HomeView({ snapshot, investmentPercent, readOnlyError, notConfigured, refreshing, onRefresh, onGoSettings, onNavigate }: HomeViewProps) {
  const { theme } = useTheme();
  const { width } = useWindowDimensions();
  const tablet = width >= 768;
  const account = snapshot?.portfolio?.account ?? null;
  const allocation = account == null ? null : createCashInvestmentEnvelope(account.cash, investmentPercent);
  const totalPnl = account == null ? null : (account.realizedPnl ?? account.position.realizedPnl) + account.unrealizedPnl;
  const ai = snapshot?.ai ?? null;
  const aiInsightAvailable = ai?.status === "AVAILABLE" && Boolean(ai.thesis?.trim()) && ai.evidenceReferences.length > 0;
  const allocationWidth = allocation ? `${allocation.investmentPercent}%` as `${number}%` : "0%";
  const signalReady = snapshot?.health === "HEALTHY" && snapshot.readyForPaperOperations;
  const nextAction = notConfigured
    ? { title: "PAPER 연결 설정", detail: "Settings에서 endpoint와 메모리 전용 세션 토큰을 검증하세요.", tab: null }
    : snapshot?.health !== "HEALTHY" || snapshot?.dashboard.killSwitchActive || !snapshot?.readyForPaperOperations
      ? { title: "PAPER 상태 보기", detail: "연결과 안전 상태를 확인하세요.", tab: "Markets" as const }
      : aiInsightAvailable
        ? { title: "AI 분석 보기", detail: "검증된 읽기 전용 분석을 확인하세요.", tab: "More" as const }
        : { title: "시장 보기", detail: "검증된 시장 데이터를 확인하세요.", tab: "Markets" as const };
  const runNextAction = () => { if (nextAction.tab === null) onGoSettings(); else onNavigate(nextAction.tab); };

  return <ScrollView contentContainerStyle={[styles.content, tablet && styles.contentTablet]} refreshControl={<RefreshControl tintColor={theme.colors.primary} refreshing={refreshing} onRefresh={onRefresh} />} testID="home-screen">
    <View style={styles.intro}><Text style={[styles.kicker, { color: theme.colors.primary }]}>NUSA / HOME</Text><Text style={[styles.title, { color: theme.colors.text }]}>오늘의 PAPER 상태</Text><Text style={[styles.subtitle, { color: theme.colors.textMuted }]}>핵심 숫자와 지금 필요한 한 가지 행동만 보여드립니다.</Text></View>
    {readOnlyError ? <InlineNotice title="PAPER 서버 연결 오류" detail={readOnlyError} tone="danger" /> : null}
    <MotionReveal testID="home-hero-reveal"><View style={[styles.hero, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]} testID="account-hero-card">
      <View style={styles.heroTopline}><View><Text style={[styles.balanceLabel, { color: theme.colors.textMuted }]}>ACCOUNT EQUITY</Text><Text style={[styles.heroState, { color: signalReady ? theme.colors.success : theme.colors.warning }]}>{snapshot ? (signalReady ? "PAPER READY" : "PAPER CHECK") : "PAPER SETUP"}</Text></View><Text style={[styles.authorityLine, { color: theme.colors.textMuted }]}>PAPER · LIVE OFF</Text></View>
      <Text style={[styles.balance, tablet && styles.balanceTablet, { color: theme.colors.text }]} adjustsFontSizeToFit numberOfLines={1}>{account ? krw(account.equity) : "-"}</Text>
      <View style={styles.heroMeta}>{totalPnl != null ? <Text style={[styles.pnl, { color: totalPnl >= 0 ? theme.colors.success : theme.colors.danger }]}>{totalPnl >= 0 ? "+" : ""}{krw(totalPnl)}</Text> : null}<Text style={[styles.metaText, { color: theme.colors.textMuted }]}>누적 손익</Text><View style={[styles.metaDot, { backgroundColor: theme.colors.borderStrong }]} /><Text style={[styles.metaText, { color: theme.colors.textMuted }]}>{snapshot?.readyForPaperOperations ? "안전 게이트 통과" : "안전 게이트 점검 필요"}</Text></View>
      <MotionReveal testID="home-signal-reveal"><View style={styles.signalWrap}><TerrainSignal variant="symbolic" signalStrength={signalReady ? 0.95 : 0.38} accessibilityLabel={`PAPER 상태 신호: ${signalReady ? "준비됨" : "점검 필요"}`} testID="home-signal-trace" /><Text style={[styles.signalCaption, { color: theme.colors.textMuted }]}>현재 상태를 읽기 전용 신호로 표시합니다.</Text></View></MotionReveal>
      <View style={styles.nextAction} testID="home-next-action"><View style={styles.nextActionCopy}><Text style={[styles.kicker, { color: theme.colors.textMuted }]}>NEXT ACTION</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>{nextAction.title}</Text><Text style={[styles.body, { color: theme.colors.textMuted }]}>{nextAction.detail}</Text></View><NusaButton label={nextAction.title} onPress={runNextAction} testID="home-next-action-button" /></View>
    </View></MotionReveal>

    {snapshot ? <View style={styles.secondaryStack}>
      <View style={styles.insight} testID="ai-card"><View style={styles.insightHeader}><View><Text style={[styles.kicker, { color: theme.colors.primary }]}>AI SIGNAL</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>핵심 관찰</Text></View><Text style={[styles.readOnlyLabel, { color: theme.colors.textMuted }]}>READ ONLY</Text></View><Text style={[styles.thesis, { color: ai?.thesis ? theme.colors.text : theme.colors.textMuted }]} numberOfLines={tablet ? 5 : 4}>{ai?.thesis ?? "현재 표시할 검증된 AI 분석이 없습니다."}</Text><View style={styles.insightFooter}><Text style={[styles.metaText, { color: theme.colors.textMuted }]}>{aiInsightAvailable ? `근거 ${ai?.evidenceReferences.length ?? 0}개 · 주문 권한 없음` : "검증된 근거 없음 · 주문 권한 없음"}</Text><NusaButton label="AI 보기" onPress={() => onNavigate("More")} tone="neutral" /></View></View>
      {allocation ? <View style={styles.allocation} testID="home-allocation-panel"><View style={styles.allocationHeader}><View><Text style={[styles.kicker, { color: theme.colors.textMuted }]}>CASH ALLOCATION</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>현금 배분</Text></View><Text style={[styles.allocationRatio, { color: theme.colors.primary }]}>{allocation.investmentPercent}%</Text></View><View style={[styles.rail, { backgroundColor: theme.colors.surfaceRaised }]}><View style={[styles.railFill, { width: allocationWidth, backgroundColor: theme.colors.primary }]} /></View><View style={styles.allocationSplit}><View style={styles.allocationCell}><Text style={[styles.valueLabel, { color: theme.colors.textMuted }]}>투자 가능</Text><Text testID="home-investable-cash" style={[styles.value, { color: theme.colors.text }]}>{krw(allocation.investableCash)}</Text></View><View style={[styles.splitDivider, { backgroundColor: theme.colors.border }]} /><View style={styles.allocationCell}><Text style={[styles.valueLabel, { color: theme.colors.textMuted }]}>보호 현금</Text><Text testID="home-reserved-cash" style={[styles.value, { color: theme.colors.text }]}>{krw(allocation.reservedCash)}</Text></View></View></View> : null}
      <View style={styles.statusSummary} testID="home-status-summary"><View style={styles.statusHeader}><View><Text style={[styles.kicker, { color: theme.colors.textMuted }]}>SYSTEM</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>안전 상태</Text></View><Text style={[styles.metaText, { color: theme.colors.textMuted }]}>{snapshot.health}</Text></View><DataRow label="PAPER 런타임" value={snapshot.operations.runtimeState} tone={healthTone(snapshot.operations.runtimeState)} /><DataRow label="안전 게이트" value={snapshot.readyForPaperOperations ? "통과" : "점검 필요"} tone={snapshot.readyForPaperOperations ? "success" : "warning"} /></View>
    </View> : <View style={styles.setupHint}><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>PAPER 연결을 시작하세요</Text><Text style={[styles.body, { color: theme.colors.textMuted }]}>{notConfigured ?? "안전한 읽기 전용 상태를 확인하면 Home 데이터가 표시됩니다."}</Text></View>}
  </ScrollView>;
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: 20, paddingTop: 22, gap: 24, paddingBottom: 48, width: "100%", maxWidth: 920, alignSelf: "center" }, contentTablet: { maxWidth: 1120, paddingHorizontal: 36, paddingTop: 28, gap: 28 },
  intro: { gap: 5 }, title: { fontSize: 32, lineHeight: 39, fontWeight: "800", letterSpacing: -1.05 }, subtitle: { fontSize: 14, lineHeight: 21, fontWeight: "500" }, kicker: { fontSize: 10, lineHeight: 15, fontWeight: "800", letterSpacing: 1.25 }, body: { fontSize: 13, lineHeight: 20 },
  hero: { minHeight: 438, paddingHorizontal: 22, paddingTop: 22, paddingBottom: 0, borderWidth: 1, borderRadius: 26, overflow: "hidden" }, heroTopline: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 14 }, balanceLabel: { fontSize: 10, lineHeight: 16, fontWeight: "800", letterSpacing: 1.55 }, heroState: { marginTop: 4, fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 0.8 }, authorityLine: { fontSize: 11, lineHeight: 17, fontWeight: "800", letterSpacing: 0.55 }, balance: { marginTop: 15, fontSize: 62, lineHeight: 70, fontWeight: "800", letterSpacing: -3.1, fontVariant: ["tabular-nums"] }, balanceTablet: { fontSize: 82, lineHeight: 90 }, heroMeta: { marginTop: 9, flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }, pnl: { fontSize: 20, lineHeight: 27, fontWeight: "800", fontVariant: ["tabular-nums"] }, metaText: { fontSize: 12, lineHeight: 18, fontWeight: "600" }, metaDot: { width: 3, height: 3, borderRadius: 2 }, signalWrap: { minHeight: 138, marginTop: 14, justifyContent: "flex-end" }, signalCaption: { marginBottom: 2, fontSize: 11, lineHeight: 17, fontWeight: "600" },
  nextAction: { marginTop: 8, paddingTop: 16, paddingBottom: 18, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.14)", flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 14, flexWrap: "wrap" }, nextActionCopy: { flexGrow: 1, flexShrink: 1, minWidth: 180, gap: 2 }, sectionTitle: { marginTop: 3, fontSize: 20, lineHeight: 26, fontWeight: "800", letterSpacing: -0.45 },
  secondaryStack: { gap: 24 }, insight: { gap: 14, paddingVertical: 2, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.14)", borderBottomColor: "rgba(255,255,255,0.14)", paddingTop: 16, paddingBottom: 18 }, insightHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }, readOnlyLabel: { fontSize: 10, lineHeight: 15, fontWeight: "800", letterSpacing: 1.1 }, thesis: { fontSize: 21, lineHeight: 31, fontWeight: "700", letterSpacing: -0.45 }, insightFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }, allocation: { gap: 13, paddingVertical: 2 }, allocationHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 }, allocationRatio: { fontSize: 20, lineHeight: 26, fontWeight: "800", fontVariant: ["tabular-nums"] }, rail: { height: 6, borderRadius: 999, overflow: "hidden" }, railFill: { height: "100%", borderRadius: 999 }, allocationSplit: { flexDirection: "row", alignItems: "stretch", gap: 16 }, allocationCell: { flex: 1 }, splitDivider: { width: StyleSheet.hairlineWidth }, valueLabel: { fontSize: 11, lineHeight: 16, fontWeight: "600" }, value: { marginTop: 4, fontSize: 20, lineHeight: 27, fontWeight: "800", letterSpacing: -0.5, fontVariant: ["tabular-nums"] }, statusSummary: { gap: 8, paddingTop: 3 }, statusHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 3 }, setupHint: { gap: 8, paddingVertical: 10 },
});
