import { RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { NusaButton, NusaCard, StatusChip } from "./components";
import { useTheme } from "./ThemeProvider";
import type { LiveReadinessObservabilitySnapshot } from "../../../packages/contracts/src/liveReadinessObservability";

export interface LiveReadinessMonitorViewProps {
  readonly snapshot: LiveReadinessObservabilitySnapshot | null;
  readonly unavailableReason?: string;
  readonly refreshing: boolean;
  readonly onRefresh: () => void | Promise<void>;
  readonly onClose?: () => void;
}

const time = (value: string | undefined): string => value == null ? "확인되지 않음" : new Date(value).toLocaleString("ko-KR");
const state = (value: boolean): string => value ? "ACTIVE" : "CLEAR";

export function LiveReadinessMonitorView({ snapshot, unavailableReason, refreshing, onRefresh, onClose }: LiveReadinessMonitorViewProps) {
  const { theme } = useTheme();
  const status = snapshot?.status ?? "UNAVAILABLE";
  const tone = status === "READY_FOR_MANUAL_ENABLE" ? "primary" : status === "HALTED" ? "danger" : "warning";
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void onRefresh(); }} />} style={[styles.screen, { backgroundColor: theme.colors.background }]} testID="live-ready-monitor">
    <View style={styles.titleRow}><View><Text style={[styles.eyebrow, { color: theme.colors.primary }]}>LIVE READY · READ ONLY</Text><Text style={[styles.title, { color: theme.colors.text }]}>LIVE 준비 상태 관측</Text><Text style={[styles.description, { color: theme.colors.textMuted }]}>LIVE 거래가 활성화된 화면이 아닙니다. 준비 상태와 차단 근거만 읽기 전용으로 표시합니다.</Text></View><StatusChip label={status} tone={tone} /></View>
    {snapshot == null ? <NusaCard testID="live-ready-unavailable"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>LIVE 준비 데이터 없음</Text><Text style={[styles.body, { color: theme.colors.textMuted }]}>{unavailableReason ?? "현재 canonical LIVE readiness source를 읽을 수 없습니다."}</Text></NusaCard> : <>
      <NusaCard testID="live-ready-overview"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>준비 상태</Text><View style={styles.grid}><Metric label="STATUS" value={snapshot.status} /><Metric label="LAST REFRESH" value={time(snapshot.lastRefresh)} /><Metric label="HEAD" value={snapshot.currentHeadSha || "UNKNOWN"} /><Metric label="ACTIVATION" value={snapshot.activationState} /><Metric label="LEASE" value={snapshot.activationLeaseState} /><Metric label="CREDENTIAL" value={snapshot.credentialReadiness} /></View><Text style={[styles.reason, { color: theme.colors.textMuted }]}>liveAuthority=NONE · productionMutationAllowed=false · AI authority=ZERO_AUTHORITY</Text></NusaCard>
      <NusaCard testID="live-ready-safety"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Safety & Readiness</Text><View style={styles.grid}><Metric label="GOVERNANCE" value={snapshot.governance} /><Metric label="TRADE PERMISSION" value={snapshot.tradePermission} /><Metric label="RISK AUTHORITY" value={snapshot.riskAuthority} /><Metric label="RECONCILIATION" value={snapshot.reconciliationTests} /><Metric label="KILL SWITCH TEST" value={snapshot.killSwitchTests} /><Metric label="CIRCUIT BREAKER" value={state(snapshot.runtimeSafety.exchangeError || snapshot.runtimeSafety.staleMarketData || snapshot.runtimeSafety.riskBudgetBreached || snapshot.runtimeSafety.reconciliationMismatch)} /><Metric label="CREDENTIAL SOURCE" value={snapshot.realAccountMonitor} /><Metric label="PROHIBITED MUTATION" value={snapshot.prohibitedFinancialMutationScan} /></View></NusaCard>
      {snapshot.blockers.length > 0 ? <NusaCard testID="live-ready-blockers"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>차단 근거</Text>{snapshot.blockers.map((blocker) => <Text key={blocker} style={[styles.body, { color: theme.colors.warning }]}>· {blocker}</Text>)}</NusaCard> : <NusaCard testID="live-ready-blockers"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>차단 근거</Text><Text style={[styles.body, { color: theme.colors.textMuted }]}>현재 canonical evaluator에서 보고된 차단 근거가 없습니다. 그래도 이 화면은 실행 권한을 부여하지 않습니다.</Text></NusaCard>}
      <NusaCard testID="live-ready-freshness"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Evidence Freshness</Text>{Object.entries(snapshot.freshness).sort(([left], [right]) => left.localeCompare(right)).map(([source, freshness]) => <View key={source} style={[styles.row, { borderBottomColor: theme.colors.border }]}><Text style={[styles.rowLabel, { color: theme.colors.text }]}>{source}</Text><Text style={[styles.rowValue, { color: freshness === "FRESH" ? theme.colors.primary : theme.colors.warning }]}>{freshness}</Text></View>)}<Text style={[styles.reason, { color: theme.colors.textMuted }]}>source version: {snapshot.provenance.sourceVersion} · fingerprint: {snapshot.provenance.sourceFingerprint.slice(0, 16)}…</Text></NusaCard>
      <NusaCard testID="live-ready-incidents"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Incidents</Text>{snapshot.incidents.length === 0 ? <Text style={[styles.body, { color: theme.colors.textMuted }]}>현재 readiness incident 없음</Text> : snapshot.incidents.map((incident) => <View key={incident.code} style={[styles.row, { borderBottomColor: theme.colors.border }]}><View style={styles.rowMain}><Text style={[styles.rowLabel, { color: incident.severity === "CRITICAL" ? theme.colors.danger : theme.colors.warning }]}>{incident.code}</Text><Text style={[styles.rowMeta, { color: theme.colors.textMuted }]}>{incident.severity} · {time(incident.observedAt)}</Text></View></View>)}</NusaCard>
      <NusaCard testID="live-ready-timeline"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Readiness Timeline</Text>{snapshot.timeline.length === 0 ? <Text style={[styles.body, { color: theme.colors.textMuted }]}>기록된 canonical LIVE mock/rehearsal lifecycle이 없습니다.</Text> : snapshot.timeline.map((entry) => <View key={`${entry.sourceId}-${entry.observedAt ?? "unknown"}`} style={[styles.row, { borderBottomColor: theme.colors.border }]}><Text style={[styles.rowLabel, { color: theme.colors.text }]}>{entry.sourceId}</Text><Text style={[styles.rowMeta, { color: theme.colors.textMuted }]}>{entry.freshness} · {time(entry.observedAt)}</Text></View>)}</NusaCard>
      <NusaCard testID="live-ready-authority"><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>Authority</Text><Text style={[styles.reason, { color: theme.colors.textMuted }]}>관측 전용: 주문·취소·출금·이체·LIVE 활성화·lease 생성 기능이 없습니다.</Text><View style={styles.grid}><Metric label="KILL SWITCH" value={state(snapshot.runtimeSafety.killSwitchActive)} /><Metric label="STALE MARKET" value={state(snapshot.runtimeSafety.staleMarketData)} /><Metric label="BALANCE DRIFT" value={state(snapshot.runtimeSafety.abnormalBalanceDrift)} /><Metric label="STRATEGY" value={state(snapshot.runtimeSafety.strategyInvalidated)} /></View></NusaCard>
    </>}
    {onClose ? <NusaButton label="닫기" onPress={onClose} /> : null}
  </ScrollView>;
}

function Metric({ label, value }: Readonly<{ label: string; value: string }>) { const { theme } = useTheme(); return <View style={styles.metric}><Text style={[styles.metricLabel, { color: theme.colors.textMuted }]}>{label}</Text><Text style={[styles.metricValue, { color: theme.colors.text }]}>{value}</Text></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 20, gap: 14, paddingBottom: 36 }, titleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 14 }, eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 26, fontWeight: "800", marginTop: 4 }, description: { fontSize: 13, lineHeight: 19, marginTop: 6, maxWidth: 620 }, sectionTitle: { fontSize: 16, fontWeight: "800", marginBottom: 10 }, body: { fontSize: 13, lineHeight: 20 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, metric: { minWidth: "30%", flexGrow: 1 }, metricLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 1 }, metricValue: { fontSize: 14, fontWeight: "700", marginTop: 4 }, reason: { fontSize: 12, lineHeight: 18, marginTop: 12 }, row: { paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", gap: 8 }, rowMain: { flex: 1, gap: 4 }, rowLabel: { fontSize: 12, fontWeight: "700", flexShrink: 1 }, rowMeta: { fontSize: 11 }, rowValue: { fontSize: 11, fontWeight: "700" },
});
