import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { NusaButton, StatusChip } from "./components";
import { useTheme } from "./ThemeProvider";

export type OwnerConnectionStage = "CONNECT" | "VERIFY_OWNER" | "VERIFY_DEVICE" | "SECURE_SESSION" | "COMPLETE" | "BLOCKED";
export interface OwnerConnectionExperienceProps { readonly stage: OwnerConnectionStage; readonly deviceCredentialAvailable: boolean; readonly busy?: boolean; readonly detail?: string; readonly onAuthenticateOwner: () => void; readonly onRecoverWithPairing: () => void; }
const STEPS = Object.freeze([["CONNECT", "PAPER 서버 확인", "공개 상태 · 인증 불필요"],["VERIFY_OWNER", "최초 기기 승인", "소유자 확인"],["VERIFY_DEVICE", "이 휴대폰 등록", "서버 검증 자격 증명"],["SECURE_SESSION", "자동 연결 준비", "기기 세션 · 토큰 재입력 없음"]]);

export function OwnerConnectionExperience({ stage, deviceCredentialAvailable, busy = false, detail, onAuthenticateOwner, onRecoverWithPairing }: OwnerConnectionExperienceProps) {
 const { theme } = useTheme(); const complete = stage === "COMPLETE"; const blocked = stage === "BLOCKED"; const activeIndex = Math.max(0, STEPS.findIndex(([candidate]) => candidate === stage));
 return <View style={[styles.shell,{backgroundColor:theme.colors.surface,borderColor:theme.colors.borderStrong}]} testID="owner-connection-experience">
  <View style={[styles.topRail,{borderBottomColor:theme.colors.border}]}><Text style={[styles.railLabel,{color:theme.colors.textMuted}]}>PAPER SERVER</Text><Text style={[styles.railTruth,{color:complete?theme.colors.success:blocked?theme.colors.danger:theme.colors.text}]}>{complete?"AUTO CONNECT":"DEVICE TRUST"}</Text><Text style={[styles.railLabel,{color:theme.colors.textMuted}]}>LIVE SEPARATE</Text></View>
  <View style={styles.hero}><View style={styles.heroCopy}><Text style={[styles.eyebrow,{color:theme.colors.textMuted}]}>NUSA · PAPER CONNECTION</Text><Text style={[styles.title,{color:theme.colors.text}]}>{complete?"PAPER 자동 연결":"이 휴대폰을 한 번만 승인"}</Text><Text style={[styles.subtitle,{color:theme.colors.textMuted}]}>{complete?"승인된 기기 세션을 안전하게 복원·갱신합니다. 토큰을 다시 입력할 필요가 없습니다.":"공개 시세와 서버 상태는 바로 볼 수 있습니다. PAPER 데이터를 변경하려면 최초 1회 기기 승인이 필요합니다."}</Text></View><StatusChip label={complete?"CONNECTED":blocked?"BLOCKED":"PAPER ONLY"} tone={complete?"success":blocked?"danger":"neutral"}/></View>
  <View style={[styles.accessGrid,{borderColor:theme.colors.border}]} testID="paper-access-boundary"><AccessRow title="공개 관측" detail="시세 · 서버 상태" state="인증 없음"/><AccessRow title="PAPER 변경" detail="주문 · 포지션 · 설정" state="기기 세션"/><AccessRow title="Upbit LIVE" detail="별도 사용자 인증 · 권한 검증" state="분리"/></View>
  {complete?<View style={[styles.success,{backgroundColor:theme.colors.surfaceSunken,borderColor:theme.colors.success}]} testID="owner-connection-success"><View style={styles.successCopy}><Text style={[styles.successTitle,{color:theme.colors.text}]}>✓ 이 휴대폰이 안전하게 연결되었습니다.</Text><Text style={[styles.body,{color:theme.colors.textMuted}]}>다음 실행부터 승인된 PAPER 기기 세션을 자동으로 복원합니다. 세션이 폐기되거나 기기가 달라지면 다시 승인하기 전까지 변경 작업은 차단됩니다.</Text></View></View>:<>
   <View style={styles.timeline} accessibilityLabel="PAPER 기기 연결 진행 단계">{STEPS.map(([key,label,caption],index)=>{const passed=activeIndex>index;const active=key===stage;return <View key={key} style={[styles.step,{borderTopColor:theme.colors.border}]}><View style={[styles.stepDot,{borderColor:passed||active?theme.colors.primary:theme.colors.borderStrong,backgroundColor:passed?theme.colors.primary:"transparent"}]}><Text style={[styles.stepIndex,{color:passed?theme.colors.background:active?theme.colors.primary:theme.colors.textMuted}]}>{passed?"✓":`0${index+1}`}</Text></View><View style={styles.stepCopy}><Text style={[styles.stepLabel,{color:active?theme.colors.text:theme.colors.textMuted}]}>{label}</Text><Text style={[styles.stepCaption,{color:theme.colors.textMuted}]}>{caption}</Text></View><Text style={[styles.stepState,{color:passed?theme.colors.success:active?theme.colors.primary:theme.colors.textMuted}]}>{passed?"DONE":active?"NOW":"NEXT"}</Text></View>})}</View>
   <View style={[styles.truthPanel,{backgroundColor:theme.colors.surfaceSunken,borderColor:blocked?theme.colors.danger:theme.colors.border}]}><Text style={[styles.truthKicker,{color:blocked?theme.colors.danger:theme.colors.textMuted}]}>{blocked?"PAPER 변경 차단":"최초 연결만 확인합니다"}</Text><Text style={[styles.body,{color:theme.colors.text}]}>{detail??(deviceCredentialAvailable?"서버 요청에 이 휴대폰의 보호된 키로 서명합니다. 승인 후에는 기기 세션이 자동 재연결되며 생체정보 자체는 서버로 전송되지 않습니다.":"서버가 소유자 신원과 이 휴대폰을 검증해야 PAPER 변경 권한이 있는 기기 세션을 발급합니다. 공개 관측은 계속 사용할 수 있습니다.")}</Text></View>
   {deviceCredentialAvailable?<NusaButton disabled={busy} label={busy?"기기 확인 중…":"이 휴대폰 승인"} onPress={onAuthenticateOwner} testID="owner-authenticate-primary"/>:null}
   <View style={[styles.recovery,{borderTopColor:theme.colors.border}]}><View style={styles.recoveryCopy}><Text style={[styles.recoveryTitle,{color:theme.colors.text}]}>복구 연결</Text><Text style={[styles.recoveryDetail,{color:theme.colors.textMuted}]}>기존 승인 기기를 사용할 수 없거나 세션을 복구해야 할 때만 6자리 확인 코드를 사용합니다.</Text></View><NusaButton disabled={busy} label="6자리 코드" onPress={onRecoverWithPairing} tone="neutral" testID="owner-pairing-recovery"/></View>
  </>}
  <View style={[styles.authorityRail,{borderTopColor:theme.colors.border}]}><Text style={[styles.authorityStrong,{color:theme.colors.text}]}>PAPER ONLY</Text><Text style={[styles.authority,{color:theme.colors.textMuted}]}>DEVICE SESSION · LIVE AUTH SEPARATE · AI ZERO AUTHORITY</Text></View>
 </View>;
}
function AccessRow({title,detail,state}:Readonly<{title:string;detail:string;state:string}>){const{theme}=useTheme();return <View style={[styles.accessRow,{borderTopColor:theme.colors.border}]}><View style={styles.accessCopy}><Text style={[styles.accessTitle,{color:theme.colors.text}]}>{title}</Text><Text style={[styles.accessDetail,{color:theme.colors.textMuted}]}>{detail}</Text></View><Text style={[styles.accessState,{color:theme.colors.textMuted}]}>{state}</Text></View>}
const styles=StyleSheet.create({shell:{borderWidth:1,borderRadius:22,overflow:"hidden"},topRail:{minHeight:38,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16,gap:8},railLabel:{fontSize:9,lineHeight:13,fontWeight:"800",letterSpacing:.9},railTruth:{fontSize:9,lineHeight:13,fontWeight:"900",letterSpacing:.7},hero:{padding:18,paddingBottom:14,flexDirection:"row",alignItems:"flex-start",gap:12},heroCopy:{flex:1,minWidth:0},eyebrow:{fontSize:10,lineHeight:14,fontWeight:"800",letterSpacing:1.2},title:{marginTop:7,fontSize:24,lineHeight:30,fontWeight:"800",letterSpacing:-.7},subtitle:{marginTop:8,fontSize:12,lineHeight:19},accessGrid:{marginHorizontal:18,borderWidth:StyleSheet.hairlineWidth,borderRadius:14,overflow:"hidden"},accessRow:{minHeight:50,paddingHorizontal:13,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",gap:10},accessCopy:{flex:1},accessTitle:{fontSize:12,lineHeight:17,fontWeight:"800"},accessDetail:{fontSize:10,lineHeight:15},accessState:{fontSize:9,lineHeight:13,fontWeight:"900",letterSpacing:.5},timeline:{paddingHorizontal:18,marginTop:16},step:{minHeight:58,borderTopWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",gap:12},stepDot:{width:31,height:31,borderRadius:16,borderWidth:1,alignItems:"center",justifyContent:"center"},stepIndex:{fontSize:10,fontWeight:"900",fontVariant:["tabular-nums"]},stepCopy:{flex:1,gap:2},stepLabel:{fontSize:14,lineHeight:19,fontWeight:"800"},stepCaption:{fontSize:10,lineHeight:15},stepState:{fontSize:9,lineHeight:13,fontWeight:"900",letterSpacing:.8},truthPanel:{marginHorizontal:18,marginTop:16,padding:14,borderWidth:StyleSheet.hairlineWidth,borderRadius:14},truthKicker:{marginBottom:7,fontSize:9,lineHeight:13,fontWeight:"900",letterSpacing:1},body:{fontSize:12,lineHeight:19},recovery:{margin:18,marginBottom:4,paddingTop:16,borderTopWidth:StyleSheet.hairlineWidth,gap:12},recoveryCopy:{gap:4},recoveryTitle:{fontSize:12,lineHeight:17,fontWeight:"800"},recoveryDetail:{fontSize:11,lineHeight:17},success:{margin:18,padding:16,borderWidth:1,borderRadius:16,flexDirection:"row",gap:13,alignItems:"flex-start"},successMark:{fontSize:21,lineHeight:25,fontWeight:"900"},successCopy:{flex:1},successTitle:{fontSize:15,lineHeight:21,fontWeight:"800",marginBottom:5},authorityRail:{marginTop:14,minHeight:43,borderTopWidth:StyleSheet.hairlineWidth,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},authorityStrong:{fontSize:9,lineHeight:13,fontWeight:"900",letterSpacing:.8},authority:{flex:1,textAlign:"right",fontSize:8,lineHeight:12,fontWeight:"700",letterSpacing:.25}});