import React, { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { DataRow, NusaButton, NusaCard, NusaTextField, StatusChip } from "./components";
import { InlineNotice, ScreenHeader, SegmentedControl } from "./uxPrimitives";
import { useTheme, type ThemePreference } from "./ThemeProvider";
import { DEFAULT_SETTINGS, normalizeInvestmentPercent, normalizeSettings, type AppSettings, type SettingsRepository, type ThemeSetting } from "./settings";
import { createCashInvestmentEnvelope } from "./capitalAllocationGuard";
import { resetUpbitReadOnlyState } from "./upbitReadOnlyAccount";

interface SettingsViewProps { readonly repository: SettingsRepository; readonly onSignOut?: () => void; readonly exchangeCash?: number; readonly onCloudInvestmentPercentSave?: (investmentPercent: number) => Promise<void>; readonly onInvestmentPercentChanged?: (investmentPercent: number) => void; }
const themeItems = Object.freeze([{ key: "SYSTEM", label: "시스템" }, { key: "LIGHT", label: "라이트" }, { key: "DARK", label: "다크" }]);
const allocationPresets = Object.freeze([{ key: "25", label: "25%" }, { key: "50", label: "50%" }, { key: "75", label: "75%" }, { key: "100", label: "100%" }]);
const themePreference = (value: ThemeSetting): ThemePreference => value === "SYSTEM" ? "system" : value === "LIGHT" ? "light" : "dark";
const money = (value: number): string => `₩${Math.round(value).toLocaleString("ko-KR")}`;

/** Production settings intentionally contains no endpoint, port, tunnel, or bearer input. */
export function SettingsView({ repository, onSignOut, exchangeCash = 0, onCloudInvestmentPercentSave, onInvestmentPercentChanged }: SettingsViewProps) {
  const { theme, setMode } = useTheme();
  const [settings, setSettings] = useState<AppSettings | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [investmentPercentDraft, setInvestmentPercentDraft] = useState(String(DEFAULT_SETTINGS.capitalAllocation.investmentPercent));
  useEffect(() => { let active = true; void repository.load().then((loaded) => { if (!active) return; const next = normalizeSettings(loaded ?? DEFAULT_SETTINGS); setSettings(next); setInvestmentPercentDraft(String(next.capitalAllocation.investmentPercent)); setMode(themePreference(next.theme)); onInvestmentPercentChanged?.(next.capitalAllocation.investmentPercent); }).catch((loadError) => { if (active) setError(loadError instanceof Error ? loadError.message : "Settings are unavailable."); }); return () => { active = false; }; }, [onInvestmentPercentChanged, repository, setMode]);
  const persist = async (next: AppSettings): Promise<boolean> => { if (saving) return false; setSaving(true); try { const normalized = normalizeSettings(next); const allocationChanged = normalized.capitalAllocation.investmentPercent !== settings?.capitalAllocation.investmentPercent; if (allocationChanged && onCloudInvestmentPercentSave) await onCloudInvestmentPercentSave(normalized.capitalAllocation.investmentPercent); await repository.save(normalized); setSettings(normalized); setInvestmentPercentDraft(String(normalized.capitalAllocation.investmentPercent)); setError(null); if (allocationChanged) onInvestmentPercentChanged?.(normalized.capitalAllocation.investmentPercent); return true; } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Settings could not be saved."); return false; } finally { setSaving(false); } };
  const updateTheme = (next: ThemeSetting) => { if (!settings || saving) return; const previous = settings.theme; setMode(themePreference(next)); void persist({ ...settings, theme: next }).then((saved) => { if (!saved) setMode(themePreference(previous)); }); };
  const saveInvestmentPercent = async (raw = investmentPercentDraft) => { if (!settings || saving) return; try { const value = normalizeInvestmentPercent(Number(raw)); setInvestmentPercentDraft(String(value)); await persist({ ...settings, capitalAllocation: { investmentPercent: value } }); } catch (allocationError) { setError(allocationError instanceof Error ? allocationError.message : "Investment allocation is invalid."); } };
  const resetSettings = () => { if (!settings || saving) return; const previous = settings.theme; resetUpbitReadOnlyState(); setMode("system"); void persist(DEFAULT_SETTINGS).then((saved) => { if (!saved) setMode(themePreference(previous)); }); };
  if (error && settings === null) return <View style={styles.state} testID="settings-error"><InlineNotice title="설정을 불러올 수 없습니다" detail={error} tone="danger" /></View>;
  if (settings === null) return <View style={styles.state} testID="settings-loading"><ActivityIndicator color={theme.colors.primary} /><Text style={[styles.title, { color: theme.colors.text }]}>설정을 불러오는 중</Text></View>;
  const allocation = createCashInvestmentEnvelope(exchangeCash, settings.capitalAllocation.investmentPercent); const selectedPreset = allocationPresets.some((item) => item.key === String(settings.capitalAllocation.investmentPercent)) ? String(settings.capitalAllocation.investmentPercent) : ""; const allocationWidth = `${allocation.investmentPercent}%` as `${number}%`;
  return <ScrollView contentContainerStyle={styles.content} testID="settings-screen">
    <StatusChip label="PAPER ONLY" tone="primary" />
    <ScreenHeader eyebrow="APPLICATION" title="설정" description="NUSA Cloud 연결 상태, 투자 비중, 화면과 로컬 상태를 관리합니다." statusLabel="자동 연결" statusTone="info" />
    {error ? <InlineNotice title="설정 저장 오류" detail={error} tone="danger" /> : null}
    <View style={styles.sectionBlock} testID="settings-cloud-connection"><View style={styles.sectionHeader}><View><Text style={[styles.eyebrow, { color: theme.colors.textMuted }]}>01 · NUSA CLOUD</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>자동 연결</Text></View><StatusChip label="자동 확인" tone="info" /></View><InlineNotice title="서버 위치는 앱이 관리합니다" detail="NUSA Cloud 연결이 끊기면 다시 시도할 수 있습니다. endpoint, port, tunnel, 운영자 토큰은 일반 설정에 노출하지 않습니다." tone="info" testID="settings-cloud-summary" /><DataRow label="PAPER / Market / AI" value="NUSA Cloud 경유" /><DataRow label="Upbit Read-only" value="서버에서 관리" /></View>
    <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />
    <View style={styles.sectionBlock} testID="settings-capital-allocation"><View style={styles.sectionHeader}><View><Text style={[styles.eyebrow, { color: theme.colors.textMuted }]}>02 · CASH ALLOCATION</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>현금 투자 비중</Text></View><Text style={[styles.allocationPercent, { color: theme.colors.primary }]}>{allocation.investmentPercent}%</Text></View><Text style={[styles.hint, { color: theme.colors.textMuted }]}>거래소 PAPER 현금 중 신규 매수에 사용할 최대 비중입니다. 나머지는 보호 현금으로 남깁니다.</Text><View style={[styles.allocationTrack, { backgroundColor: theme.colors.border }]}><View style={[styles.allocationFill, { width: allocationWidth, backgroundColor: theme.colors.primary }]} /></View><View style={styles.allocationAmounts}><View><Text style={[styles.amountLabel, { color: theme.colors.textMuted }]}>실제 투자 가능 금액</Text><Text style={[styles.amountValue, { color: theme.colors.text }]}>{money(allocation.investableCash)}</Text></View><View style={styles.amountRight}><Text style={[styles.amountLabel, { color: theme.colors.textMuted }]}>보호되는 현금 금액</Text><Text style={[styles.amountValue, { color: theme.colors.text }]}>{money(allocation.reservedCash)}</Text></View></View><SegmentedControl disabled={saving} items={allocationPresets} selectedKey={selectedPreset} onChange={(key) => { setInvestmentPercentDraft(key); void saveInvestmentPercent(key); }} testID="settings-investment-allocation-presets" /><NusaTextField autoCorrect={false} editable={!saving} keyboardType="decimal-pad" label="직접 입력 (%)" value={investmentPercentDraft} onChangeText={setInvestmentPercentDraft} placeholder="0 - 100" returnKeyType="done" testID="settings-investment-percent" /><NusaButton disabled={saving} label={saving ? "저장 중..." : "투자 비중 저장"} onPress={() => void saveInvestmentPercent()} testID="settings-investment-percent-save" /></View>
    <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />
    <View style={styles.sectionBlock} testID="settings-theme"><Text style={[styles.eyebrow, { color: theme.colors.textMuted }]}>03 · APPEARANCE</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>화면 테마</Text><SegmentedControl disabled={saving} items={themeItems} selectedKey={settings.theme} onChange={(key) => updateTheme(key as ThemeSetting)} testID="settings-theme-segmented-control" /></View>
    <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />
    <View style={styles.sectionBlock} testID="settings-mode"><View style={styles.sectionHeader}><View><Text style={[styles.eyebrow, { color: theme.colors.textMuted }]}>04 · SAFETY & ABOUT</Text><Text style={[styles.sectionTitle, { color: theme.colors.text }]}>안전과 앱 정보</Text></View><StatusChip label="READ ONLY" tone="info" /></View><NusaCard><DataRow label="운영 모드" value="PAPER" emphasis /><DataRow label="LIVE 주문" value="금지" tone="success" /><DataRow label="Production mutation" value="금지" tone="success" /><DataRow label="AI authority" value="ZERO" tone="success" /></NusaCard><NusaCard testID="settings-about"><DataRow label="클라이언트" value="NUSA Mobile" /><DataRow label="용도" value="PAPER / Read Only" /></NusaCard><View style={styles.row} testID="settings-reset"><NusaButton label={saving ? "작업 중..." : "로컬 설정 초기화"} disabled={saving} onPress={resetSettings} tone="danger" /></View>{onSignOut ? <View testID="settings-session"><NusaButton disabled={saving} label="개인 모드 종료" onPress={onSignOut} tone="neutral" testID="settings-sign-out" /></View> : null}</View>
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 20, gap: 18, paddingBottom: 40, width: "100%", maxWidth: 820, alignSelf: "center" }, state: { flex: 1, justifyContent: "center", padding: 20, gap: 14 }, title: { fontSize: 18, fontWeight: "700" }, sectionBlock: { gap: 12 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }, eyebrow: { fontSize: 10, lineHeight: 15, fontWeight: "800", letterSpacing: 1.1 }, sectionTitle: { marginTop: 4, fontSize: 21, lineHeight: 27, fontWeight: "800", letterSpacing: -0.5 }, hint: { fontSize: 13, lineHeight: 20 }, row: { flexDirection: "row", gap: 10, flexWrap: "wrap" }, divider: { height: StyleSheet.hairlineWidth }, allocationPercent: { fontSize: 22, lineHeight: 28, fontWeight: "800", fontVariant: ["tabular-nums"] }, allocationTrack: { height: 8, borderRadius: 999, overflow: "hidden" }, allocationFill: { height: "100%", borderRadius: 999 }, allocationAmounts: { flexDirection: "row", justifyContent: "space-between", gap: 18 }, amountRight: { alignItems: "flex-end" }, amountLabel: { fontSize: 11, lineHeight: 16, fontWeight: "700" }, amountValue: { marginTop: 3, fontSize: 18, lineHeight: 24, fontWeight: "800", fontVariant: ["tabular-nums"] } });
