import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { evaluateCredentialBoundary, CredentialBoundaryDecision } from "../src/credential-boundary";
import { attestProductionAdapterAbsence, ProductionAdapterAttestationDecision } from "../src/production-adapter-attestation";
import { SqliteDeploymentAttemptEvidenceRepository } from "../src/deployment-attempt-evidence";

test("synthetic credential boundary passes without granting mutation",()=>{const r=evaluateCredentialBoundary({environment:"synthetic",endpoint:"http://localhost/synthetic",apiKeyPresent:false,apiSecretPresent:false,accountIdentifier:"synthetic-test"});assert.equal(r.decision,CredentialBoundaryDecision.ALLOW_SYNTHETIC);assert.equal(r.productionMutationAllowed,false);});
test("production indicators are blocked",()=>{const r=evaluateCredentialBoundary({environment:"production",endpoint:"https://api.exchange.example",apiKeyPresent:true,apiSecretPresent:true,accountIdentifier:"live-main"});assert.equal(r.decision,CredentialBoundaryDecision.BLOCK);assert.deepEqual(r.blockers,["LIVE_ACCOUNT_IDENTIFIER_DETECTED","PRODUCTION_CREDENTIAL_DETECTED","PRODUCTION_ENDPOINT_DETECTED","PRODUCTION_ENVIRONMENT_DETECTED"]);});
test("adapter absence attests conservatively",()=>{const ok=attestProductionAdapterAbsence({attestationId:"a1",inventory:{productionExchangeAdapter:false,liveTradingExecutor:false,realOrderSubmitter:false,capitalMovementAdapter:false},nowMs:1});assert.equal(ok.decision,ProductionAdapterAttestationDecision.ATTESTED);assert.equal(ok.productionMutationAllowed,false);const bad=attestProductionAdapterAbsence({attestationId:"a2",inventory:{productionExchangeAdapter:true,liveTradingExecutor:false,realOrderSubmitter:true,capitalMovementAdapter:false},nowMs:2});assert.equal(bad.decision,ProductionAdapterAttestationDecision.FAILED);assert.deepEqual(bad.blockers,["PRODUCTION_EXCHANGE_ADAPTER_PRESENT","REAL_ORDER_SUBMITTER_PRESENT"]);});
test("deployment attempt evidence is append only",()=>{const db=new DatabaseSync(":memory:");const repo=new SqliteDeploymentAttemptEvidenceRepository(db);const e={attemptId:"d1",candidateId:"rc1",requestedBy:"operator",blockers:["DEPLOYMENT_HARD_BLOCK_ACTIVE"],attemptedAtMs:3,deploymentAllowed:false as const,productionMutationAllowed:false as const};assert.equal(repo.append(e).deploymentAllowed,false);assert.throws(()=>repo.append(e));db.close();});
