const test = require("node:test");
const assert = require("node:assert/strict");
const { AiDataPipeline, verifyAiDatasetExport, replayAiDataset } = require("../dist/apps/mobile/src/aiDataPipeline.js");

test("collects typed Paper events and exports deterministic feature vectors", () => { const pipeline = new AiDataPipeline(); pipeline.recordTradeEvent(1, { symbol: "KRW-BTC", netPnl: 10, orderId: "private-order", accountId: "private-account" }); pipeline.recordPortfolioSnapshot(2, { equity: 100, cash: 90 }); pipeline.recordMarketSnapshot(3, { symbol: "KRW-BTC", price: 10 }); const exported = pipeline.export(); assert.equal(exported.events.length, 3); assert.deepEqual(exported.featureVectors[0].values, [10]); assert.equal(exported.datasetVersion, "paper-ai-v1"); assert.equal(verifyAiDatasetExport(exported), true); });
test("removes identifiers and credentials before export", () => { const pipeline = new AiDataPipeline("v2"); pipeline.recordRiskEvent(10, { accountId: "a", userEmail: "x@y.test", apiKey: "secret", reason: "DAILY_LOSS", score: 80 }); const event = pipeline.export().events[0]; assert.deepEqual(Object.keys(event.payload), ["reason", "score"]); assert.equal(JSON.stringify(pipeline.export()).includes("secret"), false); });
test("detects tampered dataset integrity and preserves snapshots", () => { const pipeline = new AiDataPipeline(); const event = pipeline.recordAnalytics(5, { winRate: 0.5, profitFactor: 2 }); assert.equal(Object.isFrozen(event), true); const exported = pipeline.export(); assert.equal(verifyAiDatasetExport({ ...exported, checksum: "bad" }), false); assert.throws(() => pipeline.record("UNKNOWN", 1, {}), /unsupported/); });
test("rejects invalid version and timestamp instead of guessing", () => { assert.throws(() => new AiDataPipeline(""), /datasetVersion/); const pipeline = new AiDataPipeline(); assert.throws(() => pipeline.recordTradeEvent(-1, {}), /timestamp/); });
test("replays an intact dataset deterministically and rejects tampering", () => { const pipeline = new AiDataPipeline(); pipeline.recordTradeEvent(1, { netPnl: 2 }); pipeline.recordRiskEvent(2, { score: 10 }); const dataset = pipeline.export(); const replay = replayAiDataset(dataset); assert.deepEqual(replay.countsByType, { TRADE: 1, PORTFOLIO_SNAPSHOT: 0, MARKET_SNAPSHOT: 0, ANALYTICS: 0, STRATEGY: 0, RISK: 1 }); assert.deepEqual(replay, replayAiDataset(dataset)); assert.throws(() => replayAiDataset({ ...dataset, checksum: "bad" }), /integrity/); });
