const test = require("node:test");
const assert = require("node:assert/strict");
const { SqliteDatabase, SqliteCandidatePromotionRepository } = require("../dist/packages/storage/src/index.js");
const { InMemoryResearchEvaluationLedger } = require("../dist/apps/cloud/src/researchRuntimeCoordinator.js");
const { CandidatePromotionRuntime } = require("../dist/apps/cloud/src/candidatePromotionRuntime.js");
const { canonicalResearchJson } = require("../dist/packages/contracts/src/researchRuntime.js");
const crypto = require("node:crypto");
const { mkdtempSync } = require("node:fs");
const { join } = require("node:path");
const { tmpdir } = require("node:os");

const digest = (value) => crypto.createHash("sha256").update(canonicalResearchJson(value)).digest("hex");
const now = 1_800_000_000_000;
const identity = (overrides = {}) => ({ candidateId: "candidate-1", strategyId: "strategy-1", strategyVersion: "1.0.0", artifactHash: "a".repeat(64), configHash: "b".repeat(64), createdAt: now - 1000, originatingEvaluationId: "evaluation-1", originatingInputHash: "c".repeat(64), authority: "PAPER_ONLY", paperOnly: true, ...overrides });
const evidence = (overrides = {}) => ({ schemaVersion: 1, researchRunId: "run-1", evaluationId: "evaluation-1", strategyId: "strategy-1", strategyVersion: "1.0.0", marketDataTimestamp: now - 2000, evaluationTimestamp: now - 1000, canonicalInputHash: "c".repeat(64), modelVersion: "model-1", fillModelVersion: "fill-1", feeModelVersion: "fee-1", slippageModelVersion: "slip-1", costEvidence: { schemaVersion: 1, evaluationId: "evaluation-1", datasetId: "dataset-1", datasetContentSha256: "a".repeat(64), feeRate: 0.001, spreadRate: 0.0005, slippageRate: 0.0005, turnoverRate: 2, grossReturn: 2.004, netReturn: 2, costModelVersion: "cost-v1", observedAt: now - 2000 }, champion: { strategyId: "strategy-1", strategyVersion: "0.9.0", authority: "PAPER_ONLY", evaluatorVersion: "champion-1", canonicalInputHash: "c".repeat(64), metrics: { netReturn: 1, costAdjustedReturn: 1 }, signal: "HOLD" }, challenger: { strategyId: "strategy-1", strategyVersion: "1.0.0", authority: "ZERO_AUTHORITY", evaluatorVersion: "challenger-1", canonicalInputHash: "c".repeat(64), metrics: { netReturn: 2, costAdjustedReturn: 2 }, signal: "HOLD" }, result: "CHALLENGER_BETTER", reason: "NET_RETURN_COMPARISON", productionMutationAllowed: false, promotionAllowed: false, ...overrides });
const ownerAuthorization = { authorize(command) { return command.ownerActorRef === "owner-1" ? { actorRef: "owner-1", authenticated: true } : null; } };
const setup = () => { const db = new SqliteDatabase(); const repository = new SqliteCandidatePromotionRepository(db); const ledger = new InMemoryResearchEvaluationLedger(); const runtime = new CandidatePromotionRuntime({ repository, evaluationLedger: ledger, ownerAuthorization, now: () => now }); return { db, repository, ledger, runtime }; };

test("candidate registration is persistent and conflicting identity hashes are rejected", () => { const { db, repository, runtime } = setup(); try { runtime.registerCandidate(identity()); assert.equal(repository.getCandidate("candidate-1").lifecycle, "PAPER_CANDIDATE"); assert.throws(() => runtime.registerCandidate(identity({ artifactHash: "d".repeat(64) })), /conflict/); } finally { db.close(); } });
test("illegal lifecycle transitions and direct Champion writes fail closed", () => { const { db, repository, runtime } = setup(); try { runtime.registerCandidate(identity()); assert.throws(() => runtime.transitionCandidate("candidate-1", "CHAMPION"), /boundary/); assert.throws(() => repository.saveCandidate({ identity: identity(), lifecycle: "CHAMPION" }), /atomic promotion boundary/); assert.throws(() => repository.saveCandidate({ identity: identity(), lifecycle: "CHALLENGER" }), /atomic promotion boundary/); runtime.transitionCandidate("candidate-1", "PROMOTION_PENDING"); assert.throws(() => runtime.transitionCandidate("candidate-1", "CHAMPION"), /boundary/); } finally { db.close(); } });
test("a string owner allow-list alone never authorizes promotion", () => { const db = new SqliteDatabase(); const repository = new SqliteCandidatePromotionRepository(db); const ledger = new InMemoryResearchEvaluationLedger(); const runtime = new CandidatePromotionRuntime({ repository, evaluationLedger: ledger, ownerActorRefs: ["owner-1"], now: () => now }); try { runtime.registerCandidate(identity()); const record = evidence(); ledger.append(record); const command = { promotionCommandId: "promotion-legacy-owner-list", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(record), ownerActorRef: "owner-1", reason: "review", requestedAt: now }; assert.equal(runtime.promote(command).reason, "OWNER_AUTHORIZATION_REQUIRED"); assert.equal(runtime.currentChampion(), null); } finally { db.close(); } });
test("challenger-better is eligibility evidence only until authenticated owner promotion", () => { const { db, ledger, runtime } = setup(); try { runtime.registerCandidate(identity()); const record = evidence(); ledger.append(record); assert.equal(runtime.evaluatePromotionEligibility("candidate-1", "evaluation-1").eligible, true); const command = { promotionCommandId: "promotion-1", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(record), ownerActorRef: "not-owner", reason: "review", requestedAt: now }; assert.equal(runtime.promote(command).status, "REJECTED"); assert.equal(runtime.promote(command).status, "DUPLICATE"); assert.equal(runtime.currentChampion(), null); } finally { db.close(); } });
test("valid authenticated owner promotion is PAPER_ONLY and persists across restart", () => { const { db, ledger, runtime } = setup(); ledger.append(evidence()); runtime.registerCandidate(identity()); const command = { promotionCommandId: "promotion-1", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(evidence()), ownerActorRef: "owner-1", reason: "owner review", requestedAt: now }; try { assert.equal(runtime.promote(command).status, "PROMOTED"); assert.equal(runtime.currentChampion().lifecycle, "CHAMPION"); assert.equal(runtime.currentChampion().identity.authority, "PAPER_ONLY"); assert.equal(runtime.promote(command).status, "DUPLICATE"); } finally { db.close(); } });
test("restart restores candidate lifecycle, champion pointer, idempotency, and audit chain", () => { const filename = join(mkdtempSync(join(tmpdir(), "nusa-promotion-")), "research.db"); const db = new SqliteDatabase(filename); const repository = new SqliteCandidatePromotionRepository(db); const ledger = new InMemoryResearchEvaluationLedger(); const runtime = new CandidatePromotionRuntime({ repository, evaluationLedger: ledger, ownerAuthorization, now: () => now }); const record = evidence(); ledger.append(record); runtime.registerCandidate(identity()); const command = { promotionCommandId: "promotion-restart", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(record), ownerActorRef: "owner-1", reason: "owner review", requestedAt: now }; assert.equal(runtime.promote(command).status, "PROMOTED"); db.close(); const reopened = new SqliteDatabase(filename); try { const restored = new CandidatePromotionRuntime({ repository: new SqliteCandidatePromotionRepository(reopened), evaluationLedger: ledger, ownerAuthorization, now: () => now }); assert.equal(restored.currentChampion().identity.candidateId, "candidate-1"); assert.equal(restored.currentChampion().lifecycle, "CHAMPION"); assert.equal(restored.listAudit().length, 1); assert.equal(restored.promote(command).status, "DUPLICATE"); } finally { reopened.close(); } });
test("owner promotion rejects missing or invalid explicit cost evidence", () => {
  for (const costEvidence of [undefined, { ...evidence().costEvidence, observedAt: now }]) {
    const { db, ledger, runtime } = setup();
    try {
      runtime.registerCandidate(identity());
      ledger.append(evidence({ costEvidence }));
      const result = runtime.evaluatePromotionEligibility("candidate-1", "evaluation-1");
      assert.equal(result.eligible, false);
      assert.match(result.reason, /COST_EVIDENCE/);
    } finally {
      db.close();
    }
  }
});

test("inconclusive, stale, mismatched, or tampered evidence cannot promote", () => { for (const override of [{ result: "INCONCLUSIVE" }, { canonicalInputHash: "d".repeat(64) }, { evaluationTimestamp: now - 90_000_000 }]) { const { db, ledger, runtime } = setup(); try { runtime.registerCandidate(identity()); ledger.append(evidence(override)); assert.equal(runtime.evaluatePromotionEligibility("candidate-1", "evaluation-1").eligible, false); } finally { db.close(); } } });
test("same command id with a different payload is rejected and CAS conflicts retain champion", () => { const { db, ledger, runtime } = setup(); try { runtime.registerCandidate(identity()); ledger.append(evidence()); const base = { promotionCommandId: "promotion-1", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(evidence()), ownerActorRef: "owner-1", reason: "owner review", requestedAt: now }; assert.equal(runtime.promote(base).status, "PROMOTED"); assert.equal(runtime.promote({ ...base, reason: "different" }).status, "CONFLICT"); assert.equal(runtime.promote({ ...base, promotionCommandId: "promotion-2", expectedCurrentChampionCandidateId: null }).status, "CONFLICT"); } finally { db.close(); } });
test("audit chain uses verified actor identity and detects tampering", () => { const { db, ledger, runtime } = setup(); try { runtime.registerCandidate(identity()); ledger.append(evidence()); const command = { promotionCommandId: "promotion-1", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(evidence()), ownerActorRef: "bad", reason: "review", requestedAt: now }; runtime.promote(command); assert.equal(runtime.listAudit().length, 1); assert.equal(runtime.listAudit()[0].actorRef, "UNAUTHENTICATED"); runtime.verifyAudit(); db.connection.prepare("UPDATE research_promotion_audit SET record_json = ? WHERE sequence = 1").run("{}"); assert.throws(() => runtime.verifyAudit(), /integrity/); } finally { db.close(); } });
