const test = require("node:test");
const assert = require("node:assert/strict");
const { recordStressExperiment, runExecutionCostStress } = require("../dist/apps/desktop/src/strategy/executionCostStress.js");

class RoundTrip { constructor() { this.id = "round"; this.name = "Round"; this.index = 0; } onTick(tick) { this.index += 1; return { type: this.index === 1 ? "BUY" : this.index === 2 ? "SELL" : "HOLD", reason: "round", confidence: 0, timestamp: tick.timestamp }; } reset() { this.index = 0; } }
class Flat { constructor() { this.id = "flat"; this.name = "Flat"; } onTick(tick) { return { type: "HOLD", reason: "flat", confidence: 0, timestamp: tick.timestamp }; } reset() {} }
const points = (values = [100, 120, 110, 130, 120, 140, 130, 150, 140]) => values.map((close, index) => ({ timestamp: index + 1, close }));
const candidates = () => [{ id: "round", strategyFactory: () => new RoundTrip() }, { id: "flat", strategyFactory: () => new Flat() }];
const scenarios = () => [
  { id: "high", feeRate: 0.3, spreadBps: 100, slippageBps: 100 },
  { id: "baseline", feeRate: 0, spreadBps: 0, slippageBps: 0 },
  { id: "medium", feeRate: 0.05, spreadBps: 20, slippageBps: 20 }
];
const walk = { trainSize: 3, testSize: 2, stepSize: 2, backtestConfig: { initialCash: 1000, orderQuantity: 1 } };
const identity = { sourceExperimentSha: "source-experiment-sha", datasetSha256: "a".repeat(64) };
const run = (overrides = {}) => runExecutionCostStress(points(), candidates(), walk, { scenarios: scenarios(), baselineScenarioId: "baseline", ...overrides }, identity);

test("1 validates scenario count and 2 rejects duplicate ids", () => { assert.throws(() => run({ scenarios: [{ id: "x", feeRate: 0, spreadBps: 0, slippageBps: 0 }], minimumScenarioCount: 2 }), /insufficient/); assert.throws(() => run({ scenarios: [{ id: "x", feeRate: 0, spreadBps: 0, slippageBps: 0 }, { id: "x", feeRate: 0, spreadBps: 0, slippageBps: 0 }] }), /unique/); });
test("3 rejects missing baseline and 4 invalid extreme costs", () => { assert.throws(() => run({ baselineScenarioId: "none" }), /baseline/); assert.throws(() => run({ scenarios: [{ id: "baseline", feeRate: 0, spreadBps: 20_000, slippageBps: 0 }, { id: "x", feeRate: 0, spreadBps: 0, slippageBps: 0 }] }), /non-positive sell/); });
test("5 canonical scenario ordering and 6 deterministic replay", () => { const first = run(); const replay = run(); assert.deepEqual(first, replay); assert.deepEqual(first.scenarios.map(x => x.scenario.id), ["baseline", "medium", "high"]); });
test("7 baseline result is preserved and 8 costs raise trading cost", () => { const result = run(); assert.equal(result.baseline.scenario.id, "baseline"); assert.ok(result.scenarios.find(x => x.scenario.id === "high").totalTradingCost > result.baseline.totalTradingCost); });
test("9 high costs reduce OOS return and 10 retain adverse scenarios", () => { const result = run(); const high = result.scenarios.find(x => x.scenario.id === "high"); assert.ok(high.markedTotalReturn < result.baseline.markedTotalReturn); assert.equal(result.scenarios.length, 3); });
test("11 negative expectancy and 12 profit factor warnings are detected", () => { const result = run(); assert.ok(result.warnings.includes("EXPECTANCY_TURNS_NEGATIVE")); assert.ok(result.warnings.includes("PROFIT_FACTOR_BELOW_ONE")); });
test("13 benchmark edge loss and 14 drawdown robustness warnings are represented", () => { const result = runExecutionCostStress(points([100,120,110,130,140,150,160,170,180]), [{ id: "flat", strategyFactory: () => new Flat() }], { ...walk, selectionPolicy: { minimumClosedTrades: 0 } }, { scenarios: [{ id: "baseline", feeRate: 0, spreadBps: 0, slippageBps: 0 }, { id: "high", feeRate: 0.1, spreadBps: 20, slippageBps: 20 }], baselineScenarioId: "baseline" }, identity); assert.ok(result.warnings.includes("BENCHMARK_EDGE_LOST")); assert.ok(Array.isArray(result.warnings)); });
test("15 break-even is an estimated grid reference or explicitly not found", () => { const result = run(); assert.ok(["ESTIMATED", "NOT_FOUND"].includes(result.breakEvenEstimate.status)); assert.ok(["ESTIMATED_NOT_EXACT_GRID_DEPENDENT", "BREAK_EVEN_NOT_FOUND"].includes(result.breakEvenEstimate.label)); });
test("16 RESELECT_PER_SCENARIO records mode and 17 FIX_BASELINE_SELECTION fixes train choices", () => { const reselect = run(); const fixed = run({ candidateSelectionMode: "FIX_BASELINE_SELECTION" }); assert.equal(reselect.selectionMode, "RESELECT_PER_SCENARIO"); assert.equal(fixed.selectionMode, "FIX_BASELINE_SELECTION"); assert.deepEqual(fixed.scenarios.find(x => x.scenario.id === "high").walkForwardResult.windows.map(x => x.selectedCandidateId), fixed.baseline.walkForwardResult.windows.map(x => x.selectedCandidateId)); });
test("18 baseline selection uses train only", () => { const base = runExecutionCostStress(points(), candidates(), walk, { scenarios: [{ id: "baseline", feeRate: 0, spreadBps: 0, slippageBps: 0 }, { id: "alternate", feeRate: 0, spreadBps: 0, slippageBps: 0 }], baselineScenarioId: "baseline" }, identity); const changed = runExecutionCostStress(points([100,120,110,130,150,140,130,150,140]), candidates(), walk, { scenarios: [{ id: "baseline", feeRate: 0, spreadBps: 0, slippageBps: 0 }, { id: "alternate", feeRate: 0, spreadBps: 0, slippageBps: 0 }], baselineScenarioId: "baseline" }, identity); assert.equal(base.baseline.walkForwardResult.windows[0].selectedCandidateId, changed.baseline.walkForwardResult.windows[0].selectedCandidateId); });
test("19 OOS metrics remain separate from 20 open-position marked policy", () => { const result = run(); const metrics = result.baseline.walkForwardResult.combinedOutOfSampleMetrics; assert.equal(metrics.closedTradeNetProfit, metrics.netProfit); assert.equal(metrics.markedTotalReturn, metrics.totalReturn); assert.ok(Number.isFinite(metrics.markedMaximumDrawdown)); });
test("21 candidate churn is surfaced through scenario warnings", () => { const result = run(); assert.ok(result.scenarios.every(x => Array.isArray(x.warnings))); });
test("22 Research Memory identity is deterministic and 23 record insertion is idempotent", () => { const result = run(); const records = new Map(); const adapter = { appendExperiment(record) { const existing = records.get(record.id); if (existing) { assert.deepEqual(existing, record); return existing; } records.set(record.id, record); return record; } }; assert.deepEqual(result.identity, run().identity); assert.deepEqual(recordStressExperiment(adapter, result, { datasetId: "dataset", manifestSchemaVersion: 1, market: "KRW-BTC", interval: "1m", startOpenTime: 0, endCloseTime: 60_000 }), recordStressExperiment(adapter, result, { datasetId: "dataset", manifestSchemaVersion: 1, market: "KRW-BTC", interval: "1m", startOpenTime: 0, endCloseTime: 60_000 })); });
test("24 invalid non-finite scenario fails closed", () => { assert.throws(() => run({ scenarios: [{ id: "baseline", feeRate: 0, spreadBps: 0, slippageBps: 0 }, { id: "bad", feeRate: NaN, spreadBps: 0, slippageBps: 0 }] }), /invalid cost/); });

