const test=require("node:test");const assert=require("node:assert/strict");
const e=require("../dist/apps/execution/src/index.js");
const base={fillId:"f1",tradeId:"t1",orderId:"o1",accountId:"a1",symbol:"BTCUSDT",qtyRaw:2n,priceRaw:100n,fillTimeMs:10};
class Evidence{constructor(){this.m=new Map()}append(x){if(this.m.has(x.reconciliationId))throw Error("duplicate");this.m.set(x.reconciliationId,x)}getById(id){return this.m.get(id)}getLatest(a){return [...this.m.values()].filter(x=>x.accountId===a).sort((x,y)=>y.observedAtMs-x.observedAtMs)[0]}}
const run=(local,remote,id="r1")=>{const restrictions=new e.InMemoryOrderOperationalRestrictionRepository();const evidence=new Evidence();const result=e.reconcileFills({reconciliationId:id,restrictionId:"x1",accountId:"a1",local,provider:new e.ScriptedSyntheticFillProvider(remote),fromMs:0,toMs:20,nowMs:30,policy:{qtyToleranceRaw:0n,priceToleranceRaw:0n},restrictions,evidence});return{result,restrictions,evidence}};
test("matching fills reconcile",()=>assert.equal(run([base],[base]).result.status,e.FillReconciliationStatus.MATCHED));
test("missing and duplicate fills are blocked",()=>{assert.equal(run([], [base]).result.status,e.FillReconciliationStatus.MISSING_LOCAL);assert.equal(run([base],[base,base]).result.status,e.FillReconciliationStatus.DUPLICATE_PROVIDER)});
test("quantity price and order mismatches are distinct",()=>{assert.equal(run([base],[{...base,qtyRaw:3n}]).result.status,e.FillReconciliationStatus.QTY_MISMATCH);assert.equal(run([base],[{...base,priceRaw:101n}]).result.status,e.FillReconciliationStatus.PRICE_MISMATCH);assert.equal(run([base],[{...base,orderId:"o2"}]).result.status,e.FillReconciliationStatus.ORDER_MISMATCH)});
test("provider unavailable preserves uncertainty",()=>assert.equal(run([base],undefined).result.status,e.FillReconciliationStatus.PROVIDER_UNAVAILABLE));
test("freshness expires matched evidence",()=>{const x=run([base],[base]).result;assert.equal(e.evaluateFillReconciliationFreshness(x,31,{expiringSoonAfterMs:5,staleAfterMs:10}),e.FillReconciliationFreshnessStatus.FRESH);assert.equal(e.evaluateFillReconciliationFreshness(x,41,{expiringSoonAfterMs:5,staleAfterMs:10}),e.FillReconciliationFreshnessStatus.STALE)});
test("fill restriction release requires later same-account match and separated reviewers",()=>{const bad=run([base],[{...base,qtyRaw:3n}],"bad");const matched=Object.freeze({...bad.result,reconciliationId:"good",status:e.FillReconciliationStatus.MATCHED,observedAtMs:40,mismatchFillIds:Object.freeze([]),restrictionId:undefined,reason:undefined});bad.evidence.append(matched);const releases=new e.InMemoryOrderOperationalRestrictionReleaseEvidenceRepository();const released=e.releaseFillRestriction({releaseId:"rel",restrictionId:"x1",matchedFillReconciliationId:"good",requestedBy:"alice",verifiedBy:"bob",rationale:"verified",nowMs:50,restrictions:bad.restrictions,reconciliations:bad.evidence,evidence:releases});assert.equal(released.status,"RELEASED");assert.equal(releases.getByRestrictionId("x1").matchedFillReconciliationId,"good")});
