const test = require("node:test");
const assert = require("node:assert/strict");
const { GlobalRiskGateway, InMemoryRiskEvidenceSink, evaluateGlobalRisk, RISK_CAPABILITY_DESCRIPTOR } = require("../dist/apps/execution/src/global-risk-gateway.js");
const policy = { policyVersion: "risk-v1", maxGlobalExposure: "100", maxDailyLoss: "10", maxPositionSize: "50", maxPositionCount: 5, maxStrategyExposure: "80", maxSymbolExposure: "70", maxConsecutiveLosses: 3 };
const context = (overrides = {}) => ({ exchange: "UPBIT", strategyId: "s1", symbol: "KRW-BTC", sessionId: "session-1", currentPosition: "0", openOrderExposure: "0", partialFillExposure: "0", expectedFillExposure: "10", realizedPnl: "0", unrealizedPnl: "0", positionCount: 0, strategyExposure: "0", symbolExposure: "0", consecutiveLosses: 0, unknownExecutionCount: 0, reconciliationStatus: "MATCH", marketData: "HEALTHY", credentialStatus: "READY", recoveryStatus: "COMPLETE", manualApprovalToken: "approval", productionMutationAllowed: false, killSwitches: [], ...overrides });
test("approves only a fully known and safe request and records evidence", () => { const sink = new InMemoryRiskEvidenceSink(); const gateway = new GlobalRiskGateway(policy, sink); const decision = gateway.evaluate("execution-1", context()); assert.equal(decision.result, "APPROVED"); assert.equal(decision.policyVersion, "risk-v1"); assert.equal(sink.records.length, 1); gateway.assertSubmitAllowed(decision); });
test("unknown execution, reconciliation, market, recovery, credential, kill, and approval block", () => { const decision = evaluateGlobalRisk("execution-2", policy, context({ unknownExecutionCount: 1, reconciliationStatus: "DIFF", marketData: "STALE", credentialStatus: "ERROR", recoveryStatus: "PENDING", manualApprovalToken: null, killSwitches: [{ scope: "GLOBAL", key: "global", active: true, reasonCode: "EMERGENCY", activatedAt: new Date().toISOString() }] })); assert.equal(decision.result, "BLOCKED"); for (const code of ["UNKNOWN_EXECUTION", "RECONCILIATION_DIFF", "MARKET_DATA_STALE", "CREDENTIAL_ERROR", "RECOVERY_PENDING", "MANUAL_APPROVAL_REQUIRED", "KILL_SWITCH_GLOBAL"]) assert.ok(decision.reasonCodes.includes(code)); });
test("exposure, loss, position, and strategy limits reject without approving", () => { const decision = evaluateGlobalRisk("execution-3", policy, context({ expectedFillExposure: "60", realizedPnl: "-11", positionCount: 5, strategyExposure: "80", symbolExposure: "70", consecutiveLosses: 3 })); assert.equal(decision.result, "REJECTED"); assert.ok(decision.reasonCodes.includes("MAX_DAILY_LOSS")); assert.ok(decision.reasonCodes.includes("MAX_POSITION_SIZE")); assert.ok(decision.reasonCodes.includes("MAX_POSITION_COUNT")); });
test("invalid or indeterminate inputs fail closed as UNKNOWN", () => { const decision = evaluateGlobalRisk("execution-4", policy, context({ expectedFillExposure: "NaN" })); assert.equal(decision.result, "UNKNOWN"); assert.deepEqual([...decision.reasonCodes], ["RISK_EVALUATION_UNKNOWN"]); assert.deepEqual(RISK_CAPABILITY_DESCRIPTOR, { riskGatewayPresent: true, killSwitchPresent: true, productionMutationAllowed: false }); });
