const test=require("node:test");const assert=require("node:assert/strict");const x=require("../dist/apps/execution/src/index.js");
class Evidence{constructor(){this.m=new Map()}append(v){this.m.set(v.assessmentId,v)}getById(id){return this.m.get(id)}getLatest(a,s){return [...this.m.values()].filter(v=>v.accountId===a&&v.symbol===s).sort((a,b)=>b.observedAtMs-a.observedAtMs)[0]}}
const base=(over={})=>({assessmentId:"a1",accountId:"acct",symbol:"BTCUSDT",walletBalanceRaw:1000n,unrealizedPnlRaw:0n,maintenanceMarginRaw:100n,initialMarginRaw:200n,positionNotionalRaw:10000n,observedAtMs:1000,...over});
const policy={criticalRatioPpm:1200000n,watchRatioPpm:2000000n};
test("healthy margin does not restrict",()=>{const restrictions=new x.InMemoryOrderOperationalRestrictionRepository();const r=x.assessLiquidationRisk({snapshot:base(),restrictionId:"r1",policy,restrictions,evidence:new Evidence()});assert.equal(r.status,x.LiquidationRiskStatus.HEALTHY);assert.equal(restrictions.getActiveForAccount("acct"),undefined)});
test("watch margin is observable but not an automatic restriction",()=>{const restrictions=new x.InMemoryOrderOperationalRestrictionRepository();const r=x.assessLiquidationRisk({snapshot:base({walletBalanceRaw:150n}),restrictionId:"r2",policy,restrictions,evidence:new Evidence()});assert.equal(r.status,x.LiquidationRiskStatus.WATCH);assert.equal(restrictions.getActiveForAccount("acct"),undefined)});
test("critical margin blocks new exposure without closing position",()=>{const restrictions=new x.InMemoryOrderOperationalRestrictionRepository();const r=x.assessLiquidationRisk({snapshot:base({walletBalanceRaw:110n}),restrictionId:"r3",policy,restrictions,evidence:new Evidence()});assert.equal(r.status,x.LiquidationRiskStatus.CRITICAL);assert.equal(restrictions.getActiveForAccount("acct").reason,x.OrderOperationalRestrictionReason.LIQUIDATION_RISK_CRITICAL)});
test("invalid maintenance state is fail closed",()=>{const restrictions=new x.InMemoryOrderOperationalRestrictionRepository();const r=x.assessLiquidationRisk({snapshot:base({maintenanceMarginRaw:0n}),restrictionId:"r4",policy,restrictions,evidence:new Evidence()});assert.equal(r.status,x.LiquidationRiskStatus.INVALID);assert.equal(restrictions.getActiveForAccount("acct").reason,x.OrderOperationalRestrictionReason.MARGIN_STATE_INVALID)});
test("zero position is classified separately",()=>{const r=x.assessLiquidationRisk({snapshot:base({positionNotionalRaw:0n}),restrictionId:"r5",policy,restrictions:new x.InMemoryOrderOperationalRestrictionRepository(),evidence:new Evidence()});assert.equal(r.status,x.LiquidationRiskStatus.NO_POSITION)});
