const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

test("settings UI exposes implemented preferences, Paper safety, operator user management, reset, and local sign-out", () => {
  const source = fs.readFileSync(path.join(__dirname, "..", "apps", "mobile", "src", "settingsView.tsx"), "utf8");
  assert.match(source, /settings-theme/);
  assert.match(source, /settings-notifications/);
  assert.match(source, /settings-mode/);
  assert.match(source, /settings-about/);
  assert.match(source, /settings-reset/);
  assert.match(source, /settings-session/);
  assert.match(source, /settings-capital-allocation/);
  assert.match(source, /settings-operator-users/);
  assert.match(source, /operator-user-token/);
  assert.match(source, /operator-user-refresh/);
  assert.match(source, /users:manage/);
  assert.match(source, /토큰은 저장하지 않습니다/);
  assert.match(source, /실제 투자 가능 금액/);
  assert.match(source, /보호되는 현금 금액/);
  assert.match(source, /settings-loading/);
  assert.match(source, /settings-error/);
  assert.match(source, /value === "SYSTEM" \? "system"/);
  assert.doesNotMatch(source, /settings-locale-|언어 선택/);
  assert.match(source, /PAPER/);
  assert.match(source, /READ ONLY/);
  assert.match(source, /SettingsRepository/);
  assert.doesNotMatch(source, /placeOrder|cancelOrder|withdraw/);

  const app = fs.readFileSync(path.join(__dirname, "..", "apps", "mobile", "App.tsx"), "utf8");
  assert.doesNotMatch(app, /<MoreView/);
  assert.match(app, /header-settings/);
  assert.match(app, /utilityView === "SETTINGS" \? <SettingsView/);
  assert.match(app, /exchangeCash=\{accountCash\}/);
  assert.match(app, /onCloudInvestmentPercentSave=\{investmentAllocationClient\.save\}/);
  assert.match(app, /onInvestmentPercentChanged=\{setInvestmentPercent\}/);
  assert.match(app, /onSignOut=\{handleSignOut\}/);
  assert.match(app, /repository=\{settingsRepository\}/);
  assert.match(app, /credentialSession\.clear\(\)/);
  assert.match(app, /signOut\(\)/);
  assert.match(app, /settingsRepository/);
});
