const test = require("node:test");
const assert = require("node:assert/strict");
const { evaluateRisk, evaluatePaperRisk, canResumeCircuitBreaker, portfolioRiskLevel } = require("../dist/apps/mobile/src/riskManagement.js");
const policy = { dailyLossLimit: 100, maxPositionQuantity: 10, maxSymbolExposure: 1000, maxOrderQuantity: 5, maxConsecutiveLosses: 3 };
const input = (overrides = {}) => ({ orderQuantity: 1, orderNotional: 100, currentPositionQuantity: 0, symbolExposure: 0, dailyRealizedLoss: 0, consecutiveLosses: 0, circuitBreakerActive: false, stateKnown: true, ...overrides });

test("approves a known safe Paper order and never grants production authority", () => { const result = evaluatePaperRisk(input(), policy); assert.equal(result.decision, "APPROVED"); assert.equal(result.productionMutationAllowed, false); assert.ok(result.riskScore >= 0); });
test("blocks every configured loss, position, exposure, quantity and circuit limit", () => { for (const [patch, reason] of [[{ dailyRealizedLoss: 100 }, "DAILY_LOSS_LIMIT"], [{ currentPositionQuantity: 10 }, "POSITION_LIMIT"], [{ symbolExposure: 950 }, "SYMBOL_EXPOSURE_LIMIT"], [{ orderQuantity: 6 }, "ORDER_QUANTITY_LIMIT"], [{ consecutiveLosses: 3 }, "CONSECUTIVE_LOSS_LIMIT"], [{ circuitBreakerActive: true }, "CIRCUIT_BREAKER_ACTIVE"]]) { const result = evaluatePaperRisk(input(patch), policy); assert.equal(result.decision, "BLOCKED"); assert.ok(result.reasons.includes(reason)); } });
test("unknown state and invalid policy fail closed", () => { assert.equal(evaluatePaperRisk(input({ stateKnown: false }), policy).decision, "BLOCKED"); assert.equal(evaluatePaperRisk(input(), { ...policy, dailyLossLimit: 0 }).decision, "BLOCKED"); });
test("the common risk evaluator preserves the Paper safety boundary", () => { assert.equal(evaluateRisk(input(), policy).productionMutationAllowed, false); });
test("circuit breaker recovery requires acknowledgement and safe state", () => { assert.equal(canResumeCircuitBreaker({ dailyRealizedLoss: 0, consecutiveLosses: 0, stateKnown: true, circuitBreakerActive: true }, policy, true), false); assert.equal(canResumeCircuitBreaker({ dailyRealizedLoss: 0, consecutiveLosses: 0, stateKnown: true, circuitBreakerActive: false }, policy, false), false); assert.equal(canResumeCircuitBreaker({ dailyRealizedLoss: 0, consecutiveLosses: 0, stateKnown: true, circuitBreakerActive: false }, policy, true), true); });
test("portfolio risk levels are deterministic and fail closed", () => { assert.equal(portfolioRiskLevel(0), "LOW"); assert.equal(portfolioRiskLevel(30), "MEDIUM"); assert.equal(portfolioRiskLevel(60), "HIGH"); assert.equal(portfolioRiskLevel(Number.NaN), "CRITICAL"); });
