const test = require("node:test"); const assert = require("node:assert/strict");
const { hash, verifyShadowPilotEvidence, verifyCanaryPilotEvidence } = require("../scripts/lib/pilot-independent-verifier.js");
const commit = "a".repeat(40), fingerprints = { strategy: "s", config: "c", runtime: "r", riskPolicy: "p" };
function event(raw) { return { ...raw, eventSha256: hash(raw) }; }
function shadow(type = "TEST_FIXTURE") { const session = { schemaVersion: 1, sessionId: "shadow-1", createdAt: 1, startedAt: 2, stoppedAt: 4, status: "COMPLETED", sourceCommitSha: commit, symbol: "KRW-BTC", strategyId: "sma", fingerprints, counters: { signalCount: 1, allowCount: 2, rejectCount: 0, haltCount: 0, hypotheticalOrderCount: 1, hypotheticalFillCount: 1, actualOrderCount: 0, actualFillCount: 0, cashMutationCount: 0, positionMutationCount: 0 }, blockers: [] }; session.resultSha256 = hash(session); const started = event({ sequence: 1, timestamp: 2, sessionId: "shadow-1", eventType: "SESSION_STARTED", signalId: "session", commandId: "session", riskDecision: "ALLOW", reasonCodes: [], actualBrokerCallCount: 0, actualOrderDelta: 0, actualFillDelta: 0, actualCashDelta: 0, actualPositionDelta: 0, previousEventSha256: "GENESIS" }); const fill = event({ sequence: 2, timestamp: 3, sessionId: "shadow-1", eventType: "HYPOTHETICAL_FILL", signalId: "signal", commandId: "command", riskDecision: "ALLOW", reasonCodes: [], hypotheticalOrderId: "shadow-order-shadow-1-2", hypotheticalFillId: "shadow-fill-shadow-1-2", actualBrokerCallCount: 0, actualOrderDelta: 0, actualFillDelta: 0, actualCashDelta: 0, actualPositionDelta: 0, previousEventSha256: started.eventSha256 }); return { evidenceType: type, schemaVersion: 1, session, events: [started, fill] }; }
function canary(type = "TEST_FIXTURE") { const approval = { approvalId: "approval", approvedBy: "owner", approvedAt: 1, expiresAt: 1000, mode: "PAPER_CANARY", sourceCommitSha: commit, allowedSymbol: "KRW-BTC", allowedStrategyId: "sma", fingerprints, maxDurationMinutes: 1, maxOrders: 5, maxTrades: 5, maxOpenPositions: 1, maxOrderQuantity: 1, maxOrderNotional: 100, maxGrossExposure: 100, maxDailyLoss: 1, maxSessionLoss: 1, maxDrawdown: 1, maxConsecutiveLosses: 1 }; approval.approvalSha256 = hash(approval); const session = { schemaVersion: 1, sessionId: "canary-1", approvalId: "approval", startedAt: 2, stoppedAt: 4, status: "COMPLETED", sourceCommitSha: commit, symbol: "KRW-BTC", strategyId: "sma", fingerprints, orderCount: 1, automaticTrading: false, blockers: [] }; session.resultSha256 = hash(session); const started = event({ sequence: 1, timestamp: 2, sessionId: "canary-1", approvalId: "approval", eventType: "SESSION_STARTED", commandId: "start", clientOrderId: "start", riskDecision: "ALLOW", canaryDecision: "ALLOW", reasonCodes: [], actualBrokerCallCount: 0, previousEventSha256: "GENESIS" }); const fill = event({ sequence: 2, timestamp: 3, sessionId: "canary-1", approvalId: "approval", eventType: "ORDER_FILLED", commandId: "command", clientOrderId: "client", riskDecision: "ALLOW", canaryDecision: "ALLOW", reasonCodes: [], orderId: "order-1", fillId: "fill-1", actualBrokerCallCount: 1, previousEventSha256: started.eventSha256 }); return { evidenceType: type, schemaVersion: 1, approval, session, events: [started, fill] }; }
test("independent verifier seals full Shadow and Canary event evidence", () => { assert.equal(verifyShadowPilotEvidence(shadow(), { sourceCommitSha: commit }).verifierStatus, "PASS"); assert.equal(verifyCanaryPilotEvidence(canary(), { sourceCommitSha: commit }).verifierStatus, "PASS"); });
test("independent verifier catches Shadow mutations and Canary linkage tampering", () => { const unsafe = shadow(); unsafe.events[1].actualCashDelta = 1; unsafe.events[1].eventSha256 = hash(Object.fromEntries(Object.entries(unsafe.events[1]).filter(([key]) => key !== "eventSha256"))); assert.equal(verifyShadowPilotEvidence(unsafe).verifierStatus, "FAIL"); const tampered = canary(); tampered.events[1].fillId = "fill-2"; assert.equal(verifyCanaryPilotEvidence(tampered).verifierStatus, "FAIL"); });
test("operational evidence requires elapsed operational observations", () => { const evidence = shadow("SHADOW_OPERATIONAL"); delete evidence.session.stoppedAt; evidence.session.resultSha256 = hash(Object.fromEntries(Object.entries(evidence.session).filter(([key]) => key !== "resultSha256"))); assert.equal(verifyShadowPilotEvidence(evidence).verifierStatus, "FAIL"); });
module.exports = { shadow, canary, commit, fingerprints };
