const test=require("node:test");const assert=require("node:assert/strict");const x=require("../dist/apps/execution/src/index.js");
const snap=(over={})=>({accountId:"acct",asset:"USDT",realizedPnlRaw:100n,unrealizedPnlRaw:20n,fundingPnlRaw:-3n,feeRaw:2n,observedAtMs:1000,...over});
const policy={realizedToleranceRaw:0n,unrealizedToleranceRaw:0n,fundingToleranceRaw:0n,feeToleranceRaw:0n};
function deps(remote){return{restrictions:new x.InMemoryOrderOperationalRestrictionRepository(),evidence:new(class{constructor(){this.m=new Map()}append(v){this.m.set(v.reconciliationId,v)}getById(id){return this.m.get(id)}getLatest(a,s){return [...this.m.values()].filter(v=>v.accountId===a&&v.asset===s).sort((a,b)=>b.observedAtMs-a.observedAtMs)[0]}})(),provider:new x.ScriptedSyntheticPnlProvider(remote?[remote]:[])}}
test("matches complete PnL components",()=>{const d=deps(snap());const r=x.reconcilePnl({reconciliationId:"p1",restrictionId:"r1",local:snap(),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1000});assert.equal(r.status,x.PnlReconciliationStatus.MATCHED);assert.equal(d.restrictions.getActiveForAccount("acct"),undefined)});
test("realized PnL mismatch blocks new exposure",()=>{const d=deps(snap({realizedPnlRaw:101n}));const r=x.reconcilePnl({reconciliationId:"p2",restrictionId:"r2",local:snap(),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1000});assert.equal(r.status,x.PnlReconciliationStatus.REALIZED_MISMATCH);assert.equal(d.restrictions.getActiveForAccount("acct").reason,x.OrderOperationalRestrictionReason.PNL_RECONCILIATION_MISMATCH)});
test("provider absence remains uncertain",()=>{const d=deps();const r=x.reconcilePnl({reconciliationId:"p3",restrictionId:"r3",local:snap(),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1000});assert.equal(r.status,x.PnlReconciliationStatus.PROVIDER_UNAVAILABLE)});
test("stale PnL evidence creates restriction",()=>{const d=deps(snap());x.reconcilePnl({reconciliationId:"p4",restrictionId:"unused",local:snap(),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1000});const r=x.enforcePnlFreshness({restrictionId:"stale",accountId:"acct",asset:"USDT",nowMs:2001,policy:{maxAgeMs:1000,expiringSoonMs:100},restrictions:d.restrictions,evidence:d.evidence});assert.equal(r.reason,x.OrderOperationalRestrictionReason.PNL_RECONCILIATION_STALE)});
test("release requires later matched evidence and separated reviewers",()=>{const d=deps(snap({realizedPnlRaw:101n}));x.reconcilePnl({reconciliationId:"bad",restrictionId:"r5",local:snap(),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1000});d.provider=new x.ScriptedSyntheticPnlProvider([snap({observedAtMs:1100})]);x.reconcilePnl({reconciliationId:"good",restrictionId:"unused",local:snap({observedAtMs:1100}),provider:d.provider,policy,restrictions:d.restrictions,evidence:d.evidence,nowMs:1100});const releases=new x.InMemoryOrderOperationalRestrictionReleaseEvidenceRepository();const r=x.releasePnlRestriction({releaseId:"rel",restrictionId:"r5",matchedPnlReconciliationId:"good",requestedBy:"a",verifiedBy:"b",rationale:"reconciled",nowMs:1100,restrictions:d.restrictions,evidence:d.evidence,releaseEvidence:releases});assert.equal(r.status,"RELEASED");assert.equal(releases.getByRestrictionId("r5").matchedPnlReconciliationId,"good")});
