const test = require("node:test");
const assert = require("node:assert/strict");
const { SqliteDatabase, SqliteResearchEvaluationLedger, SqliteCandidatePromotionRepository } = require("../dist/packages/storage/src/index.js");
const { CandidatePromotionRuntime } = require("../dist/apps/cloud/src/candidatePromotionRuntime.js");
const { ResearchRecoveryCoordinator } = require("../dist/apps/cloud/src/researchRecoveryCoordinator.js");
const { startCloudRuntime } = require("../dist/apps/cloud/src/runtime.js");
const { InMemoryCloudDashboardStateProvider } = require("../dist/apps/cloud/src/cloudDashboardStateProvider.js");
const { canonicalResearchJson } = require("../dist/packages/contracts/src/researchRuntime.js");
const crypto = require("node:crypto");
const { mkdtempSync } = require("node:fs");
const { join } = require("node:path");
const { tmpdir } = require("node:os");

const now = 1_800_000_000_000;
const digest = (value) => crypto.createHash("sha256").update(canonicalResearchJson(value)).digest("hex");
const identity = (overrides = {}) => ({ candidateId: "candidate-1", strategyId: "strategy-1", strategyVersion: "1.0.0", artifactHash: "a".repeat(64), configHash: "b".repeat(64), createdAt: now - 1000, originatingEvaluationId: "evaluation-1", originatingInputHash: "c".repeat(64), authority: "PAPER_ONLY", paperOnly: true, ...overrides });
const evidence = (overrides = {}) => ({ schemaVersion: 1, researchRunId: "run-1", evaluationId: "evaluation-1", strategyId: "strategy-1", strategyVersion: "1.0.0", marketDataTimestamp: now - 2000, evaluationTimestamp: now - 1000, canonicalInputHash: "c".repeat(64), modelVersion: "model-1", fillModelVersion: "fill-1", feeModelVersion: "fee-1", slippageModelVersion: "slip-1", champion: { strategyId: "strategy-1", strategyVersion: "0.9.0", authority: "PAPER_ONLY", evaluatorVersion: "champion-1", canonicalInputHash: "c".repeat(64), metrics: { netReturn: 1 }, signal: "HOLD" }, challenger: { strategyId: "strategy-1", strategyVersion: "1.0.0", authority: "ZERO_AUTHORITY", evaluatorVersion: "challenger-1", canonicalInputHash: "c".repeat(64), metrics: { netReturn: 2, costAdjustedReturn: 2 }, signal: "HOLD" }, costEvidence: { schemaVersion: 1, evaluationId: "evaluation-1", datasetId: "dataset-1", datasetContentSha256: "a".repeat(64), feeRate: 0.001, spreadRate: 0.0005, slippageRate: 0.0005, turnoverRate: 2, grossReturn: 2.004, netReturn: 2, costModelVersion: "cost-v1", observedAt: now - 2000 }, result: "CHALLENGER_BETTER", reason: "NET_RETURN_COMPARISON", productionMutationAllowed: false, promotionAllowed: false, ...overrides });
const ownerAuthorization = { authorize(command) { return command.ownerActorRef === "owner-1" ? { actorRef: "owner-1", authenticated: true } : null; } };

function validState() {
  const db = new SqliteDatabase();
  const repository = new SqliteCandidatePromotionRepository(db);
  const ledger = new SqliteResearchEvaluationLedger(db);
  const runtime = new CandidatePromotionRuntime({ repository, evaluationLedger: ledger, ownerAuthorization, now: () => now });
  const record = evidence();
  ledger.append(record);
  runtime.registerCandidate(identity());
  const command = { promotionCommandId: "promotion-1", expectedCurrentChampionCandidateId: null, candidateId: "candidate-1", evidenceEvaluationId: "evaluation-1", evidenceHash: digest(record), ownerActorRef: "owner-1", reason: "owner review", requestedAt: now };
  assert.equal(runtime.promote(command).status, "PROMOTED");
  return { db, repository, ledger, recovery: new ResearchRecoveryCoordinator({ repository, evaluationLedger: ledger, now: () => now }) };
}

test("clean close/reopen produces a ready deterministic snapshot", () => { const state = validState(); try { const first = state.recovery.recover(); assert.equal(first.status, "READY"); assert.equal(first.snapshot.championAuthority, "PAPER_ONLY"); assert.equal(first.snapshot.challengerAuthority, "ZERO_AUTHORITY"); assert.equal(first.snapshot.liveAuthority, "NONE"); assert.equal(first.snapshot.productionMutationAllowed, false); const second = state.recovery.recover(); assert.equal(second.status, "READY"); assert.equal(first.snapshot.stateDigest, second.snapshot.stateDigest); assert.equal(first.snapshot.recoveredAt, second.snapshot.recoveredAt); } finally { state.db.close(); } });
test("evaluation corruption is fail closed", () => { const state = validState(); try { state.db.connection.prepare("UPDATE research_evaluation_ledger SET hash = ? WHERE evaluation_id = ?").run("f".repeat(64), "evaluation-1"); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.match(result.reasons[0], /research evaluation ledger integrity/); } finally { state.db.close(); } });
test("promotion audit corruption is fail closed", () => { const state = validState(); try { state.db.connection.prepare("UPDATE research_promotion_audit SET current_hash = ? WHERE sequence = 1").run("f".repeat(64)); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.match(result.reasons[0], /promotion audit integrity/); } finally { state.db.close(); } });
test("candidate checksum corruption is fail closed", () => { const state = validState(); try { state.db.connection.prepare("UPDATE research_candidates SET checksum = ? WHERE candidate_id = ?").run("f".repeat(64), "candidate-1"); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.match(result.reasons[0], /candidate lifecycle integrity/); } finally { state.db.close(); } });
test("missing originating evaluation and dangling promotion evidence are rejected", () => { const state = validState(); try { state.db.connection.prepare("DELETE FROM research_evaluation_ledger WHERE evaluation_id = ?").run("evaluation-1"); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.match(result.reasons[0], /MISSING_ORIGINATING_EVALUATION|PROMOTION_EVIDENCE_MISMATCH/); } finally { state.db.close(); } });
test("candidate strategy/version and canonical input mismatches are rejected", () => { for (const property of ["strategyVersion", "originatingInputHash"]) { const state = validState(); try { const candidateRow = state.db.connection.prepare("SELECT payload_json FROM research_candidates WHERE candidate_id = ?").get("candidate-1"); const candidate = JSON.parse(candidateRow.payload_json); candidate.identity[property] = property === "strategyVersion" ? "9.9.9" : "d".repeat(64); const payload = JSON.stringify(candidate); const checksum = crypto.createHash("sha256").update(payload).digest("hex"); state.db.connection.prepare("UPDATE research_candidates SET payload_json = ?, checksum = ? WHERE candidate_id = ?").run(payload, checksum, "candidate-1"); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.match(result.reasons[0], /CANDIDATE_STRATEGY_VERSION_MISMATCH|CANDIDATE_INPUT_HASH_MISMATCH/); } finally { state.db.close(); } } });
test("Champion pointer and lifecycle must reconcile with owner promotion history", () => { const state = validState(); try { state.db.connection.prepare("UPDATE research_champion_pointer SET candidate_id = ? WHERE id = 1").run("missing"); assert.equal(state.recovery.recover().status, "FAIL_CLOSED"); } finally { state.db.close(); } const noHistory = validState(); try { noHistory.db.connection.prepare("DELETE FROM research_promotion_audit").run(); noHistory.db.connection.prepare("DELETE FROM research_promotion_commands").run(); assert.equal(noHistory.recovery.recover().status, "FAIL_CLOSED"); } finally { noHistory.db.close(); } });
test("partial promotion states are rejected without automatic repair or promotion", () => { const state = validState(); try { state.db.connection.prepare("UPDATE research_candidates SET lifecycle = ? WHERE candidate_id = ?").run("PAPER_CANDIDATE", "candidate-1"); const result = state.recovery.recover(); assert.equal(result.status, "FAIL_CLOSED"); assert.equal(state.repository.getChampion(), "candidate-1"); } finally { state.db.close(); } });
test("recovery is authority-neutral and leaves commands, audits, and Champion unchanged", () => { const state = validState(); try { const before = { champion: state.repository.getChampion(), audit: state.repository.listAudit().length, commands: state.repository.listCommands().length }; const result = state.recovery.recover(); assert.equal(result.status, "READY"); const after = { champion: state.repository.getChampion(), audit: state.repository.listAudit().length, commands: state.repository.listCommands().length }; assert.deepEqual(after, before); } finally { state.db.close(); } });
test("research recovery failure is isolated while PAPER/dashboard remains fail closed", async () => { const provider = new InMemoryCloudDashboardStateProvider(); const handle = startCloudRuntime({ NUSA_CLOUD_DASHBOARD_PORT: "41919", NUSA_CLOUD_DASHBOARD_TOKEN: "research-recovery-test-token-at-least-32-bytes" }, provider, undefined, undefined, undefined, undefined, undefined, undefined, { recover: () => ({ status: "FAIL_CLOSED", snapshot: null, reasons: ["CORRUPTED_RESEARCH_STATE"] }) }); try { const state = provider.read({ userId: "operator", scopes: ["dashboard:read"] }); assert.notEqual(state, undefined); assert.equal(state.mode, "PAPER"); assert.equal(state.killSwitchActive, true); assert.equal(state.overallHealth, "DOWN"); } finally { await handle.stop(); } });
test("unsupported future schema is rejected by the existing migration runner", () => { const filename = join(mkdtempSync(join(tmpdir(), "nusa-future-schema-")), "research.db"); const raw = new (require("node:sqlite").DatabaseSync)(filename); raw.exec("CREATE TABLE schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL, checksum TEXT); INSERT INTO schema_migrations VALUES ('999_future', 'now', 'x')"); raw.close(); assert.throws(() => new SqliteDatabase(filename), /database contains unknown migration|migration/); });
