import { createHash } from "node:crypto";
import type { PaperBroker, PaperSide } from "../paper/paperBroker";
import type { RuntimeCommandService } from "../control/runtimeCommandService";

export type CanaryStatus = "IDLE" | "PRECHECK" | "APPROVED" | "READY" | "RUNNING" | "PAUSED" | "COMPLETED" | "HALTED" | "LIMIT_REACHED" | "EXPIRED" | "INVALIDATED" | "FAILED";
export interface CanaryApproval { readonly approvalId: string; readonly approvedBy: string; readonly approvedAt: number; readonly expiresAt: number; readonly mode: "PAPER_CANARY"; readonly sourceCommitSha: string; readonly allowedSymbol: string; readonly allowedStrategyId: string; readonly maxDurationMinutes: number; readonly maxOrders: number; readonly maxTrades: number; readonly maxOpenPositions: number; readonly maxOrderQuantity: number; readonly maxOrderNotional: number; readonly maxGrossExposure: number; readonly maxDailyLoss: number; readonly maxSessionLoss: number; readonly maxDrawdown: number; readonly maxConsecutiveLosses: number; readonly fingerprints: Readonly<{ strategy: string; config: string; runtime: string; riskPolicy: string }>; readonly approvalSha256: string; }
export interface CanaryPrecheck { readonly paperOnly: boolean; readonly shadowEvidencePassed: boolean; readonly deploymentIntegrity: boolean; readonly reconciliation: boolean; readonly killSwitch: boolean; readonly openP0: boolean; readonly marketDataHealthy: boolean; readonly warmedUp: boolean; readonly automaticTrading: boolean; readonly persistenceHealthy: boolean; }
export interface CanaryEvent { readonly sequence: number; readonly timestamp: number; readonly sessionId: string; readonly approvalId: string; readonly eventType: "SESSION_STARTED" | "ORDER_FILLED" | "BLOCKED" | "SESSION_STOPPED"; readonly commandId: string; readonly clientOrderId: string; readonly riskDecision: "ALLOW" | "REJECT" | "HALT"; readonly canaryDecision: "ALLOW" | "REJECT" | "HALT"; readonly reasonCodes: readonly string[]; readonly orderId?: string; readonly fillId?: string; readonly actualBrokerCallCount: number; readonly previousEventSha256: string; readonly eventSha256: string; }
export interface CanaryPersistence { save(input: Readonly<{ events: readonly CanaryEvent[]; snapshot: ReturnType<CanaryPilotRuntime["snapshot"]> }>): void; }
const canonicalize=(value:unknown):unknown=>value===null||typeof value!=="object"?value:Array.isArray(value)?value.map(canonicalize):Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalize((value as Record<string,unknown>)[key])]));
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(canonicalize(value)),"utf8").digest("hex");
const finite=(value:number)=>Number.isFinite(value)&&value>0;
export function createCanaryApproval(input: Omit<CanaryApproval,"approvalSha256">): CanaryApproval { const approval={...input}; validateCanaryApproval({...approval,approvalSha256:hash(approval)}); return Object.freeze({...approval,approvalSha256:hash(approval)}); }
export function validateCanaryApproval(value: CanaryApproval): void { const {approvalSha256,...raw}=value; if(!value.approvalId||!value.approvedBy||value.mode!=="PAPER_CANARY"||!value.allowedSymbol||!value.allowedStrategyId||!value.sourceCommitSha||value.approvedAt>=value.expiresAt||value.approvalSha256!==hash(raw))throw new Error("invalid canary approval"); if(![value.maxDurationMinutes,value.maxOrders,value.maxTrades,value.maxOpenPositions,value.maxOrderQuantity,value.maxOrderNotional,value.maxGrossExposure,value.maxDailyLoss,value.maxSessionLoss,value.maxDrawdown,value.maxConsecutiveLosses].every(finite)||!Object.values(value.fingerprints).every(Boolean))throw new Error("invalid canary limits"); }
export class CanaryPilotRuntime {
  private status:CanaryStatus="IDLE";private orders=0;private readonly commands=new Set<string>();private readonly events:CanaryEvent[]=[];private blockers:string[]=[];private startedAt=0;private stoppedAt?:number;
  constructor(private readonly input:Readonly<{sessionId:string;symbol:string;strategyId:string;sourceCommitSha:string;fingerprints:CanaryApproval["fingerprints"];approval:CanaryApproval;runtime:RuntimeCommandService;broker:PaperBroker;persistence:CanaryPersistence}> ){}
  precheck(check:CanaryPrecheck,_now:number):CanaryStatus { if(this.status!=="IDLE")throw new Error("canary is not idle");this.status="PRECHECK";try{validateCanaryApproval(this.input.approval);}catch{this.blockers.push("APPROVAL_INVALID");}this.blockers.push(...[!check.paperOnly&&"NOT_PAPER_ONLY",!check.shadowEvidencePassed&&"SHADOW_EVIDENCE_MISSING",!check.deploymentIntegrity&&"DEPLOYMENT_FAILED",!check.reconciliation&&"RECONCILIATION_REQUIRED",check.killSwitch&&"KILL_SWITCH_ACTIVE",check.openP0&&"OPEN_P0_ALERT",!check.marketDataHealthy&&"MARKET_DATA_UNHEALTHY",!check.warmedUp&&"WARMING_UP",check.automaticTrading&&"AUTOMATIC_TRADING_ON",!check.persistenceHealthy&&"PERSISTENCE_UNHEALTHY",this.input.approval.sourceCommitSha!==this.input.sourceCommitSha&&"SOURCE_COMMIT_MISMATCH",this.input.approval.allowedSymbol!==this.input.symbol&&"SYMBOL_SCOPE_MISMATCH",this.input.approval.allowedStrategyId!==this.input.strategyId&&"STRATEGY_SCOPE_MISMATCH",Object.keys(this.input.fingerprints).some(k=>this.input.approval.fingerprints[k as keyof CanaryApproval["fingerprints"]]!==this.input.fingerprints[k as keyof CanaryApproval["fingerprints"]])&&"FINGERPRINT_MISMATCH"].filter(Boolean) as string[]);this.status=this.blockers.length?"HALTED":"READY";return this.status; }
  start(now:number):void{if(this.status!=="READY")throw new Error("canary requires explicit approved start");this.status="RUNNING";this.startedAt=now;this.append("SESSION_STARTED",now,"start","ALLOW","ALLOW",[]);}
  order(command:Readonly<{commandId:string;side:PaperSide;quantity:number;price:number;now:number;metrics?:Readonly<{completedTrades:number;openPositions:number;grossExposure:number;dailyLoss:number;sessionLoss:number;drawdown:number;consecutiveLosses:number}>}>):void { if(this.status!=="RUNNING")throw new Error("canary is not running");const reasons=this.limitReasons(command);if(reasons.length){this.block(command,reasons);return;}const state=this.input.broker.exportState();try{const order=this.input.runtime.manualOrder(command.side,command.quantity,command.price);this.orders++;this.append("ORDER_FILLED",command.now,command.commandId,"ALLOW","ALLOW",[],order.id,`paper-fill-${order.id}`,1);this.input.persistence.save({events:this.eventLog(),snapshot:this.snapshot()});}catch(error){try{this.input.broker.restoreState(state);}catch{this.status="FAILED";}this.status=this.status==="FAILED"?"FAILED":"HALTED";this.append("BLOCKED",command.now,command.commandId,"HALT","HALT",[error instanceof Error?error.message:"PERSISTENCE_FAILURE"]);} }
  restart():void{if(this.status==="RUNNING")this.status="INVALIDATED";}
  stop(now:number):void{if(!["RUNNING","HALTED","LIMIT_REACHED"].includes(this.status))throw new Error("canary cannot stop from current state");this.append("SESSION_STOPPED",now,"session-stop","ALLOW","ALLOW",[]);this.stoppedAt=now;if(this.status==="RUNNING")this.status="COMPLETED";}
  snapshot(){const raw={schemaVersion:1 as const,sessionId:this.input.sessionId,approvalId:this.input.approval.approvalId,status:this.status,sourceCommitSha:this.input.sourceCommitSha,symbol:this.input.symbol,strategyId:this.input.strategyId,startedAt:this.startedAt,...(this.stoppedAt===undefined?{}:{stoppedAt:this.stoppedAt}),fingerprints:this.input.fingerprints,orderCount:this.orders,automaticTrading:false as const,blockers:[...this.blockers].sort()};return Object.freeze({...raw,resultSha256:hash(raw)});}
  eventLog(){return Object.freeze([...this.events]);}
  resume(check:CanaryPrecheck,now:number):void{if(this.status!=="PAUSED")throw new Error("canary requires explicit paused resume");this.status="IDLE";if(this.precheck(check,now)!=="READY")return;this.start(now);}
  private block(c:{commandId:string;now:number},reasons:string[]){this.status=reasons.some(r=>r.endsWith("LIMIT")||r==="EXPIRED")?"LIMIT_REACHED":"HALTED";this.append("BLOCKED",c.now,c.commandId,"HALT","HALT",reasons);}
  private limitReasons(c:{commandId:string;quantity:number;price:number;now:number;metrics?:Readonly<{completedTrades:number;openPositions:number;grossExposure:number;dailyLoss:number;sessionLoss:number;drawdown:number;consecutiveLosses:number}>}){const a=this.input.approval,r:string[]=[];const m=c.metrics??{completedTrades:0,openPositions:0,grossExposure:0,dailyLoss:0,sessionLoss:0,drawdown:0,consecutiveLosses:0};if(Object.values(m).some(v=>!Number.isFinite(v)))return ["NON_FINITE_LIMIT_STATE"];if(this.commands.has(c.commandId))r.push("DUPLICATE_COMMAND");else this.commands.add(c.commandId);if(c.now>=a.expiresAt)r.push("EXPIRED");if(c.now-this.startedAt>=a.maxDurationMinutes*60000)r.push("DURATION_LIMIT");if(this.orders>=a.maxOrders)r.push("ORDER_LIMIT");if(m.completedTrades>=a.maxTrades)r.push("TRADE_LIMIT");if(m.openPositions>=a.maxOpenPositions)r.push("OPEN_POSITION_LIMIT");if(!finite(c.quantity)||!finite(c.price)||c.quantity>a.maxOrderQuantity)r.push("QUANTITY_LIMIT");const n=c.quantity*c.price;if(!Number.isFinite(n))r.push("NON_FINITE_LIMIT_STATE");else if(n>a.maxOrderNotional)r.push("NOTIONAL_LIMIT");if(m.grossExposure+n>a.maxGrossExposure)r.push("GROSS_EXPOSURE_LIMIT");if(m.dailyLoss>=a.maxDailyLoss)r.push("DAILY_LOSS_LIMIT");if(m.sessionLoss>=a.maxSessionLoss)r.push("SESSION_LOSS_LIMIT");if(m.drawdown>=a.maxDrawdown)r.push("DRAWDOWN_LIMIT");if(m.consecutiveLosses>=a.maxConsecutiveLosses)r.push("CONSECUTIVE_LOSS_LIMIT");return r.sort();}
  private append(type:CanaryEvent["eventType"],timestamp:number,commandId:string,riskDecision:CanaryEvent["riskDecision"],canaryDecision:CanaryEvent["canaryDecision"],reasonCodes:readonly string[],orderId?:string,fillId?:string,calls=0){const raw={sequence:this.events.length+1,timestamp,sessionId:this.input.sessionId,approvalId:this.input.approval.approvalId,eventType:type,commandId,clientOrderId:commandId,riskDecision,canaryDecision,reasonCodes:[...reasonCodes].sort(),...(orderId?{orderId}:{}),...(fillId?{fillId}:{}),actualBrokerCallCount:calls,previousEventSha256:this.events.at(-1)?.eventSha256??"GENESIS"};this.events.push(Object.freeze({...raw,eventSha256:hash(raw)}));}
}
export function verifyCanaryEvents(events:readonly CanaryEvent[]):readonly string[]{const errors:string[]=[];let previous="GENESIS";for(let i=0;i<events.length;i++){const {eventSha256,...raw}=events[i]!;if(raw.sequence!==i+1||raw.previousEventSha256!==previous||hash(raw)!==eventSha256)errors.push("CANARY_EVIDENCE_INVALID");previous=eventSha256;}return Object.freeze([...new Set(errors)]);}
