export enum BusinessServiceCriticality { TIER_0_SAFETY_CRITICAL = "TIER_0_SAFETY_CRITICAL", TIER_1_EXECUTION_CRITICAL = "TIER_1_EXECUTION_CRITICAL", TIER_2_OPERATIONAL = "TIER_2_OPERATIONAL", TIER_3_SUPPORTING = "TIER_3_SUPPORTING", UNKNOWN = "UNKNOWN" }
export enum ResilienceReadiness { READY = "READY", BLOCKED = "BLOCKED", UNKNOWN = "UNKNOWN" }
export interface RecoveryObjectives { readonly rtoMs: number; readonly rpoMs: number; readonly maximumTolerableDowntimeMs: number; }
export interface CriticalBusinessService { readonly businessServiceId: string; readonly canonicalName: string; readonly tenantId: string; readonly legalEntityId: string; readonly region: string; readonly jurisdiction: string; readonly environment: "PAPER" | "PRODUCTION"; readonly ownerId?: string; readonly criticality: BusinessServiceCriticality; readonly dependencyIds: readonly string[]; readonly recoveryPolicyId?: string; readonly continuityPlanId?: string; readonly objectives?: RecoveryObjectives; readonly recoveryPlanTestedAt?: number; readonly expiresAt?: number; readonly evidenceHash: string; }
export interface ResilienceReadinessResult { readonly serviceId: string; readonly readiness: ResilienceReadiness; readonly blockers: readonly string[]; readonly productionMutationAllowed: false; }
export interface ContinuityPlan { readonly planId: string; readonly version: string; readonly serviceId: string; readonly approvedAt?: number; readonly testedAt?: number; readonly expiresAt: number; readonly evidenceHash: string; }
export type ResilienceEventType = "PLAN_REGISTERED" | "PLAN_APPROVED" | "PLAN_TESTED" | "PLAN_EXPIRED";
export interface ResilienceLedgerEvent { readonly eventId: string; readonly type: ResilienceEventType; readonly occurredAt: number; readonly plan: ContinuityPlan; readonly evidenceHash: string; }
export interface ResilienceLedgerRecord { readonly sequence: number; readonly previousHash: string; readonly event: ResilienceLedgerEvent; readonly hash: string; }
export interface FailoverRequest { readonly requestId: string; readonly tenantId: string; readonly legalEntityId: string; readonly jurisdiction: string; readonly sourceRegion: string; readonly targetRegion: string; readonly sourceFenced: boolean; readonly targetSynchronized: boolean; readonly reconciliationHealthy: boolean; readonly approved: boolean; readonly evidenceHash: string; }
export interface FailoverDecision { readonly requestId: string; readonly decision: "ALLOW_READ_ONLY_FAILOVER" | "DENY" | "UNKNOWN"; readonly reasons: readonly string[]; readonly productionMutationAllowed: false; }
