import { createHash } from "node:crypto";
import type { StrategyGovernanceEvent, StrategyLifecycle } from "./strategyGovernance";

export interface StrategyGovernanceLedgerRecord { readonly sequence: number; readonly previousHash: string; readonly event: StrategyGovernanceEvent; readonly hash: string; }
export interface StrategyGovernanceState { readonly lifecycles: ReadonlyMap<string, StrategyLifecycle>; readonly champions: ReadonlyMap<string, string>; readonly hash: string; }
const genesis = "0".repeat(64);
const approvalReference = /^[A-Za-z0-9_.:/#@-]{1,240}$/;
const sha256 = /^[a-f0-9]{64}$/;
const containmentEventTypes = new Set<StrategyGovernanceEvent["type"]>(["STRATEGY_SUSPENDED", "STRATEGY_ROLLED_BACK", "STRATEGY_RETIRED"]);
const canonical = (event: StrategyGovernanceEvent): string => JSON.stringify({ family: event.family, lifecycle: event.lifecycle, occurredAt: event.occurredAt, reason: event.reason, strategyId: event.strategyId, type: event.type, version: event.version, ...(event.approval ? { approval: { actorType: event.approval.actorType, approvalReference: event.approval.approvalReference, approvedAt: event.approval.approvedAt, decisionFingerprint: event.approval.decisionFingerprint } } : {}) });
const hash = (sequence: number, previousHash: string, event: StrategyGovernanceEvent): string => createHash("sha256").update(`${sequence}\n${previousHash}\n${canonical(event)}`).digest("hex");
const key = (event: StrategyGovernanceEvent): string => `${event.strategyId}|${event.version}`;
const terminal = new Set<StrategyLifecycle>(["RETIRED", "REJECTED", "ROLLED_BACK"]);
const validateApproval = (event: StrategyGovernanceEvent): void => { const approval = event.approval; if (approval === undefined) return; const expectedLifecycle = event.type === "STRATEGY_SUSPENDED" ? "SUSPENDED" : event.type === "STRATEGY_ROLLED_BACK" ? "ROLLED_BACK" : "RETIRED"; if (!containmentEventTypes.has(event.type) || event.lifecycle !== expectedLifecycle) throw new Error("invalid governance approval event"); if (approval.actorType !== "HUMAN" || !approvalReference.test(approval.approvalReference) || !sha256.test(approval.decisionFingerprint) || !Number.isSafeInteger(approval.approvedAt) || approval.approvedAt < 0 || approval.approvedAt !== event.occurredAt) throw new Error("invalid governance approval"); };

export function appendStrategyGovernanceEvent(records: readonly StrategyGovernanceLedgerRecord[], event: StrategyGovernanceEvent): readonly StrategyGovernanceLedgerRecord[] {
  replayStrategyGovernanceLedger(records); if (!event.strategyId.trim() || !event.version.trim() || !event.family.trim() || !event.reason.trim() || !Number.isSafeInteger(event.occurredAt) || event.occurredAt < 0) throw new Error("invalid governance event"); validateApproval(event); const previousHash = records.at(-1)?.hash ?? genesis; const record = Object.freeze({ sequence: records.length + 1, previousHash, event: Object.freeze({ ...event, ...(event.approval ? { approval: Object.freeze({ ...event.approval }) } : {}) }), hash: hash(records.length + 1, previousHash, event) }); return Object.freeze([...records, record]);
}
export function replayStrategyGovernanceLedger(records: readonly StrategyGovernanceLedgerRecord[]): StrategyGovernanceState {
  const lifecycles = new Map<string, StrategyLifecycle>(); const champions = new Map<string, string>(); let previous = genesis; let last = -1;
  for (let index = 0; index < records.length; index += 1) { const record = records[index]!; validateApproval(record.event); if (record.sequence !== index + 1 || record.previousHash !== previous || record.hash !== hash(record.sequence, record.previousHash, record.event)) throw new Error("governance ledger integrity violation"); if (record.event.occurredAt < last) throw new Error("governance ledger timestamp regression"); const eventKey = key(record.event); const old = lifecycles.get(eventKey); if (old && terminal.has(old) && record.event.lifecycle !== old) throw new Error("terminal lifecycle cannot resume"); if (record.event.type === "CHAMPION_PROMOTED") { const incumbent = champions.get(record.event.family); if (incumbent && incumbent !== eventKey) lifecycles.set(incumbent, "CHALLENGER"); champions.set(record.event.family, eventKey); } if (record.event.type === "STRATEGY_ROLLED_BACK" || record.event.type === "STRATEGY_RETIRED") if (champions.get(record.event.family) === eventKey) champions.delete(record.event.family); lifecycles.set(eventKey, record.event.lifecycle); previous = record.hash; last = record.event.occurredAt; }
  return Object.freeze({ lifecycles, champions, hash: previous });
}
