import { evaluateRuntimeInvariants, type RuntimeInvariantObservation, type InvariantMonitorResult } from "./invariant-monitor";
export enum BurnInDecision { PASS="PASS", FAIL="FAIL", INCOMPLETE="INCOMPLETE" }
export interface BurnInSample { readonly sampleId:string; readonly sequence:number; readonly observedAtMs:number; readonly invariants:readonly RuntimeInvariantObservation[]; }
export interface BurnInPolicy { readonly requiredSamples:number; readonly minimumDurationMs:number; readonly maximumCriticalFailures:number; readonly maximumUnknownSamples:number; }
export interface BurnInResult { readonly runId:string; readonly decision:BurnInDecision; readonly sampleCount:number; readonly durationMs:number; readonly criticalFailureSamples:number; readonly unknownSamples:number; readonly blockingReasons:readonly string[]; readonly finalInvariantState:InvariantMonitorResult; readonly completedAtMs:number; }
export function runSyntheticBurnIn(input:{readonly runId:string;readonly samples:readonly BurnInSample[];readonly policy:BurnInPolicy;readonly nowMs:number;}):BurnInResult{
 if(!input.runId.trim()||!Number.isSafeInteger(input.nowMs)||input.nowMs<0)throw new Error("valid burn-in identity and time are required");
 const p=input.policy;if(!Number.isSafeInteger(p.requiredSamples)||p.requiredSamples<=0||!Number.isSafeInteger(p.minimumDurationMs)||p.minimumDurationMs<0||!Number.isSafeInteger(p.maximumCriticalFailures)||p.maximumCriticalFailures<0||!Number.isSafeInteger(p.maximumUnknownSamples)||p.maximumUnknownSamples<0)throw new Error("invalid burn-in policy");
 const ids=new Set<string>();let previousSequence=-1;let previousTime=-1;let criticalFailureSamples=0;let unknownSamples=0;let finalState=evaluateRuntimeInvariants([]);
 for(const sample of input.samples){if(!sample.sampleId.trim()||ids.has(sample.sampleId))throw new Error("duplicate or empty burn-in sample id");ids.add(sample.sampleId);if(!Number.isSafeInteger(sample.sequence)||sample.sequence<=previousSequence)throw new Error("burn-in sample sequence must increase");if(!Number.isSafeInteger(sample.observedAtMs)||sample.observedAtMs<previousTime||sample.observedAtMs>input.nowMs)throw new Error("burn-in sample time is invalid");previousSequence=sample.sequence;previousTime=sample.observedAtMs;finalState=evaluateRuntimeInvariants(sample.invariants);if(finalState.criticalFailureIds.length>0)criticalFailureSamples++;if(finalState.unknownIds.length>0)unknownSamples++;}
 const durationMs=input.samples.length<2?0:input.samples[input.samples.length-1].observedAtMs-input.samples[0].observedAtMs;const reasons:string[]=[];
 if(input.samples.length<p.requiredSamples)reasons.push("INSUFFICIENT_SAMPLES");if(durationMs<p.minimumDurationMs)reasons.push("INSUFFICIENT_DURATION");if(criticalFailureSamples>p.maximumCriticalFailures)reasons.push("CRITICAL_INVARIANT_FAILURES");if(unknownSamples>p.maximumUnknownSamples)reasons.push("UNKNOWN_INVARIANT_SAMPLES");
 const incomplete=reasons.includes("INSUFFICIENT_SAMPLES")||reasons.includes("INSUFFICIENT_DURATION");const decision=reasons.length===0?BurnInDecision.PASS:incomplete&&criticalFailureSamples<=p.maximumCriticalFailures&&unknownSamples<=p.maximumUnknownSamples?BurnInDecision.INCOMPLETE:BurnInDecision.FAIL;
 return Object.freeze({runId:input.runId,decision,sampleCount:input.samples.length,durationMs,criticalFailureSamples,unknownSamples,blockingReasons:Object.freeze(reasons.sort()),finalInvariantState,completedAtMs:input.nowMs});
}
