import { randomUUID } from "node:crypto";

export type ExecutionState =
  | "INTENT_CREATED" | "RISK_APPROVED" | "RISK_REJECTED" | "QUEUED" | "SUBMITTING"
  | "ACCEPTED" | "REJECTED" | "SUBMISSION_UNKNOWN" | "PARTIALLY_FILLED" | "FILLED"
  | "CANCEL_REQUESTED" | "CANCELING" | "CANCELED" | "EXPIRED"
  | "RECONCILIATION_REQUIRED" | "RECONCILED";

export type ReconciliationStatus = "NOT_REQUIRED" | "PENDING" | "MATCH" | "DIFF" | "UNKNOWN";
export interface ExecutionRecord {
  readonly executionId: string; readonly clientOrderId: string; readonly strategyId: string;
  readonly signalId: string | null; readonly exchange: "UPBIT"; readonly market: string;
  readonly side: "BUY" | "SELL"; readonly orderType: "MARKET" | "LIMIT";
  readonly requestedQuantity: string | null; readonly requestedQuoteAmount: string | null;
  readonly limitPrice: string | null; readonly state: ExecutionState;
  readonly exchangeOrderId: string | null; readonly submittedQuantity: string | null;
  readonly filledQuantity: string; readonly remainingQuantity: string | null;
  readonly averageFillPrice: string | null; readonly totalFee: string | null; readonly feeCurrency: string | null;
  readonly riskDecisionId: string | null; readonly reconciliationStatus: ReconciliationStatus;
  readonly createdAt: string; readonly updatedAt: string; readonly submittedAt: string | null;
  readonly acceptedAt: string | null; readonly completedAt: string | null; readonly version: number;
}
export interface ExecutionTransition { readonly transitionId: string; readonly executionId: string; readonly fromState: ExecutionState | null; readonly toState: ExecutionState; readonly reasonCode: string; readonly metadata: Readonly<Record<string, unknown>>; readonly createdAt: string; readonly sequence: number; }
export interface ExecutionFill { readonly fillId: string; readonly executionId: string; readonly exchangeTradeId: string; readonly quantity: string; readonly price: string; readonly fee: string | null; readonly feeCurrency: string | null; readonly executedAt: string; }
export interface CreateExecutionIntent { readonly strategyId: string; readonly signalId?: string | null; readonly market: string; readonly side: "BUY" | "SELL"; readonly orderType: "MARKET" | "LIMIT"; readonly requestedQuantity?: string | null; readonly requestedQuoteAmount?: string | null; readonly limitPrice?: string | null; readonly createdAt?: string; }
export interface ExchangeSubmitOrderRequest { readonly clientOrderId: string; readonly market: string; readonly side: "BUY" | "SELL"; readonly orderType: "MARKET" | "LIMIT"; readonly requestedQuantity: string | null; readonly requestedQuoteAmount: string | null; readonly limitPrice: string | null; }
export type ExchangeSubmitOrderResult = Readonly<{ status: "ACCEPTED"; exchangeOrderId: string }> | Readonly<{ status: "REJECTED"; reasonCode: string }> | Readonly<{ status: "UNKNOWN"; reasonCode: string }>;
export interface ExchangeOrderSnapshot { readonly exchangeOrderId: string | null; readonly clientOrderId: string | null; readonly state: "ACCEPTED" | "PARTIALLY_FILLED" | "FILLED" | "CANCELED" | "REJECTED" | "EXPIRED"; readonly fills: readonly ExecutionFill[]; }
export type ExchangeCancelOrderResult = Readonly<{ status: "CANCELED" | "FILLED" | "PARTIALLY_FILLED" }> | Readonly<{ status: "UNKNOWN"; reasonCode: string }>;
export interface ExchangeExecutionPort { submitOrder(request: ExchangeSubmitOrderRequest): Promise<ExchangeSubmitOrderResult>; cancelOrder(request: { readonly exchangeOrderId: string }): Promise<ExchangeCancelOrderResult>; getOrder(request: { readonly clientOrderId: string; readonly exchangeOrderId: string | null }): Promise<ExchangeOrderSnapshot>; }
export class LiveMutationDisabledError extends Error { public constructor() { super("LIVE_MUTATION_DISABLED"); this.name = "LiveMutationDisabledError"; } }
export class DisabledExchangeExecutionPort implements ExchangeExecutionPort { public readonly productionMutationAllowed = false as const; submitOrder(): Promise<ExchangeSubmitOrderResult> { return Promise.reject(new LiveMutationDisabledError()); } cancelOrder(): Promise<ExchangeCancelOrderResult> { return Promise.reject(new LiveMutationDisabledError()); } getOrder(): Promise<ExchangeOrderSnapshot> { return Promise.reject(new Error("LIVE_LOOKUP_UNAVAILABLE")); } }
export class FakeExchangeExecutionPort implements ExchangeExecutionPort { public readonly testOnly = true as const; public submitCalls = 0; public cancelCalls = 0; public constructor(private readonly submitResult: ExchangeSubmitOrderResult, private readonly cancelResult: ExchangeCancelOrderResult = { status: "CANCELED" }, private readonly snapshot?: ExchangeOrderSnapshot) {} submitOrder(): Promise<ExchangeSubmitOrderResult> { this.submitCalls += 1; return Promise.resolve(this.submitResult); } cancelOrder(): Promise<ExchangeCancelOrderResult> { this.cancelCalls += 1; return Promise.resolve(this.cancelResult); } getOrder(request: { readonly clientOrderId: string; readonly exchangeOrderId: string | null }): Promise<ExchangeOrderSnapshot> { return Promise.resolve(this.snapshot ?? { exchangeOrderId: request.exchangeOrderId, clientOrderId: request.clientOrderId, state: "ACCEPTED", fills: [] }); } }

const transitions: Readonly<Record<ExecutionState, readonly ExecutionState[]>> = {
  INTENT_CREATED: ["RISK_APPROVED", "RISK_REJECTED"], RISK_APPROVED: ["QUEUED"], QUEUED: ["SUBMITTING", "CANCELED"],
  SUBMITTING: ["ACCEPTED", "REJECTED", "SUBMISSION_UNKNOWN"], ACCEPTED: ["PARTIALLY_FILLED", "FILLED", "CANCEL_REQUESTED", "EXPIRED", "RECONCILIATION_REQUIRED"],
  PARTIALLY_FILLED: ["PARTIALLY_FILLED", "FILLED", "CANCEL_REQUESTED", "EXPIRED", "RECONCILIATION_REQUIRED"], CANCEL_REQUESTED: ["CANCELING", "RECONCILIATION_REQUIRED"],
  CANCELING: ["CANCELED", "FILLED", "PARTIALLY_FILLED", "SUBMISSION_UNKNOWN", "RECONCILIATION_REQUIRED"], SUBMISSION_UNKNOWN: ["ACCEPTED", "PARTIALLY_FILLED", "FILLED", "REJECTED", "RECONCILIATION_REQUIRED"],
  RECONCILIATION_REQUIRED: ["RECONCILED", "ACCEPTED", "PARTIALLY_FILLED", "FILLED", "CANCELED", "REJECTED", "EXPIRED"],
  RISK_REJECTED: [], REJECTED: [], FILLED: [], CANCELED: [], EXPIRED: [], RECONCILED: []
};
export function allowedExecutionTransitions(): Readonly<Record<ExecutionState, readonly ExecutionState[]>> { return transitions; }
export function assertExecutionTransition(from: ExecutionState, to: ExecutionState): void { if (from === to) return; if (!transitions[from].includes(to)) throw new Error(`INVALID_EXECUTION_TRANSITION:${from}->${to}`); }
function decimal(value: string | null | undefined, name: string): void { if (value != null && (!/^\d+(?:\.\d+)?$/.test(value) || value === "0")) throw new Error(`INVALID_DECIMAL:${name}`); }
function iso(value?: string): string { const x = value ?? new Date().toISOString(); if (Number.isNaN(Date.parse(x))) throw new Error("INVALID_TIMESTAMP"); return x; }
function sum(a: string, b: string): string { const [ai, af = ""] = a.split("."); const [bi, bf = ""] = b.split("."); const scale = Math.max(af.length, bf.length); const n = BigInt(`${ai}${af.padEnd(scale, "0")}`) + BigInt(`${bi}${bf.padEnd(scale, "0")}`); const s = n.toString().padStart(scale + 1, "0"); return scale === 0 ? s : `${s.slice(0, -scale)}.${s.slice(-scale)}`.replace(/\.0+$/, ""); }
/** Canonical decimal form so "0.10" and "0.1" compare equal. Exchange fill quantities arrive in arbitrary scales; a raw string comparison would wedge the execution in PARTIALLY_FILLED forever. */
function canonicalDecimal(value: string): string { if (!value.includes(".")) return value; const [head, tail] = value.split("."); const trimmed = tail.replace(/0+$/, ""); return trimmed === "" ? head : `${head}.${trimmed}`; }
function createRecord(input: CreateExecutionIntent, now: string): ExecutionRecord { decimal(input.requestedQuantity, "requestedQuantity"); decimal(input.requestedQuoteAmount, "requestedQuoteAmount"); decimal(input.limitPrice, "limitPrice"); return Object.freeze({ executionId: randomUUID(), clientOrderId: `nusa_${Date.now()}_${randomUUID().replaceAll("-", "")}`, strategyId: input.strategyId, signalId: input.signalId ?? null, exchange: "UPBIT", market: input.market, side: input.side, orderType: input.orderType, requestedQuantity: input.requestedQuantity ?? null, requestedQuoteAmount: input.requestedQuoteAmount ?? null, limitPrice: input.limitPrice ?? null, state: "INTENT_CREATED", exchangeOrderId: null, submittedQuantity: null, filledQuantity: "0", remainingQuantity: input.requestedQuantity ?? null, averageFillPrice: null, totalFee: null, feeCurrency: null, riskDecisionId: null, reconciliationStatus: "NOT_REQUIRED", createdAt: now, updatedAt: now, submittedAt: null, acceptedAt: null, completedAt: null, version: 1 } as ExecutionRecord); }

export interface ExecutionRepository { get(id: string): ExecutionRecord | null; getByClientOrderId(id: string): ExecutionRecord | null; save(record: ExecutionRecord, transition: ExecutionTransition): ExecutionRecord; transitions(id: string): readonly ExecutionTransition[]; fills(id: string): readonly ExecutionFill[]; appendFill(fill: ExecutionFill): void; listActive(): readonly ExecutionRecord[]; }
export class InMemoryExecutionRepository implements ExecutionRepository {
  private readonly records = new Map<string, ExecutionRecord>(); private readonly history = new Map<string, ExecutionTransition[]>(); private readonly fillMap = new Map<string, ExecutionFill[]>();
  get(id: string): ExecutionRecord | null { return this.records.get(id) ?? null; } getByClientOrderId(id: string): ExecutionRecord | null { return [...this.records.values()].find(x => x.clientOrderId === id) ?? null; }
  save(record: ExecutionRecord, transition: ExecutionTransition): ExecutionRecord { const old = this.records.get(record.executionId); if (old) { assertExecutionTransition(old.state, record.state); if (record.version !== old.version + 1) throw new Error("EXECUTION_VERSION_CONFLICT"); } else if (transition.fromState !== null || transition.sequence !== 1) throw new Error("INVALID_INITIAL_TRANSITION"); this.records.set(record.executionId, Object.freeze({ ...record })); const list = this.history.get(record.executionId) ?? []; if (list.some(x => x.sequence === transition.sequence)) throw new Error("DUPLICATE_TRANSITION_SEQUENCE"); list.push(Object.freeze(transition)); this.history.set(record.executionId, list); return record; }
  transitions(id: string): readonly ExecutionTransition[] { return Object.freeze([...(this.history.get(id) ?? [])]); } fills(id: string): readonly ExecutionFill[] { return Object.freeze([...(this.fillMap.get(id) ?? [])]); }
  appendFill(fill: ExecutionFill): void { const list = this.fillMap.get(fill.executionId) ?? []; const dupe = list.find(x => x.exchangeTradeId === fill.exchangeTradeId); if (dupe !== undefined) { if (dupe.quantity !== fill.quantity || dupe.price !== fill.price || dupe.fee !== fill.fee || dupe.feeCurrency !== fill.feeCurrency || dupe.executedAt !== fill.executedAt) throw new Error("EXECUTION_FILL_CONFLICT"); return; } decimal(fill.quantity, "fillQuantity"); decimal(fill.price, "fillPrice"); list.push(Object.freeze(fill)); this.fillMap.set(fill.executionId, list); }
  listActive(): readonly ExecutionRecord[] { return Object.freeze([...this.records.values()].filter(x => !["RISK_REJECTED", "REJECTED", "FILLED", "CANCELED", "EXPIRED", "RECONCILED"].includes(x.state))); }
}

export class ExecutionService {
  public constructor(private readonly repository: ExecutionRepository, private readonly port: ExchangeExecutionPort = new DisabledExchangeExecutionPort(), private readonly productionMutationAllowed = false) {}
  private transition(record: ExecutionRecord, state: ExecutionState, reasonCode: string, metadata: Readonly<Record<string, unknown>> = {}, patch: Partial<ExecutionRecord> = {}): ExecutionRecord { assertExecutionTransition(record.state, state); const now = new Date().toISOString(); const next = Object.freeze({ ...record, ...patch, state, updatedAt: now, version: record.version + 1, submittedAt: state === "SUBMITTING" ? now : record.submittedAt, acceptedAt: state === "ACCEPTED" ? now : record.acceptedAt, completedAt: ["RISK_REJECTED", "REJECTED", "FILLED", "CANCELED", "EXPIRED", "RECONCILED"].includes(state) ? now : record.completedAt, reconciliationStatus: state === "RECONCILIATION_REQUIRED" ? "PENDING" : record.reconciliationStatus }); const event: ExecutionTransition = Object.freeze({ transitionId: randomUUID(), executionId: record.executionId, fromState: record.state, toState: state, reasonCode, metadata, createdAt: now, sequence: this.repository.transitions(record.executionId).length + 1 }); return this.repository.save(next, event); }
  async createIntent(input: CreateExecutionIntent): Promise<ExecutionRecord> { if (!input.strategyId || !input.market) throw new Error("INVALID_EXECUTION_INTENT"); const now = iso(input.createdAt); const record = createRecord(input, now); if (this.repository.getByClientOrderId(record.clientOrderId)) throw new Error("DUPLICATE_CLIENT_ORDER_ID"); return this.repository.save(record, { transitionId: randomUUID(), executionId: record.executionId, fromState: null, toState: record.state, reasonCode: "INTENT_CREATED", metadata: {}, createdAt: now, sequence: 1 }); }
  async approveRisk(id: string, riskDecisionId: string): Promise<ExecutionRecord> { const r = this.require(id); return this.transition(r, "RISK_APPROVED", "RISK_APPROVED", { riskDecisionId }, { riskDecisionId }); }
  async rejectRisk(id: string, riskDecisionId: string, reasonCode: string): Promise<ExecutionRecord> { const r = this.require(id); return this.transition(r, "RISK_REJECTED", reasonCode, {}, { riskDecisionId }); }
  async queue(id: string): Promise<ExecutionRecord> { return this.transition(this.require(id), "QUEUED", "QUEUED"); }
  async submit(id: string): Promise<ExecutionRecord> { const r = this.require(id); if (r.state !== "QUEUED") throw new Error("SUBMIT_REQUIRES_QUEUED"); if (!this.productionMutationAllowed || this.port instanceof DisabledExchangeExecutionPort) throw new LiveMutationDisabledError(); const submitting = this.transition(r, "SUBMITTING", "SUBMIT_STARTED"); try { const result = await this.port.submitOrder({ clientOrderId: submitting.clientOrderId, market: submitting.market, side: submitting.side, orderType: submitting.orderType, requestedQuantity: submitting.requestedQuantity, requestedQuoteAmount: submitting.requestedQuoteAmount, limitPrice: submitting.limitPrice }); if (result.status === "ACCEPTED") return this.transition({ ...submitting, exchangeOrderId: result.exchangeOrderId }, "ACCEPTED", "EXCHANGE_ACCEPTED"); if (result.status === "REJECTED") return this.transition(submitting, "REJECTED", result.reasonCode); return this.transition(submitting, "SUBMISSION_UNKNOWN", result.reasonCode); } catch { return this.transition(submitting, "SUBMISSION_UNKNOWN", "SUBMISSION_OUTCOME_UNKNOWN"); } }
  async requestCancel(id: string): Promise<ExecutionRecord> { return this.transition(this.require(id), "CANCEL_REQUESTED", "CANCEL_REQUESTED"); }
  async cancel(id: string): Promise<ExecutionRecord> { const r = this.require(id); if (r.state !== "CANCEL_REQUESTED") throw new Error("CANCEL_REQUIRES_REQUEST"); const canceling = this.transition(r, "CANCELING", "CANCEL_STARTED"); try { const result = await this.port.cancelOrder({ exchangeOrderId: canceling.exchangeOrderId ?? "" }); if (result.status === "CANCELED") return this.transition(canceling, "CANCELED", "CANCEL_CONFIRMED"); if (result.status === "FILLED") return this.transition(canceling, "FILLED", "CANCEL_RACE_FILLED"); if (result.status === "PARTIALLY_FILLED") return this.transition(canceling, "PARTIALLY_FILLED", "CANCEL_RACE_PARTIAL"); if (result.status === "UNKNOWN") return this.transition(canceling, "RECONCILIATION_REQUIRED", result.reasonCode); throw new Error("INVALID_CANCEL_RESULT"); } catch { return this.transition(canceling, "SUBMISSION_UNKNOWN", "CANCEL_OUTCOME_UNKNOWN"); } }
  async reconcile(id: string): Promise<ExecutionRecord> { const r = this.require(id); if (r.state !== "SUBMISSION_UNKNOWN" && r.state !== "RECONCILIATION_REQUIRED" && r.state !== "ACCEPTED" && r.state !== "PARTIALLY_FILLED" && r.state !== "CANCELING") throw new Error("RECONCILIATION_NOT_REQUIRED"); const snapshot = await this.port.getOrder({ clientOrderId: r.clientOrderId, exchangeOrderId: r.exchangeOrderId }); if (snapshot.clientOrderId !== r.clientOrderId) return this.transition(r, "RECONCILIATION_REQUIRED", "RECONCILIATION_DIFF"); const target: ExecutionState = snapshot.state === "FILLED" ? "FILLED" : snapshot.state === "PARTIALLY_FILLED" ? "PARTIALLY_FILLED" : snapshot.state === "CANCELED" ? "CANCELED" : snapshot.state === "REJECTED" ? "REJECTED" : "ACCEPTED"; let current = r; for (const fill of snapshot.fills) { this.repository.appendFill(fill); current = this.applyFills(current); } return this.transition(current, target, "RECONCILIATION_MATCH"); }
  async addFill(fill: ExecutionFill): Promise<ExecutionRecord> { const r = this.require(fill.executionId); this.repository.appendFill(fill); return this.applyFills(r); }
  getExecution(id: string): Promise<ExecutionRecord | null> { return Promise.resolve(this.repository.get(id)); } listActiveExecutions(): Promise<readonly ExecutionRecord[]> { return Promise.resolve(this.repository.listActive()); }
  async replayRecovery(): Promise<readonly ExecutionRecord[]> { const active = this.repository.listActive(); const recovered: ExecutionRecord[] = []; for (const record of active) { if (["SUBMITTING", "SUBMISSION_UNKNOWN", "ACCEPTED", "PARTIALLY_FILLED", "CANCEL_REQUESTED", "CANCELING", "RECONCILIATION_REQUIRED"].includes(record.state)) { try { recovered.push(await this.reconcile(record.executionId)); } catch { recovered.push(record); } } } return Object.freeze(recovered); }
  private applyFills(record: ExecutionRecord): ExecutionRecord { const fills = this.repository.fills(record.executionId); const quantity = fills.reduce((x, f) => sum(x, f.quantity), "0"); const target = record.requestedQuantity != null && canonicalDecimal(quantity) === canonicalDecimal(record.requestedQuantity) ? "FILLED" : "PARTIALLY_FILLED" as ExecutionState; const priced = fills.reduce((x, f) => x + Number(f.quantity) * Number(f.price), 0); const qty = Number(quantity); return this.transition(record, target, target === "FILLED" ? "FILL_COMPLETE" : "FILL_PARTIAL", {}, { filledQuantity: quantity, averageFillPrice: Number.isFinite(priced / qty) ? String(priced / qty) : null, remainingQuantity: record.requestedQuantity == null ? null : String(Math.max(0, Number(record.requestedQuantity) - qty)) }); }
  private require(id: string): ExecutionRecord { const record = this.repository.get(id); if (!record) throw new Error("EXECUTION_NOT_FOUND"); return record; }
}
