import { OrderOperationalRestrictionReason, type OrderOperationalRestrictionRepository, type OrderOperationalRestrictionReleaseEvidenceRepository, type OrderRestrictionReleaseTransaction } from "./order-restriction";

export enum FillReconciliationStatus { MATCHED="MATCHED", MISSING_LOCAL="MISSING_LOCAL", MISSING_PROVIDER="MISSING_PROVIDER", QTY_MISMATCH="QTY_MISMATCH", PRICE_MISMATCH="PRICE_MISMATCH", ORDER_MISMATCH="ORDER_MISMATCH", DUPLICATE_LOCAL="DUPLICATE_LOCAL", DUPLICATE_PROVIDER="DUPLICATE_PROVIDER", PROVIDER_UNAVAILABLE="PROVIDER_UNAVAILABLE" }
export enum FillReconciliationFreshnessStatus { FRESH="FRESH", EXPIRING_SOON="EXPIRING_SOON", STALE="STALE", NOT_MATCHED="NOT_MATCHED" }
export interface FillRecord { readonly fillId:string; readonly tradeId:string; readonly orderId:string; readonly accountId:string; readonly symbol:string; readonly qtyRaw:bigint; readonly priceRaw:bigint; readonly fillTimeMs:number; }
export interface FillProvider { listFills(accountId:string, fromMs:number, toMs:number): readonly FillRecord[] | undefined; }
export interface FillReconciliationPolicy { readonly qtyToleranceRaw:bigint; readonly priceToleranceRaw:bigint; }
export interface FillReconciliationResult { readonly reconciliationId:string; readonly accountId:string; readonly status:FillReconciliationStatus; readonly localCount:number; readonly providerCount:number; readonly mismatchFillIds:readonly string[]; readonly observedAtMs:number; readonly restrictionId?:string; readonly reason?:string; }
export interface FillReconciliationEvidenceRepository { append(result:FillReconciliationResult):void; getById(id:string):FillReconciliationResult|undefined; getLatest(accountId:string):FillReconciliationResult|undefined; }
const abs=(v:bigint)=>v<0n?-v:v;
const duplicates=(records:readonly FillRecord[])=>{const seen=new Set<string>(), dup=new Set<string>(); for(const r of records){if(seen.has(r.fillId))dup.add(r.fillId);else seen.add(r.fillId);} return Object.freeze([...dup].sort());};
export function reconcileFills(input:{readonly reconciliationId:string;readonly restrictionId:string;readonly accountId:string;readonly local:readonly FillRecord[];readonly provider:FillProvider;readonly fromMs:number;readonly toMs:number;readonly nowMs:number;readonly policy:FillReconciliationPolicy;readonly restrictions:OrderOperationalRestrictionRepository;readonly evidence:FillReconciliationEvidenceRepository;}):FillReconciliationResult{
 if([input.reconciliationId,input.restrictionId,input.accountId].some(v=>v.trim()===""))throw new Error("fill reconciliation identity is required");
 if(!Number.isSafeInteger(input.fromMs)||!Number.isSafeInteger(input.toMs)||input.fromMs<0||input.toMs<input.fromMs||!Number.isSafeInteger(input.nowMs)||input.nowMs<input.toMs)throw new Error("fill reconciliation time window is invalid");
 if(input.policy.qtyToleranceRaw<0n||input.policy.priceToleranceRaw<0n)throw new Error("fill tolerances must be non-negative bigint");
 if(input.evidence.getById(input.reconciliationId))throw new Error("fill reconciliation id already exists");
 if(input.local.some(r=>r.accountId!==input.accountId||r.fillTimeMs<input.fromMs||r.fillTimeMs>input.toMs||r.qtyRaw<=0n||r.priceRaw<=0n))throw new Error("local fill outside scope");
 const remote=input.provider.listFills(input.accountId,input.fromMs,input.toMs); let status:FillReconciliationStatus; let mismatch:readonly string[]=Object.freeze([]);
 if(remote==null)status=FillReconciliationStatus.PROVIDER_UNAVAILABLE; else { if(remote.some(r=>r.accountId!==input.accountId||r.fillTimeMs<input.fromMs||r.fillTimeMs>input.toMs||r.qtyRaw<=0n||r.priceRaw<=0n))throw new Error("provider fill outside scope"); const ld=duplicates(input.local),rd=duplicates(remote); if(ld.length){status=FillReconciliationStatus.DUPLICATE_LOCAL;mismatch=ld;}else if(rd.length){status=FillReconciliationStatus.DUPLICATE_PROVIDER;mismatch=rd;}else{const l=new Map(input.local.map(r=>[r.fillId,r])),p=new Map(remote.map(r=>[r.fillId,r])); const ml=[...p.keys()].filter(id=>!l.has(id)).sort(),mp=[...l.keys()].filter(id=>!p.has(id)).sort(); const om=[...l].filter(([id,r])=>{const x=p.get(id);return x!=null&&(x.orderId!==r.orderId||x.tradeId!==r.tradeId||x.symbol!==r.symbol);}).map(([id])=>id).sort(); const qm=[...l].filter(([id,r])=>{const x=p.get(id);return x!=null&&abs(x.qtyRaw-r.qtyRaw)>input.policy.qtyToleranceRaw;}).map(([id])=>id).sort(); const pm=[...l].filter(([id,r])=>{const x=p.get(id);return x!=null&&abs(x.priceRaw-r.priceRaw)>input.policy.priceToleranceRaw;}).map(([id])=>id).sort(); if(ml.length){status=FillReconciliationStatus.MISSING_LOCAL;mismatch=Object.freeze(ml);}else if(mp.length){status=FillReconciliationStatus.MISSING_PROVIDER;mismatch=Object.freeze(mp);}else if(om.length){status=FillReconciliationStatus.ORDER_MISMATCH;mismatch=Object.freeze(om);}else if(qm.length){status=FillReconciliationStatus.QTY_MISMATCH;mismatch=Object.freeze(qm);}else if(pm.length){status=FillReconciliationStatus.PRICE_MISMATCH;mismatch=Object.freeze(pm);}else status=FillReconciliationStatus.MATCHED;}}
 let restrictionId:string|undefined; if(status!==FillReconciliationStatus.MATCHED){const r=input.restrictions.getActiveForAccount(input.accountId)??input.restrictions.save(Object.freeze({restrictionId:input.restrictionId,accountId:input.accountId,reason:status===FillReconciliationStatus.PROVIDER_UNAVAILABLE?OrderOperationalRestrictionReason.FILL_STATE_UNCERTAIN:OrderOperationalRestrictionReason.FILL_RECONCILIATION_MISMATCH,sourceRunId:input.reconciliationId,sourceIntentIds:Object.freeze([]),blockNewExposure:true,manualReleaseRequired:true,status:"ACTIVE",createdAtMs:input.nowMs}));restrictionId=r.restrictionId;}
 const result=Object.freeze({reconciliationId:input.reconciliationId,accountId:input.accountId,status,localCount:input.local.length,providerCount:remote?.length??0,mismatchFillIds:Object.freeze([...mismatch]),observedAtMs:input.nowMs,...(restrictionId?{restrictionId}:{}),...(status===FillReconciliationStatus.MATCHED?{}:{reason:"fills are not fully reconciled"})});input.evidence.append(result);return result;
}
export function evaluateFillReconciliationFreshness(result:FillReconciliationResult|undefined,nowMs:number,policy:{readonly staleAfterMs:number;readonly expiringSoonAfterMs:number;}):FillReconciliationFreshnessStatus{if(result==null||result.status!==FillReconciliationStatus.MATCHED)return FillReconciliationFreshnessStatus.NOT_MATCHED;if(policy.expiringSoonAfterMs<0||policy.staleAfterMs<=policy.expiringSoonAfterMs)throw new Error("invalid freshness policy");const age=nowMs-result.observedAtMs;if(age<0)throw new Error("freshness time is invalid");return age>=policy.staleAfterMs?FillReconciliationFreshnessStatus.STALE:age>=policy.expiringSoonAfterMs?FillReconciliationFreshnessStatus.EXPIRING_SOON:FillReconciliationFreshnessStatus.FRESH;}
export function releaseFillRestriction(input:{readonly releaseId:string;readonly restrictionId:string;readonly matchedFillReconciliationId:string;readonly requestedBy:string;readonly verifiedBy:string;readonly rationale:string;readonly nowMs:number;readonly restrictions:OrderOperationalRestrictionRepository;readonly reconciliations:FillReconciliationEvidenceRepository;readonly evidence:OrderOperationalRestrictionReleaseEvidenceRepository;readonly transaction?:OrderRestrictionReleaseTransaction;}){const operation=()=>{if(!input.releaseId.trim()||!input.matchedFillReconciliationId.trim()||!input.requestedBy.trim()||!input.verifiedBy.trim()||input.requestedBy===input.verifiedBy||!input.rationale.trim())throw new Error("valid separated fill release approval is required");const restriction=input.restrictions.getById(input.restrictionId);if(!restriction||restriction.status!=="ACTIVE"||![OrderOperationalRestrictionReason.FILL_RECONCILIATION_MISMATCH,OrderOperationalRestrictionReason.FILL_STATE_UNCERTAIN,OrderOperationalRestrictionReason.FILL_RECONCILIATION_STALE].includes(restriction.reason))throw new Error("active fill restriction not found");const matched=input.reconciliations.getById(input.matchedFillReconciliationId);if(!matched||matched.status!==FillReconciliationStatus.MATCHED||matched.accountId!==restriction.accountId||matched.observedAtMs<restriction.createdAtMs)throw new Error("later same-account matched fill evidence is required");input.evidence.append(Object.freeze({releaseId:input.releaseId,restrictionId:restriction.restrictionId,accountId:restriction.accountId,requestedBy:input.requestedBy,verifiedBy:input.verifiedBy,rationale:input.rationale.trim(),verifiedIntentIds:Object.freeze([]),matchedFillReconciliationId:matched.reconciliationId,releasedAtMs:input.nowMs}));return input.restrictions.save(Object.freeze({...restriction,status:"RELEASED",releasedAtMs:input.nowMs}));};return input.transaction?input.transaction.transaction(operation):operation();}
export class ScriptedSyntheticFillProvider implements FillProvider{public constructor(private readonly records?:readonly FillRecord[]){} listFills(accountId:string,fromMs:number,toMs:number){return this.records?.filter(r=>r.accountId===accountId&&r.fillTimeMs>=fromMs&&r.fillTimeMs<=toMs);}}
