import { randomUUID } from "node:crypto";

export type OperationsSessionState = "IDLE" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "BLOCKED";
export type OperationsAlertCode = "EXCHANGE_DISCONNECT" | "RISK_TRIGGER" | "KILL_SWITCH" | "API_ERROR" | "BALANCE_DIFFERENCE" | "RESTART_REQUIRED";
export interface DailyStartupCheck { readonly apiConnected: boolean; readonly balanceChecked: boolean; readonly openOrdersChecked: boolean; readonly shadowComparisonMatched: boolean; readonly reconciliationMatched: boolean; readonly riskHealthy: boolean; readonly killSwitchClear: boolean; readonly productionMutationAllowed: false; }
export interface OperationsSession { readonly sessionId: string; readonly mode: "PAPER" | "SHADOW" | "READ_ONLY" | "LIVE_DISABLED"; readonly state: OperationsSessionState; readonly startedAt: string | null; readonly stoppedAt: string | null; readonly blockerCodes: readonly string[]; }
export interface TradeRecord { readonly tradeId: string; readonly sessionId: string; readonly symbol: string; readonly side: "BUY" | "SELL"; readonly quantity: string; readonly price: string; readonly fee: string | null; readonly executedAt: string; }
export interface DailyReport { readonly reportId: string; readonly sessionId: string; readonly generatedAt: string; readonly openOrderCount: number; readonly tradeCount: number; readonly evidenceCount: number; readonly summary: Readonly<Record<string, unknown>>; readonly productionMutationAllowed: false; }
export interface OperationsEvidence { readonly evidenceId: string; readonly type: string; readonly sessionId: string; readonly createdAt: string; readonly payload: Readonly<Record<string, unknown>>; }
export interface AuditEvent { readonly auditId: string; readonly action: string; readonly actor: string; readonly createdAt: string; readonly payload: Readonly<Record<string, string>>; }
export const LIVE_OPERATIONS_DESCRIPTOR = Object.freeze({ liveOperationsPresent: true as const, productionMutationAllowed: false as const, privateApiMutationCapabilityPresent: false as const });
const now = () => new Date().toISOString();

export class OperationsAuditLog { private readonly events: AuditEvent[] = []; append(action: string, actor: string, payload: Readonly<Record<string, string>> = {}): AuditEvent { const event = Object.freeze({ auditId: randomUUID(), action, actor, createdAt: now(), payload: Object.freeze({ ...payload }) }); this.events.push(event); return event; } list(): readonly AuditEvent[] { return Object.freeze([...this.events]); } }
export class OperationsAlertCenter { private readonly alerts: Array<{ readonly alertId: string; readonly code: OperationsAlertCode; readonly message: string; readonly acknowledged: boolean; readonly createdAt: string }> = []; constructor(private readonly audit: OperationsAuditLog) {} raise(code: OperationsAlertCode, message: string): void { this.alerts.push(Object.freeze({ alertId: randomUUID(), code, message, acknowledged: false, createdAt: now() })); this.audit.append("ALERT_RAISED", "system", { code }); } acknowledge(alertId: string, actor: string): void { const index = this.alerts.findIndex(x => x.alertId === alertId); if (index < 0) throw new Error("ALERT_NOT_FOUND"); const alert = this.alerts[index]; this.alerts[index] = Object.freeze({ ...alert, acknowledged: true }); this.audit.append("ALERT_ACKNOWLEDGED", actor, { alertId, code: alert.code }); } list(): readonly typeof this.alerts[number][] { return Object.freeze([...this.alerts]); } }
export class OperationsEvidenceStore { private readonly events: OperationsEvidence[] = []; append(type: string, sessionId: string, payload: Readonly<Record<string, unknown>> = {}): OperationsEvidence { const event = Object.freeze({ evidenceId: randomUUID(), type, sessionId, createdAt: now(), payload: Object.freeze({ ...payload }) }); this.events.push(event); return event; } list(sessionId?: string): readonly OperationsEvidence[] { return Object.freeze(this.events.filter(x => !sessionId || x.sessionId === sessionId)); } exportJson(sessionId?: string): string { return JSON.stringify(this.list(sessionId), null, 2); } exportCsv(sessionId?: string): string { const values = this.list(sessionId); return ["evidenceId,type,sessionId,createdAt", ...values.map(x => [x.evidenceId, x.type, x.sessionId, x.createdAt].map(value => JSON.stringify(value)).join(","))].join("\n"); } }
export class LiveOperationsSessionManager {
  private session: OperationsSession = Object.freeze({ sessionId: "none", mode: "LIVE_DISABLED", state: "IDLE", startedAt: null, stoppedAt: null, blockerCodes: [] });
  private readonly trades: TradeRecord[] = [];
  public constructor(private readonly audit: OperationsAuditLog, private readonly evidence: OperationsEvidenceStore, private readonly alerts: OperationsAlertCenter) {}
  get current(): OperationsSession { return this.session; }
  start(check: DailyStartupCheck, mode: OperationsSession["mode"] = "LIVE_DISABLED"): OperationsSession { const blockers = Object.entries(check).filter(([key, value]) => key !== "productionMutationAllowed" && value === false).map(([key]) => key.toUpperCase()); if (check.productionMutationAllowed !== false) blockers.push("PRODUCTION_MUTATION_ENABLED"); if (blockers.length) { this.session = Object.freeze({ ...this.session, state: "BLOCKED", blockerCodes: Object.freeze(blockers) }); this.audit.append("SESSION_START_BLOCKED", "system", { blockers: blockers.join(",") }); return this.session; } const sessionId = randomUUID(); this.session = Object.freeze({ sessionId, mode, state: "RUNNING", startedAt: now(), stoppedAt: null, blockerCodes: [] }); this.audit.append("SESSION_START", "operator", { sessionId, mode }); this.evidence.append("SESSION_STARTED", sessionId, { mode }); return this.session; }
  stop(openOrderCount: number, reason = "OPERATOR_STOP"): DailyReport { if (this.session.state !== "RUNNING") throw new Error("SESSION_NOT_RUNNING"); this.session = Object.freeze({ ...this.session, state: "STOPPING" }); this.audit.append("SESSION_STOP", "operator", { sessionId: this.session.sessionId, reason }); if (openOrderCount > 0) this.alerts.raise("RESTART_REQUIRED", "Unfilled orders require reconciliation before another session"); const report: DailyReport = Object.freeze({ reportId: randomUUID(), sessionId: this.session.sessionId, generatedAt: now(), openOrderCount, tradeCount: this.trades.filter(x => x.sessionId === this.session.sessionId).length, evidenceCount: this.evidence.list(this.session.sessionId).length + 1, summary: { reason, liveTrading: false }, productionMutationAllowed: false }); this.evidence.append("DAILY_REPORT", this.session.sessionId, report as unknown as Record<string, unknown>); this.session = Object.freeze({ ...this.session, state: "STOPPED", stoppedAt: report.generatedAt }); this.audit.append("DAILY_REPORT_GENERATED", "system", { reportId: report.reportId, sessionId: report.sessionId }); return report; }
  recordTrade(trade: TradeRecord): void { if (this.session.state !== "RUNNING" || trade.sessionId !== this.session.sessionId) throw new Error("TRADE_SESSION_INVALID"); this.trades.push(Object.freeze(trade)); this.evidence.append("TRADE_RECORDED", trade.sessionId, { tradeId: trade.tradeId, symbol: trade.symbol, side: trade.side, quantity: trade.quantity }); }
}
