import { randomUUID } from "node:crypto";

export type RiskDecision = "APPROVED" | "REJECTED" | "BLOCKED" | "UNKNOWN";
export type KillReason = "EXCHANGE_DISCONNECT" | "UNKNOWN_SUBMISSION" | "RECONCILIATION_FAILURE" | "BALANCE_MISMATCH" | "API_FAILURE" | "MANUAL_STOP" | "DAILY_LOSS_EXCEEDED" | "EXPOSURE_EXCEEDED";
export interface RiskPolicy { readonly maxDailyLoss: number; readonly maxPositionSize: number; readonly maxExposure: number; readonly maxOpenOrders: number; readonly consecutiveLossLimit: number; readonly maxOrderSize: number; readonly symbolAllowlist: readonly string[]; readonly tradingSession: boolean; }
export interface RiskInput { readonly symbol: string; readonly dailyLoss: number; readonly positionSize: number; readonly exposure: number; readonly openOrders: number; readonly consecutiveLosses: number; readonly orderSize: number; readonly marketHealthy: boolean; readonly reconciliationHealthy: boolean; readonly warmupComplete: boolean; readonly apiHealthy: boolean; readonly exchangeConnected: boolean; readonly unknownSubmission: boolean; readonly balanceMatched: boolean; }
export interface RiskDecisionRecord { readonly decisionId: string; readonly result: RiskDecision; readonly reasonCodes: readonly string[]; readonly observedAt: string; readonly policyVersion: string; }
export interface KillSwitchSnapshot { readonly active: boolean; readonly reasons: readonly KillReason[]; readonly activatedAt: string | null; readonly updatedAt: string; }
export interface EvidenceSink { append(event: Readonly<Record<string, unknown>>): void; }
export const CAPABILITY_DESCRIPTOR = Object.freeze({ riskGatewayPresent: true as const, killSwitchPresent: true as const, productionMutationAllowed: false as const });

export class KillSwitch {
  private snapshot: KillSwitchSnapshot = Object.freeze({ active: false, reasons: [], activatedAt: null, updatedAt: new Date().toISOString() });
  public constructor(private readonly evidence?: EvidenceSink) {}
  get state(): KillSwitchSnapshot { return this.snapshot; }
  trigger(reason: KillReason, now = new Date().toISOString()): KillSwitchSnapshot { const reasons = [...new Set([...this.snapshot.reasons, reason])].sort() as KillReason[]; this.snapshot = Object.freeze({ active: true, reasons, activatedAt: this.snapshot.activatedAt ?? now, updatedAt: now }); this.evidence?.append({ type: "KILL_SWITCH_TRIGGERED", reason, observedAt: now }); return this.snapshot; }
  triggerMany(reasons: readonly KillReason[], now?: string): KillSwitchSnapshot { for (const reason of reasons) this.trigger(reason, now); return this.snapshot; }
  approveRelease(reviewer: string, now = new Date().toISOString()): KillSwitchSnapshot { if (!reviewer.trim()) throw new Error("KILL_RELEASE_REVIEWER_REQUIRED"); if (!this.snapshot.active) return this.snapshot; this.evidence?.append({ type: "KILL_SWITCH_RELEASE_APPROVED", reviewer, observedAt: now }); this.snapshot = Object.freeze({ active: false, reasons: [], activatedAt: null, updatedAt: now }); return this.snapshot; }
  restore(snapshot: KillSwitchSnapshot): void { if (snapshot.active && snapshot.reasons.length === 0) throw new Error("INVALID_KILL_SNAPSHOT"); this.snapshot = Object.freeze({ ...snapshot, reasons: Object.freeze([...snapshot.reasons]) }); }
}

function finite(value: number): boolean { return Number.isFinite(value); }
export class LiveRiskGateway {
  public constructor(private readonly policy: RiskPolicy, private readonly killSwitch: KillSwitch, private readonly evidence?: EvidenceSink, private readonly policyVersion = "risk-v1") {}
  evaluate(input: RiskInput, now = new Date().toISOString()): RiskDecisionRecord { const reasons: string[] = []; if (!Object.values(input).every(value => typeof value === "boolean" || typeof value === "string" || finite(value as number))) return this.record("UNKNOWN", ["RISK_INPUT_UNKNOWN"], now); if (!this.policy.tradingSession) reasons.push("TRADING_SESSION_CLOSED"); if (!this.policy.symbolAllowlist.includes(input.symbol)) reasons.push("SYMBOL_NOT_ALLOWED"); if (input.dailyLoss > this.policy.maxDailyLoss) { reasons.push("DAILY_LOSS_EXCEEDED"); this.killSwitch.trigger("DAILY_LOSS_EXCEEDED", now); } if (input.positionSize > this.policy.maxPositionSize) reasons.push("MAX_POSITION_SIZE"); if (input.exposure > this.policy.maxExposure) { reasons.push("EXPOSURE_EXCEEDED"); this.killSwitch.trigger("EXPOSURE_EXCEEDED", now); } if (input.openOrders >= this.policy.maxOpenOrders) reasons.push("MAX_OPEN_ORDERS"); if (input.consecutiveLosses >= this.policy.consecutiveLossLimit) reasons.push("CONSECUTIVE_LOSS_LIMIT"); if (input.orderSize > this.policy.maxOrderSize) reasons.push("MAX_ORDER_SIZE"); if (!input.marketHealthy || !input.exchangeConnected) { reasons.push("MARKET_UNHEALTHY"); this.killSwitch.trigger("EXCHANGE_DISCONNECT", now); } if (!input.reconciliationHealthy) { reasons.push("RECONCILIATION_UNHEALTHY"); this.killSwitch.trigger("RECONCILIATION_FAILURE", now); } if (!input.warmupComplete) reasons.push("WARMUP_INCOMPLETE"); if (!input.apiHealthy) { reasons.push("API_FAILURE"); this.killSwitch.trigger("API_FAILURE", now); } if (input.unknownSubmission) { reasons.push("UNKNOWN_SUBMISSION"); this.killSwitch.trigger("UNKNOWN_SUBMISSION", now); } if (!input.balanceMatched) { reasons.push("BALANCE_MISMATCH"); this.killSwitch.trigger("BALANCE_MISMATCH", now); } if (this.killSwitch.state.active) reasons.push("KILL_SWITCH_ACTIVE"); const result: RiskDecision = this.killSwitch.state.active ? "BLOCKED" : reasons.length ? "REJECTED" : "APPROVED"; return this.record(result, reasons, now); }
  assertApproved(decision: RiskDecisionRecord): void { if (decision.result !== "APPROVED") throw new Error(`RISK_${decision.result}:${decision.reasonCodes.join(",")}`); }
  private record(result: RiskDecision, reasonCodes: readonly string[], observedAt: string): RiskDecisionRecord { const record = Object.freeze({ decisionId: randomUUID(), result, reasonCodes: Object.freeze([...new Set(reasonCodes)].sort()), observedAt, policyVersion: this.policyVersion }); this.evidence?.append({ type: "RISK_DECISION", ...record }); return record; }
}

export class RiskSubmissionQueue { private readonly items: string[] = []; public constructor(private readonly killSwitch: KillSwitch) {} enqueue(id: string): void { if (this.killSwitch.state.active) throw new Error("QUEUE_BLOCKED_KILL_SWITCH"); if (!this.items.includes(id)) this.items.push(id); } drain(): readonly string[] { const result = [...this.items]; this.items.length = 0; return result; } clearOnKill(): void { if (this.killSwitch.state.active) this.items.length = 0; } get size(): number { return this.items.length; } }
