import { OrderOperationalRestrictionReason, type OrderOperationalRestriction, type OrderOperationalRestrictionReleaseEvidenceRepository, type OrderOperationalRestrictionRepository, type OrderRestrictionReleaseTransaction } from "./order-restriction";

export enum PnlReconciliationStatus { MATCHED="MATCHED", REALIZED_MISMATCH="REALIZED_MISMATCH", UNREALIZED_MISMATCH="UNREALIZED_MISMATCH", FUNDING_MISMATCH="FUNDING_MISMATCH", FEE_MISMATCH="FEE_MISMATCH", PROVIDER_UNAVAILABLE="PROVIDER_UNAVAILABLE" }
export enum PnlReconciliationFreshnessStatus { FRESH="FRESH", EXPIRING_SOON="EXPIRING_SOON", STALE="STALE", NOT_MATCHED="NOT_MATCHED" }
export interface PnlSnapshot { readonly accountId:string;readonly asset:string;readonly realizedPnlRaw:bigint;readonly unrealizedPnlRaw:bigint;readonly fundingPnlRaw:bigint;readonly feeRaw:bigint;readonly observedAtMs:number; }
export interface PnlProvider { getPnl(accountId:string,asset:string):PnlSnapshot|undefined; }
export interface PnlReconciliationPolicy { readonly realizedToleranceRaw:bigint;readonly unrealizedToleranceRaw:bigint;readonly fundingToleranceRaw:bigint;readonly feeToleranceRaw:bigint; }
export interface PnlReconciliationResult { readonly reconciliationId:string;readonly accountId:string;readonly asset:string;readonly status:PnlReconciliationStatus;readonly local:PnlSnapshot;readonly provider?:PnlSnapshot;readonly observedAtMs:number;readonly restrictionId?:string; }
export interface PnlReconciliationEvidenceRepository { append(result:PnlReconciliationResult):void;getById(id:string):PnlReconciliationResult|undefined;getLatest(accountId:string,asset:string):PnlReconciliationResult|undefined; }
const abs=(v:bigint)=>v<0n?-v:v;
const valid=(p:PnlReconciliationPolicy)=>Object.values(p).every(v=>typeof v==="bigint"&&v>=0n);
export function reconcilePnl(input:{readonly reconciliationId:string;readonly restrictionId:string;readonly local:PnlSnapshot;readonly provider:PnlProvider;readonly policy:PnlReconciliationPolicy;readonly restrictions:OrderOperationalRestrictionRepository;readonly evidence:PnlReconciliationEvidenceRepository;readonly nowMs:number;}):PnlReconciliationResult{
 if(!input.reconciliationId.trim()||!input.restrictionId.trim()||!input.local.accountId.trim()||!input.local.asset.trim())throw new Error("PnL reconciliation identity is required");if(!valid(input.policy)||!Number.isSafeInteger(input.nowMs)||input.nowMs<input.local.observedAtMs)throw new Error("PnL reconciliation policy or time is invalid");if(input.evidence.getById(input.reconciliationId))throw new Error("PnL reconciliation id already exists");
 const remote=input.provider.getPnl(input.local.accountId,input.local.asset);let status=PnlReconciliationStatus.MATCHED;
 if(!remote)status=PnlReconciliationStatus.PROVIDER_UNAVAILABLE;else{if(remote.accountId!==input.local.accountId||remote.asset!==input.local.asset||remote.observedAtMs>input.nowMs)throw new Error("provider PnL identity or time is invalid");if(abs(remote.realizedPnlRaw-input.local.realizedPnlRaw)>input.policy.realizedToleranceRaw)status=PnlReconciliationStatus.REALIZED_MISMATCH;else if(abs(remote.unrealizedPnlRaw-input.local.unrealizedPnlRaw)>input.policy.unrealizedToleranceRaw)status=PnlReconciliationStatus.UNREALIZED_MISMATCH;else if(abs(remote.fundingPnlRaw-input.local.fundingPnlRaw)>input.policy.fundingToleranceRaw)status=PnlReconciliationStatus.FUNDING_MISMATCH;else if(abs(remote.feeRaw-input.local.feeRaw)>input.policy.feeToleranceRaw)status=PnlReconciliationStatus.FEE_MISMATCH;}
 let restrictionId:string|undefined;if(status!==PnlReconciliationStatus.MATCHED){const r=input.restrictions.getActiveForAccount(input.local.accountId)??input.restrictions.save(Object.freeze({restrictionId:input.restrictionId,accountId:input.local.accountId,reason:status===PnlReconciliationStatus.PROVIDER_UNAVAILABLE?OrderOperationalRestrictionReason.PNL_STATE_UNCERTAIN:OrderOperationalRestrictionReason.PNL_RECONCILIATION_MISMATCH,sourceRunId:input.reconciliationId,sourceIntentIds:Object.freeze([]),blockNewExposure:true,manualReleaseRequired:true,status:"ACTIVE",createdAtMs:input.nowMs}));restrictionId=r.restrictionId;}
 const result=Object.freeze({reconciliationId:input.reconciliationId,accountId:input.local.accountId,asset:input.local.asset,status,local:input.local,provider:remote,observedAtMs:input.nowMs,...(restrictionId?{restrictionId}:{})});input.evidence.append(result);return result;
}
export function evaluatePnlFreshness(result:PnlReconciliationResult|undefined,nowMs:number,policy:{readonly maxAgeMs:number;readonly expiringSoonMs:number;}):PnlReconciliationFreshnessStatus{if(!result||result.status!==PnlReconciliationStatus.MATCHED)return PnlReconciliationFreshnessStatus.NOT_MATCHED;if(!Number.isSafeInteger(nowMs)||policy.maxAgeMs<=0||policy.expiringSoonMs<0||policy.expiringSoonMs>=policy.maxAgeMs||nowMs<result.observedAtMs)throw new Error("PnL freshness policy or time is invalid");const age=nowMs-result.observedAtMs;return age>policy.maxAgeMs?PnlReconciliationFreshnessStatus.STALE:age>=policy.maxAgeMs-policy.expiringSoonMs?PnlReconciliationFreshnessStatus.EXPIRING_SOON:PnlReconciliationFreshnessStatus.FRESH;}
export function enforcePnlFreshness(input:{readonly restrictionId:string;readonly accountId:string;readonly asset:string;readonly nowMs:number;readonly policy:{readonly maxAgeMs:number;readonly expiringSoonMs:number;};readonly restrictions:OrderOperationalRestrictionRepository;readonly evidence:PnlReconciliationEvidenceRepository;}):OrderOperationalRestriction|undefined{const latest=input.evidence.getLatest(input.accountId,input.asset);const state=evaluatePnlFreshness(latest,input.nowMs,input.policy);if(state===PnlReconciliationFreshnessStatus.FRESH||state===PnlReconciliationFreshnessStatus.EXPIRING_SOON)return undefined;return input.restrictions.getActiveForAccount(input.accountId)??input.restrictions.save(Object.freeze({restrictionId:input.restrictionId,accountId:input.accountId,reason:OrderOperationalRestrictionReason.PNL_RECONCILIATION_STALE,sourceRunId:latest?.reconciliationId??"NO_PNL_EVIDENCE",sourceIntentIds:Object.freeze([]),blockNewExposure:true,manualReleaseRequired:true,status:"ACTIVE",createdAtMs:input.nowMs}));}
export function releasePnlRestriction(input:{readonly releaseId:string;readonly restrictionId:string;readonly matchedPnlReconciliationId:string;readonly requestedBy:string;readonly verifiedBy:string;readonly rationale:string;readonly nowMs:number;readonly restrictions:OrderOperationalRestrictionRepository;readonly evidence:PnlReconciliationEvidenceRepository;readonly releaseEvidence:OrderOperationalRestrictionReleaseEvidenceRepository;readonly transaction?:OrderRestrictionReleaseTransaction;}):OrderOperationalRestriction{const op=()=>{if(!input.releaseId.trim()||!input.matchedPnlReconciliationId.trim()||!input.requestedBy.trim()||!input.verifiedBy.trim()||input.requestedBy===input.verifiedBy||!input.rationale.trim())throw new Error("valid separated PnL release approval is required");const r=input.restrictions.getById(input.restrictionId);if(!r||r.status!=="ACTIVE"||![OrderOperationalRestrictionReason.PNL_RECONCILIATION_MISMATCH,OrderOperationalRestrictionReason.PNL_STATE_UNCERTAIN,OrderOperationalRestrictionReason.PNL_RECONCILIATION_STALE].includes(r.reason))throw new Error("active PnL restriction not found");const match=input.evidence.getById(input.matchedPnlReconciliationId);if(!match||match.status!==PnlReconciliationStatus.MATCHED||match.accountId!==r.accountId||match.observedAtMs<r.createdAtMs)throw new Error("later matched PnL evidence is required");input.releaseEvidence.append(Object.freeze({releaseId:input.releaseId,restrictionId:r.restrictionId,accountId:r.accountId,requestedBy:input.requestedBy,verifiedBy:input.verifiedBy,rationale:input.rationale.trim(),verifiedIntentIds:Object.freeze([]),matchedPnlReconciliationId:match.reconciliationId,releasedAtMs:input.nowMs}));return input.restrictions.save(Object.freeze({...r,status:"RELEASED",releasedAtMs:input.nowMs}));};return input.transaction?input.transaction.transaction(op):op();}
export class ScriptedSyntheticPnlProvider implements PnlProvider{public constructor(private readonly snapshots:readonly PnlSnapshot[]){}getPnl(accountId:string,asset:string){return this.snapshots.find(s=>s.accountId===accountId&&s.asset===asset);}}
