import { createHash } from "node:crypto";
import type { PreTradeRiskDecision, PreTradeRiskRequest, RiskReasonCode } from "../../../packages/contracts/src/riskGateway";

const ORDER: readonly RiskReasonCode[] = ["LIVE_CAPABILITY_DETECTED","PRIVATE_API_CAPABILITY_DETECTED","KILL_SWITCH_ACTIVE","DEPLOYMENT_INTEGRITY_FAILED","STRATEGY_FINGERPRINT_MISMATCH","CONFIG_FINGERPRINT_MISMATCH","RUNTIME_FINGERPRINT_MISMATCH","RISK_POLICY_FINGERPRINT_MISMATCH","APPROVAL_MISSING","APPROVAL_EXPIRED","APPROVAL_SCOPE_MISMATCH","PERSISTENCE_UNHEALTHY","RECONCILIATION_FAILED","OPEN_P0_ALERT","MARKET_DATA_STALE","MARKET_DATA_RECONNECTING","MARKET_DATA_WARMING_UP","MARKET_DATA_GAP","MARKET_DATA_OUT_OF_ORDER","MARKET_DATA_INVALID","DUPLICATE_SIGNAL","DUPLICATE_COMMAND","DUPLICATE_CLIENT_ORDER_ID","OPEN_ORDER_LIMIT","MAX_ORDER_NOTIONAL","MAX_POSITION_NOTIONAL","INSUFFICIENT_CASH","INSUFFICIENT_POSITION","INVALID_REQUEST"];
const hash = (value: unknown): string => createHash("sha256").update(JSON.stringify(value), "utf8").digest("hex");
export interface IndependentRiskLimits { readonly maxOrderNotional: number; readonly maxPositionNotional: number; readonly maxOpenOrders: number; }
export interface RiskIdentityState { readonly strategyFingerprint: string; readonly configFingerprint: string; readonly runtimeFingerprint: string; readonly riskPolicyFingerprint: string; readonly seenSignalIds: ReadonlySet<string>; readonly seenCommandIds: ReadonlySet<string>; readonly seenClientOrderIds: ReadonlySet<string>; }
/** Evaluates an immutable Paper request without changing it, account state, or execution state. */
export function evaluatePreTradeRisk(request: PreTradeRiskRequest, identity: RiskIdentityState, limits: IndependentRiskLimits): PreTradeRiskDecision {
  const reasons = new Set<RiskReasonCode>(); const invalid = !request || request.schemaVersion !== 1 || ![request.requestId,request.signalId,request.commandId,request.clientOrderId,request.symbol,request.strategyFingerprint,request.configFingerprint,request.runtimeFingerprint,request.riskPolicyFingerprint].every((value) => typeof value === "string" && value.length > 0) || ![request.quantity,request.referencePrice,request.requestedAt].every(Number.isFinite) || request.quantity <= 0 || request.referencePrice <= 0 || !["BUY","SELL"].includes(request.side);
  if (invalid) reasons.add("INVALID_REQUEST");
  if (request.controlState.liveCapabilityDetected) reasons.add("LIVE_CAPABILITY_DETECTED"); if (request.controlState.privateApiCapabilityDetected) reasons.add("PRIVATE_API_CAPABILITY_DETECTED"); if (request.controlState.killSwitchActive) reasons.add("KILL_SWITCH_ACTIVE");
  if (request.strategyFingerprint !== identity.strategyFingerprint) reasons.add("STRATEGY_FINGERPRINT_MISMATCH"); if (request.configFingerprint !== identity.configFingerprint) reasons.add("CONFIG_FINGERPRINT_MISMATCH"); if (request.runtimeFingerprint !== identity.runtimeFingerprint) reasons.add("RUNTIME_FINGERPRINT_MISMATCH"); if (request.riskPolicyFingerprint !== identity.riskPolicyFingerprint) reasons.add("RISK_POLICY_FINGERPRINT_MISMATCH");
  if (!request.approvalState.approved) reasons.add("APPROVAL_MISSING"); if (request.approvalState.expiresAt < request.requestedAt) reasons.add("APPROVAL_EXPIRED"); if (!request.approvalState.symbols.includes(request.symbol)) reasons.add("APPROVAL_SCOPE_MISMATCH");
  if (!request.persistenceState.healthy) reasons.add("PERSISTENCE_UNHEALTHY"); if (!request.reconciliationState.healthy) reasons.add("RECONCILIATION_FAILED"); if (request.reconciliationState.openP0) reasons.add("OPEN_P0_ALERT");
  const market = request.marketDataState.status; if (market !== "HEALTHY") reasons.add(({"STALE":"MARKET_DATA_STALE","RECONNECTING":"MARKET_DATA_RECONNECTING","WARMING_UP":"MARKET_DATA_WARMING_UP","GAP_DETECTED":"MARKET_DATA_GAP","OUT_OF_ORDER":"MARKET_DATA_OUT_OF_ORDER","INVALID":"MARKET_DATA_INVALID"} as const)[market]);
  if (identity.seenSignalIds.has(request.signalId)) reasons.add("DUPLICATE_SIGNAL"); if (identity.seenCommandIds.has(request.commandId)) reasons.add("DUPLICATE_COMMAND"); if (identity.seenClientOrderIds.has(request.clientOrderId)) reasons.add("DUPLICATE_CLIENT_ORDER_ID");
  const notional = request.quantity * request.referencePrice; if (request.accountState.openOrderCount >= limits.maxOpenOrders) reasons.add("OPEN_ORDER_LIMIT"); if (notional > limits.maxOrderNotional) reasons.add("MAX_ORDER_NOTIONAL"); if (request.side === "BUY" && notional > request.accountState.cash) reasons.add("INSUFFICIENT_CASH"); if (request.side === "SELL" && request.quantity > request.accountState.positionQuantity) reasons.add("INSUFFICIENT_POSITION"); if (request.accountState.positionQuantity * request.referencePrice + (request.side === "BUY" ? notional : 0) > limits.maxPositionNotional) reasons.add("MAX_POSITION_NOTIONAL");
  const ordered = ORDER.filter((code) => reasons.has(code)); const halt = ordered.some((code) => ORDER.indexOf(code) <= ORDER.indexOf("OPEN_P0_ALERT")); const status = ordered.length === 0 ? "ALLOW" : halt ? "HALT" : "REJECT"; const requestSha256 = hash(request); return Object.freeze({ status, reasonCodes: Object.freeze(ordered), evaluatedAt: request.requestedAt, requestSha256, decisionSha256: hash({ status, reasonCodes: ordered, requestSha256 }), productionMutationAllowed: false });
}
