import type { RegisteredStrategy, StrategyGovernanceApproval, StrategyGovernanceEvent, StrategyIdentity, StrategyLifecycle } from "../../../packages/contracts/src/strategyGovernance";
import { StrategyRegistry } from "./strategyRegistry";
import { appendStrategyGovernanceEvent, type StrategyGovernanceLedgerRecord } from "./strategyGovernanceLedger";
import { evaluateStrategyContainment, fingerprintStrategyContainmentDecision, type StrategyContainmentDecision, type StrategyContainmentInput } from "./strategyRollbackEngine";
export interface GovernancePersistence { append(strategy:RegisteredStrategy,event:StrategyGovernanceEvent):void; verify():void; claimCommand(commandId:string,fingerprint:string):boolean; hasCommand?: (commandId:string,fingerprint:string)=>boolean; listStrategies():readonly RegisteredStrategy[]; listEvents?:()=>readonly StrategyGovernanceLedgerRecord[]; }
const approvalReference=/^[A-Za-z0-9_.:/#@-]{1,240}$/;
const reasonCode=/^[A-Z0-9_:-]{1,120}$/;
const sha256=/^[a-f0-9]{64}$/;
const containmentEventTypes=new Set<StrategyGovernanceEvent["type"]>(["STRATEGY_SUSPENDED","STRATEGY_ROLLED_BACK","STRATEGY_RETIRED"]);
const containmentEventFor=(decision:StrategyContainmentDecision):StrategyGovernanceEvent["type"]=>decision.action==="SUSPEND"?"STRATEGY_SUSPENDED":decision.action==="ROLLBACK"?"STRATEGY_ROLLED_BACK":"STRATEGY_RETIRED";
const targetLifecycleFor=(decision:StrategyContainmentDecision):StrategyLifecycle=>decision.action==="SUSPEND"?"SUSPENDED":decision.action==="ROLLBACK"?"ROLLED_BACK":"RETIRED";
const validateApproval=(decision:StrategyContainmentDecision,approval:StrategyGovernanceApproval):void=>{if(decision.action==="HOLD")throw new Error("STRATEGY_CONTAINMENT_NO_ACTION");if(decision.requiresHumanApproval!==true||decision.productionMutationAllowed!==false||decision.liveAuthority!=="NONE")throw new Error("STRATEGY_CONTAINMENT_AUTHORITY_INVALID");if(approval.actorType!=="HUMAN"||!approvalReference.test(approval.approvalReference)||!sha256.test(approval.decisionFingerprint)||!Number.isSafeInteger(approval.approvedAt)||approval.approvedAt<decision.decidedAt)throw new Error("STRATEGY_CONTAINMENT_APPROVAL_INVALID");if(fingerprintStrategyContainmentDecision(decision)!==approval.decisionFingerprint)throw new Error("STRATEGY_CONTAINMENT_APPROVAL_MISMATCH");if(!Array.isArray(decision.reasons)||decision.reasons.length===0||decision.reasons.some((reason)=>!reasonCode.test(reason)))throw new Error("STRATEGY_CONTAINMENT_REASON_INVALID");};
export class StrategyGovernanceService { private readonly registry=new StrategyRegistry();private records:readonly StrategyGovernanceLedgerRecord[]=Object.freeze([]);private readonly commandIds=new Map<string,string>();constructor(private readonly store?:GovernancePersistence){}
  restorePersistedState(): void { if (!this.store) throw new Error("governance persistence is unavailable"); this.store.verify(); this.records=Object.freeze([...(this.store.listEvents?.() ?? [])]); this.registry.restore(this.store.listStrategies()); }
  evaluateContainment(input: StrategyContainmentInput): StrategyContainmentDecision { this.store?.verify(); return evaluateStrategyContainment(input); }
  applyContainmentDecision(commandId:string,decision:StrategyContainmentDecision,approval:StrategyGovernanceApproval,family=decision.strategyId):void{validateApproval(decision,approval);if(!family.trim())throw new Error("strategy family is required");const type=containmentEventFor(decision);const lifecycle=targetLifecycleFor(decision);const fingerprint=`${decision.strategyId}|${decision.version}|${type}|${lifecycle}|${approval.approvedAt}|${approval.decisionFingerprint}`;const current=this.registry.getStrategy(decision.strategyId,decision.version);if(!current)throw new Error("strategy not registered");if(current.lifecycle!==decision.currentLifecycle){if(this.commandIds.get(commandId)===fingerprint||this.store?.hasCommand?.(commandId,fingerprint)===true)return;throw new Error("STRATEGY_CONTAINMENT_STALE");}this.transitionWithApproval(commandId,decision.strategyId,decision.version,type,lifecycle,family,approval.approvedAt,`containment:${decision.reasons.join(",")}`,approval);}
  register(commandId:string,identity:StrategyIdentity,now:number):RegisteredStrategy{return this.command(commandId,JSON.stringify(identity),()=>{const s=this.registry.registerStrategy(identity,"DRAFT");this.record(s,"STRATEGY_REGISTERED","DRAFT",now,"registered");return s;});}
  transition(commandId:string,strategyId:string,version:string,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,family:string,now:number,reason:string,killSwitchActive=false):void{if(containmentEventTypes.has(type))throw new Error("STRATEGY_CONTAINMENT_APPROVAL_REQUIRED");this.commitTransition(commandId,strategyId,version,type,lifecycle,family,now,reason,killSwitchActive);}
  private transitionWithApproval(commandId:string,strategyId:string,version:string,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,family:string,now:number,reason:string,approval:StrategyGovernanceApproval):void{if(!containmentEventTypes.has(type))throw new Error("STRATEGY_CONTAINMENT_EVENT_INVALID");this.commitTransition(commandId,strategyId,version,type,lifecycle,family,now,reason,false,approval);}
  private commitTransition(commandId:string,strategyId:string,version:string,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,family:string,now:number,reason:string,killSwitchActive:boolean,approval?:StrategyGovernanceApproval):void{this.command(commandId,`${strategyId}|${version}|${type}|${lifecycle}|${now}|${approval?.decisionFingerprint??""}`,()=>{if((type as string)==="CHAMPION_PROMOTED")throw new Error("champion mutation requires CandidatePromotionRuntime owner command");if(killSwitchActive&&(type==="PROMOTION_REQUESTED"))throw new Error("kill switch blocks promotion");const s=this.registry.getStrategy(strategyId,version);if(!s)throw new Error("strategy not registered");this.record(s,type,lifecycle,now,reason,family,approval);this.registry.updateLifecycle(strategyId,version,lifecycle);});}
  private command<T>(id:string,fingerprint:string,run:()=>T):T{if(!id.trim())throw new Error("command id is required");const prior=this.commandIds.get(id);if(prior!==undefined){if(prior!==fingerprint)throw new Error("command conflict");return undefined as T;}this.store?.verify();if(this.store&&!this.store.claimCommand(id,fingerprint)){this.commandIds.set(id,fingerprint);return undefined as T;}const result=run();this.commandIds.set(id,fingerprint);return result;}
  private record(s:RegisteredStrategy,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,occurredAt:number,reason:string,family=s.identity.strategyId,approval?:StrategyGovernanceApproval):void{const e=Object.freeze({type,strategyId:s.identity.strategyId,version:s.identity.version,lifecycle,family,occurredAt,reason,...(approval?{approval:Object.freeze({...approval})}: {})});const next=appendStrategyGovernanceEvent(this.records,e as StrategyGovernanceEvent);this.store?.append(s,e as StrategyGovernanceEvent);this.records=next;}
}
