import type { RegisteredStrategy, StrategyGovernanceEvent, StrategyIdentity, StrategyLifecycle } from "../../../packages/contracts/src/strategyGovernance";
import { StrategyRegistry } from "./strategyRegistry";
import { appendStrategyGovernanceEvent, type StrategyGovernanceLedgerRecord } from "./strategyGovernanceLedger";
export interface GovernancePersistence { append(strategy:RegisteredStrategy,event:StrategyGovernanceEvent):void; verify():void; }
export class StrategyGovernanceService { private readonly registry=new StrategyRegistry();private records:readonly StrategyGovernanceLedgerRecord[]=Object.freeze([]);private readonly commandIds=new Map<string,string>();constructor(private readonly store?:GovernancePersistence){}
  register(commandId:string,identity:StrategyIdentity,now:number):RegisteredStrategy{return this.command(commandId,JSON.stringify(identity),()=>{const s=this.registry.registerStrategy(identity,"DRAFT");this.record(s,"STRATEGY_REGISTERED","DRAFT",now,"registered");return s;});}
  transition(commandId:string,strategyId:string,version:string,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,family:string,now:number,reason:string,killSwitchActive=false):void{this.command(commandId,`${strategyId}|${version}|${type}|${lifecycle}|${now}`,()=>{if(killSwitchActive&&(type==="PROMOTION_REQUESTED"||type==="CHAMPION_PROMOTED"))throw new Error("kill switch blocks promotion");const s=this.registry.getStrategy(strategyId,version);if(!s)throw new Error("strategy not registered");this.record(s,type,lifecycle,now,reason,family);});}
  private command<T>(id:string,fingerprint:string,run:()=>T):T{if(!id.trim())throw new Error("command id is required");const prior=this.commandIds.get(id);if(prior!==undefined){if(prior!==fingerprint)throw new Error("command conflict");return undefined as T;}this.store?.verify();const result=run();this.commandIds.set(id,fingerprint);return result;}
  private record(s:RegisteredStrategy,type:StrategyGovernanceEvent["type"],lifecycle:StrategyLifecycle,occurredAt:number,reason:string,family=s.identity.strategyId):void{const e:Object=Object.freeze({type,strategyId:s.identity.strategyId,version:s.identity.version,lifecycle,family,occurredAt,reason});this.records=appendStrategyGovernanceEvent(this.records,e as StrategyGovernanceEvent);this.store?.append(s,e as StrategyGovernanceEvent);}
}
